### ISSUE TITLE
Account Level Access

### ISSUE THREAD

**Issue by comicreliefinc** [basecamp/bc3-api#101]
Is there a way to get Account level access for a whole account? We want to access all projects under our account and not just those that the user is part of. 

We've tried authenticating on Admins and the Owner of the account but can't seem to find a way to get an over view of the entire account.

**Comment by georgeclaghorn** [comment]
Afraid not. You’ll need to authenticate as a person with access to all projects and teams.

**Comment by comicreliefinc** [comment]
Could this be added as a feature request? I understand having user level OAuth access, however there are a number of uses for an administrative level access as well.
