### ISSUE TITLE
Webhooks: Creating a To-Do and assigning it to someone results in two separate out of order webhooks

### ISSUE THREAD

**Issue by SeBsZ** [basecamp/bc3-api#103]
When you create a new To-Do and immediately assign it to someone upon creation, two webhooks are called: todo_created and todo_assignment_changed. Unfortunately, in most cases these two are actually in the wrong order and todo_assignment_changed comes first.

Would it be possible to combine these into a single webhook like in BC2? Here's a suggestion of how the payload could look. I'm using added_person_ids just like in todo_assignment_changed:

```{
  "id": 650436650,
  "kind": "todo_created",
  "details": {
    {"added_person_ids":[196524]}
  },
  "created_at": "2017-03-08T23:24:07.511+01:00",
  "recording": {
    "id": xxxx,
    ......```

**Comment by archon810** [comment]
Less spam = good, so anything that can be combined within, say, a 5-second period (or even 1-second - in the case we examined, the timestamps differed by <0.01s), because it relates to the same item, should be. Especially if BC2 did it.

Thanks!

cc @georgeclaghorn.

**Comment by rosa** [comment]
Having these two events makes sense internally because of the way we send different notifications (when a todo is assigned v. when a todo is created) and combining them in one just for webhooks is not trivial, so it's not very likely to happen. But I'd like to understand why it's a problem now, and see what alternatives we can come up with! Are there any issues with the current implementation?

**Comment by archon810** [comment]
@SeBsZ can correct me if I'm wrong but perhaps this was already resolved, or we worked around it? Because I just added a test event assigned to myself, and our webhook processor output only 1 thing: "Artem Russakovskii added a to-do TODO List → Test and assigned it to Artem Russakovskii."

**Comment by SeBsZ** [comment]
Yeah. Sorry about the late reply. We actually ignore todo_assignment_changed when it is less than a second or so from when the todo itself was created.
