### ISSUE TITLE
Pings

### ISSUE THREAD

**Issue by gps** [basecamp/bc3-api#105]
#1 had 

> Get, create pings

on the list, but was closed without it being added to the list of endpoints.

What I'd like to be able to do:

- Given a list of users, get a url that can be opened in a browser which will ping those users (assuming the user is logged in on that browser)
- List all existing pings for a user (should include participants, and a url that can be opened in a web browser, again assuming the user is logged in on that browser)

#93 talks about being able to ping a user through the API, so this may be a duplicate.

**Comment by georgeclaghorn** [comment]
Closing in favor of #93. Thanks!
