### ISSUE TITLE
"Enable this webhook" cannot be toggled after initial webhook creation

### ISSUE THREAD

**Issue by archon810** [basecamp/bc3-api#107]
Hi,

When editing a webhook (https://3.basecamp.com/NNNNN/buckets/MMMMM/webhooks/OOOOO/edit), I cannot seem to toggle the "Enable this webhook" toggle on or off. The other toggles all work when I save, but disabling or enabling does not.

So, right now our webhook got disabled because of Cloudflare challenges (which I'm fixing), and I can't re-enable it. I'll have to create a new hook for now.

Would be good to get this fixed.

Thanks.

cc @sebsz

**Comment by archon810** [comment]
P.S. Now that I think about it, it'd be good to get an email when a web hook gets deactivated due to errors. For instance, in our case, because of Cloudflare challenges, the hook got disabled hours ago, but I only found out about it when I got flagged by some of our staff.

**Comment by archon810** [comment]
cc @georgeclaghorn

**Comment by georgeclaghorn** [comment]
Fixed the “Enable this webhook?“ checkbox. Sorry for the trouble!

**Comment by archon810** [comment]
Thanks, confirmed working.
