### ISSUE TITLE
how to archive and activate a basecamp through the api not in the docs 

### ISSUE THREAD

**Issue by pskrz** [basecamp/bc3-api#109]
I couldn't find it in the current documentation, but it looks like this commit had the information https://github.com/basecamp/bc3-api/commit/4bf33f12580a188157500d3dcad29b90751c5c40 , maybe it got wiped out somehow?

**Comment by pskrz** [comment]
here we go, looks like it was removed in a later commit https://github.com/basecamp/bc3-api/commit/0817e2bf3f758c24660850e669465f6ac5aae83a

**Comment by pskrz** [comment]
When I put against the archive endpoint I get a `302 Found`, I'd expect a 200.

using put against /projects/<projectid>/status/archived.json

The project archives, so I'm not sure what I may have done or if it's an error.

**Comment by georgeclaghorn** [comment]
We don’t currently support archiving projects and teams via the API. Sorry!

**Comment by pskrz** [comment]
dang wonder how it worked then

**Comment by pskrz** [comment]
also, any plans to support? I have a basecamp 2 integration feature that uses this, I don't really wanna lose features with my basecamp 3 integration
