### ISSUE TITLE
authorization/token returns a 404 when called

### ISSUE THREAD

**Issue by Elhebert** [basecamp/bc3-api#110]
From the scraps and bits I could gather here and there (it's safe to say that the documentation isn't really well documented), to refresh a token, the url that we're supposed to call is: `https://launchpad.37signals.com/authorization/token`.

But, so far, it's returning `{"status":404,"error":"Not Found"}`, which isn't really helpful.

If there is a new url to call or a new *way* to refresh an access token, would be nice if it was documented.

**Comment by georgeclaghorn** [comment]
Can you send an email to support@basecamp.com with the X-Request-ID header from a 404 response? We can track down what’s happening and help you out.
