### ISSUE TITLE
support for archive and unarchive Projects endpoints

### ISSUE THREAD

**Issue by pskrz** [basecamp/bc3-api#111]
From the following linked issue I found out that archive and unarchive project endpoints are not supported, currently, https://github.com/basecamp/bc3-api/issues/109 . Opening this issue since that one was closed.

Use case: The organization I work for use archive and unarchive project endpoints with a Basecamp 2 integration, the feature is well received. We are in the process of upgrading to Basecamp 3 and we don't wan't to lose these features.

These endpoints currently 'work' with the Basecamp 3 api but it returns a 302. 

I'm not sure what else to say other than, could the Basecamp 3 api please provide support for these endpoints?

**Comment by pskrz** [comment]
Jumping in here asking for status/update on this issue, please

**Comment by pskrz** [comment]
Pinging here, can I get an update on this issue, please?

**Comment by jeremy** [comment]
Documented in #164. Thanks @pskrz!

**Comment by pskrz** [comment]
That documentation is for recordings, I was asking about projects. I don't think I can archive/unarchive a project through recordings endpoints. I'm left wondering why projects don't have support for archive/unarchive. They work currently, and I use them, but I don't want to lose this feature in the future because they're 'unsupported'.
