### ISSUE TITLE
Feature Request: Endpoint for Notifications

### ISSUE THREAD

**Issue by bcjarrett** [basecamp/bc3-api#114]
It would be wonderful to define the people on the "When someone comments on this RECORD, a notification will be sent to:" list.  This would be particularly useful for creating messages, but also great for helping users track to-dos they care about.

If I create a message only intended for a few people the API automatically adds everyone to the notification list, which fills inboxes with emails that are not relevant to users, causing them to ignore basecamp emails all together.

It's very important that every notification a user gets is worth their time, as well as ensuring they get every email they should. The current API does not appear to let me address that.

**Comment by rosa** [comment]
@bcjarrett we already have this. Check out the API documentation for `subscriptions` [here](https://github.com/basecamp/bc3-api/blob/master/sections/subscriptions.md). Additionally, for to-dos you can also specify people to be [notified on completion and/or assignment](https://github.com/basecamp/bc3-api/blob/master/sections/todos.md#create-a-to-do). 

When creating a message, you can specify a `subscriptions` parameter with an array of people IDs, exactly like the `subscriptions` parameter in [this endpoint](https://github.com/basecamp/bc3-api/blob/master/sections/subscriptions.md#update-subscription).

**Comment by bcjarrett** [comment]
Awesome!

Team will be excited to stop getting a million emails.
