### ISSUE TITLE
paging of recordings broke sometime today.

### ISSUE THREAD

**Issue by urkle** [basecamp/bc3-api#117]
We are paging through recordings to get a "delta" of what happened since a point in time..  However sometime today, the API changed and is ALWAYS returning a 'next' page URL (specifically when we send status=archived ).  This our code has been going into lovely infinite loops.  

We have locally modified our code so that it doesn't "fully trust" the next page URL, but instead also checks that there was any records returned. 

Considering we have 170 customers using Basecamp 3, this REALLY put a damper on things today and causing the need for a lot of damage control due to this unexpected change in the BX3 API.

**Comment by dhh** [comment]
We are now using geared pagination, so the records returned per page starts out lower and then increments. It goes 15 on page 1, then 30, 50, 100. But that shouldn't have changed the fact that if there's a Link header, there should also be another page with records. Can you send me an example of a URL that gives you the Link header even though there's no more records on that page? david@basecamp.com. Thanks and sorry for the trouble!

**Comment by dhh** [comment]
We've replicated the problem when using the status=archived param. Will get a fix deployed for this tomorrow. Thanks for reporting and sorry again for the trouble. Relying on the Link header to know when you're done paging is indeed the way we intend it to work.

**Comment by dhh** [comment]
[This has now been fixed](https://github.com/basecamp/geared_pagination/commit/6891d7064993322b183460cfcc8d804b1ea77e76).
