### ISSUE TITLE
Getting all people using /people.json broke recently

### ISSUE THREAD

**Issue by SeBsZ** [basecamp/bc3-api#118]
According to this page https://github.com/basecamp/bc3-api/blob/master/sections/people.md#people , making an API call to just /people.json should return "all people visible to the current user". This worked well until at some point the behavior changed to no longer return the full set of users.

To demonstrate, calling /people.json returns 22 users, and several important users are missing. When I call /projects/3005288/people.json , 30 users are returned and this includes everyone.

Limiting this call to a project should never return more users than asking for all users, right?

**Comment by archon810** [comment]
This seems serious @georgeclaghorn.

**Comment by dhh** [comment]
@SeBsZ I can't seem to replicate this. Can you send me the exact API calls you're executing to david@basecamp.com? This could be related to our new geared pagination scheme, but if you're getting 22 users on /people.json and 30 on a project, then that's odd. Anyway, I'll investigate when I have the data.

**Comment by jbaiza** [comment]
@dhh we also are facing this error. I sent you API calls and responses to e-mail.

**Comment by SeBsZ** [comment]
@dhh I think this is related to pagination. I made a counting mistake, there were not 22 users returned, I'm always seeing 15, which seems to be the first page limit according to https://github.com/basecamp/bc3-api#pagination

It would have been nice if we were somehow informed about this breaking change in the API.

I'll have to modify my code to grab the next page as well, as it doesn't seem I can grab say 100 in one go anymore.

**Comment by dhh** [comment]
Yes, 15 is the number of entries you'll see on most pages right now. This number is subject to change, though. (The number before was 50, btw, not 100).

As detailed in the pagination section, the only reliable way to know whether there are more pages is through the Link and X-Total-Count headers. You're explicitly instructed not to construct your own pagination links or other custom approaches to traversing the recordsets.

We may well change the pagination ratios in the future as well. But if you follow the approach of looking for the Link header to determine whether they're additional pages in your record set, you'll always be robust against such changes.

**Comment by archon810** [comment]
@dhh Do you have a place where you publish API changes like these, and more importantly, intents to make changes ahead of time, giving us some time to prepare, so they don't leave us wondering next time?

**Comment by dhh** [comment]
Good idea. I'll setup an API announcements mailing list for people who'd like a heads up when things evolve 👍

**Comment by pskrz** [comment]
@dhh This change broke a piece of the Basecamp 3 integration we have at my organization. We add and remove users through the api and I used this endpoint to get the user's basecamp ids. The documentation isn't updated from what I can tell, and there was no announcement. Does the mailing list announcing API changes exist yet? And do you plan to version your API?

**Comment by dhh** [comment]
We don't have a mailing list setup yet, but it's on the docket. We'll
definitely use that to announce similar changes.

There are no plans to version the API at this time, though. Tweaking the
number of results we provide per page to queries in the API is something we
may well continue to do as scaling needs dictate or usage patterns change.
You can, however, guard against such changes entirely by relying on the API
conventions we've supplied around pagination, watching the headers, and
using them exclusively to determine whether there are more records in a set
or not.

**Comment by pskrz** [comment]
@dhh Thank you for the quick response, noted.
