### ISSUE TITLE
Web hooks for forwards

### ISSUE THREAD

**Issue by edgerunner** [basecamp/bc3-api#119]
I would like to set up a web hook that would trigger on a new forward, but it seems that it is not possible. Or maybe I couldn't find out how. Please help.

**Comment by georgeclaghorn** [comment]
@edgerunner, we support subscribing to forward events with webhooks. Check the box labeled “Forwarded emails” when setting up a webhook:

![screen shot 2018-02-27 at 10 12 41 pm](https://user-images.githubusercontent.com/94129/36768138-8f36e7b4-1c0b-11e8-98ce-cd7b3fc66740.png)

If you’re creating webhooks via the API, use the `"Inbox::Forward"` type:

![screen shot 2018-02-27 at 10 13 47 pm](https://user-images.githubusercontent.com/94129/36768154-a4950208-1c0b-11e8-8571-d05c0c2772a8.png)
