### ISSUE TITLE
/circles/people.json is broken

### ISSUE THREAD

**Issue by jtsang1** [basecamp/bc3-api#120]
https://github.com/basecamp/bc3-api/blob/master/sections/people.md#get-pingable-people

This endpoint is returning 204 - No Content

`https://3.basecamp.com/<account_id>/circles/people.json` works properly (in browser)
`https://3.basecampapi.com/<account_id>/circles/people.json` returns 204 (via curl)

**Comment by javan** [comment]
Thanks! Should be fixed now.
