### ISSUE TITLE
Delete webhook for revoked OAuth credentials

### ISSUE THREAD

**Issue by raulpopadineti** [basecamp/bc3-api#122]
What's the best way to unsubscribe from a webhook if the client revokes the OAuth credentials? Do you automatically delete that webhook or do we need to contact the user or you guys to get rid of it?

I know Trello handles this in a slick way:

> There are three ways to delete webhooks.
> 
> 1. Using the DELETE route on webhooks
> DELETE https://api.trello.com/1/webhooks/[WEBHOOK_ID]?key=[APPLICATION_KEY]&token=[USER_TOKEN]
> 2. If the webhook request from Trello, when POSTing to the callbackURL, receives an HTTP 410 Gone response, the webhook will be deleted.
> 3. If the token that the webhook is bound to is revoked or expires, then the webhook will be deleted

Something like this would be awesome!

**Comment by raulpopadineti** [comment]
At least an acknowledged or a thumbs up would be nice to see that at least someone from Basecamp saw this.

**Comment by raulpopadineti** [comment]
Looks like these API enhancements have a very low priority inside the company. /cc @jeremy @javan

**Comment by jeremy** [comment]
Appreciate your patience, @raulpopadineti. We do indeed have our eyes (and minds) on new product dev and the API gets bursts of catch-up attention on a longer cycle.

If webhook delivery fails 10 times, we deactivate it. (And they can be [deleted via the API](https://github.com/basecamp/bc3-api/blob/master/sections/webhooks.md#destroy-a-webhook).)

**Comment by raulpopadineti** [comment]
@jeremy thanks for your reply.

**Comment by raulpopadineti** [comment]
Hello @jeremy ! 👋 

Hope you're all well during these tough times.

Since [Hey launch is being postponed](https://m.signalvnoise.com/why-hey-had-to-wait/) and things are a bit more relaxed in terms of BC 4 roadmap, is it possible to revisit the three options of deleting webhooks implemented by Trello and add no. 2 for BC 3 API as well?

> 2. If the webhook request from Trello, when POSTing to the callbackURL, receives an HTTP 410 Gone response, the webhook will be deleted.

I know you have the auto-disable policy in place, but having this second option is such a fast and easy way to deal with keeping the webhooks slate clean on both ends, the integrators and Basecamp.

Let me know if it's something you'll reconsider in the near future.

Kindly,
Raul
