### ISSUE TITLE
The remote server returned an error: (404) Not Found

### ISSUE THREAD

**Issue by dsliter** [basecamp/bc3-api#123]
I'm currently receiving a 404 error when I try to get a project schedule. It was working fine yesterday, and today it stopped working. I haven't made any code changes is several weeks, So I'm wondering if something changed on BC3's end.

I'm setting web headers Authorization to Bearer "My Authorization Token" and the User agent as "Lepton (development@highimpact.com)". Security Protocol = Tls12, and I have tested the link that I'm using by logging into basecamp using the development@highimpact.com and pasting the link into a browser which returns a json file.

Any help would be great.

Thanks
Dieter

**Comment by georgeclaghorn** [comment]
Could you please send an email to support@basecamp.com with the value of the `X-Request-Id` response header for a recent request that resulted in a 404 error? Thanks!
