### ISSUE TITLE
Upload file as comment in Basecamp 3

### ISSUE THREAD

**Issue by swapnilnagare** [basecamp/bc3-api#126]
In Basecamp 3, How do I upload a file whether it is text file or image file as a comment or in comment using the bc3-api??
Please help me ASAP....

**Comment by Rosa** [comment]
Hey @swapnilnagare, you can find how to do so in our documentation 😄 First, you need to create [an attachment](https://github.com/basecamp/bc3-api/blob/master/sections/attachments.md#create-an-attachment), posting the file you wish to upload to the attachment creation endpoint. This will return an `attachable_sgid` for the attachment.

Then, when [creating a comment](https://github.com/basecamp/bc3-api/blob/master/sections/comments.md#create-a-comment) you can provide the content as **rich text**, which among other features, can include  inline attachments. [Here](https://github.com/basecamp/bc3-api/blob/e76663bf524c31a0037171622b2a387eec916923/sections/rich_text.md#inserting-an-image-or-file-attachment) you can find the details of how to include an inline attachment using the `attachable_sgid` you got in the previous step.

I hope this helps!

**Comment by swapnilnagare** [comment]
Thnaks @Rosa for giving the reply. I got how to upload the attachment but didn't get how to add it in comments. I will follow your solution.... Thanks once again...

**Comment by Rosa** [comment]
It's a bit hidden! Let me know if you need any help with that @swapnilnagare 😃
