### ISSUE TITLE
empty array returned from Update People response

### ISSUE THREAD

**Issue by ecommerce-technician** [basecamp/bc3-api#127]
Hello,

My goal is authorize an external user to be assigned todos in an already-existing basecamp project. Auth seems to work fine, and I can hit other endpoints like get projects just fine.

When trying to use the "Update who can access a Basecamp" featured here 
 - https://github.com/basecamp/bc3-api/blob/master/sections/people.md#update-who-can-access-a-basecamp

### I'm issuing the following curl request per the instructions here:
```
curl -s -H "Authorization: Bearer XXX--MY TOKEN--XXX" -H "Content-Type: application/json" \
  -d '{"grant":[EXTERNAL ACCOUNT ID]}' -X PUT \
  https://3.basecampapi.com/MY ACCOUNT ID/projects/MY PROJECT ID/people/users.json
```

### And this is the response I'm getting basecamp
```{"granted":[],"revoked":[]}```

As I'm not getting an error code, and the request seems fine, I'm kinda stuck. Wondering if anyone has any guidance?

**Comment by georgeclaghorn** [comment]
Can you explain what you mean by “external user”? Is the person you’re trying to add not part of the account that contains the project?

**Comment by ecommerce-technician** [comment]
@georgeclaghorn correct, I have one basecamp + user that is the owner of the api tied to 37 signals. On our external site, a user clicks a link which authorizes the application and performs a token exchange. My goal is to then, after token exchange, add our user as an authorized user to the clients basecamp or project

**Comment by ecommerce-technician** [comment]
@georgeclaghorn any idea? I still havent been able to resolve

**Comment by georgeclaghorn** [comment]
Sorry for the delay! You can’t add a person from a different account to a Basecamp. Invite them to the account using the `create` parameter.

**Comment by ecommerce-technician** [comment]
Perfect, thanks!

**Comment by georgeclaghorn** [comment]
Correct. I was referring to the `create` parameter of the [Update who can access a Basecamp](https://github.com/basecamp/bc3-api/blob/master/sections/people.md#update-who-can-access-a-basecamp) endpoint.

**Comment by ecommerce-technician** [comment]
Last question - is this not possible through the API then?
https://help.basecamp.com/basecamp/questions/425-how-do-i-add-people-to-my-account

To add new users to your stand-alone Basecamp account, go to the 'All People' page. Click the “Add a new person” button to invite people into your account. If you're a Suite user, it works a bit differently. Use these instructions to add someone to your main company.

**Comment by georgeclaghorn** [comment]
Those instructions are for Basecamp Classic, but yes, it’s not currently possible to add someone to a Basecamp account via the API without adding them to a Basecamp.

**Comment by ecommerce-technician** [comment]
@georgeclaghorn Hey in the people.md, the docs state "allows granting new and existing people access to a Basecamp, and revoking access from existing people." 

Shouldn't that cover adding someone to a basecamp project, or team via the API? Apologies, I'm just on a deadline with a client and this isn't really making sense, why would you grant access to a basecamp if the user is already on the basecamp?
```
{
  "grant": [
    1007299151
  ],
  "revoke": [
    1007299150
  ],
  "create": [
    {
      "name": "Victor Copper",
      "email_address": "victor@hanchodesign.com",
      "title": "Prankster",
      "company_name": "Hancho Design"
    }
  ]
}
```

**Comment by georgeclaghorn** [comment]
Sorry for the confusion. By “existing people,” the docs mean people who are already on the account but don’t have access to the project/team. Does that answer your question?

**Comment by ecommerce-technician** [comment]
Yes it does, is there currently an API method for inviting a user to a basecamp then, similar to this "https://basecamp.com/help/3/guides/people/users-and-orgs"

the goal is for a user who has authenticated via oath 2 to then invite a user to their basecamp via the api
