### ISSUE TITLE
Clarification about rate limited request accounting

### ISSUE THREAD

**Issue by yellow5** [basecamp/bc3-api#130]
I see in the rate limiting documentation that requests are scoped by account per IP address [1]. 

> You can perform up to 50 requests per 10-second period from the same IP address for the same account.

Does the access token sent with the request have any effect on this?

Ultimately I am curious whether or not this scenario is true:

```
Given that user 1 has access token ABC for account 123
And that user 2 has access token DEF for account 123
When I perform an API request for user 1
And I perform an API request for user 2
Then the rate limited request counter for account 123 drops by 2
```

[1] https://github.com/basecamp/bc3-api#rate-limiting

**Comment by georgeclaghorn** [comment]
Your example is correct if you send both requests from the same IP address.

**Comment by yellow5** [comment]
Okay, thanks for the help @georgeclaghorn 👍
