### ISSUE TITLE
upload_active webhook does not specify notified_recipient_ids

### ISSUE THREAD

**Issue by bwbuchanan** [basecamp/bc3-api#131]
The upload_active webhook does not have a notified_recipient_ids key in the details hash.

This information (who was notified about the upload) is needed by an automation that sends notifications if the file uploader forgot to select the option to notify the project members when they uploaded the file. But if I can't tell who Basecamp notified about the upload, I can't decide whether to send a replacement notification or not.

Also, as far as I can tell, there is no way to use the API to query an upload (or any other resource) and determine who is subscribed to it.

**Comment by rosa** [comment]
> Also, as far as I can tell, there is no way to use the API to query an upload (or any other resource) and determine who is subscribed to it.

@bwbuchanan now there is. Check out the [documentation on subscriptions](https://github.com/basecamp/bc3-api/blob/master/sections/subscriptions.md#subscriptions).
