### ISSUE TITLE
get client list

### ISSUE THREAD

**Issue by kamekun** [basecamp/bc3-api#132]
i dont see on the api to get the client list, i can set the client name on the web but i want to retrieve a client list from the api. so how do i get the client list on the BC3 api....

here is an example from what i want to get:
[Link to the capture](https://gyazo.com/6d1b67e12361d005349c4ea7a3f4e6a8)

**Comment by rosa** [comment]
@kamekun we recently added client side information to the project responses as indicated in https://github.com/basecamp/bc3-api/issues/165#issuecomment-370851534. That provides exactly what you want to get in that screenshot.
