### ISSUE TITLE
Oauth using a Google account is not working anymore

### ISSUE THREAD

**Issue by bwgabel** [basecamp/bc3-api#133]
My users can no longer authenticate via Oauth2 using their google accounts. When they select "Use my Google account" a popup prompts for their google credentials (if they are not already logged in). Once they authenticate with Google and select their account from the list, the popup disappears and nothing happens. The continue to see that screen asking them to sign in using Google or their basecamp credentials.

**Comment by javan** [comment]
Are you able to reproduce this issue? If so, what browser and OS? I just tested on Chrome / macOS and it worked fine.
