### ISSUE TITLE
Could not get todoset

### ISSUE THREAD

**Issue by sivaramsi** [basecamp/bc3-api#135]
I have tried to get the todosets with the below URL.
https://3.basecampapi.com/{my_account_id}/buckets/{my_project_id}/todosets/2.json
But it throws 404. 
By the way, what is that 2.json is that static one or any dynamic id.Nothing in the docs about it

**Comment by NicoGettingBetter** [comment]
Open https://3.basecamp.com/{my_account_id}/projects/{my_project_id}
Go to To-dos.
https://3.basecamp.com/{my_account_id}/buckets/{my_project_id}/todosets/{my_todoset_id}

**Comment by georgeclaghorn** [comment]
You can obtain the URL for a project’s to-do set via the [Get a project](https://github.com/basecamp/bc3-api/blob/master/sections/projects.md#get-a-project) endpoint.
