### ISSUE TITLE
[Feature Request] People show the time since they did something

### ISSUE THREAD

**Issue by NoahGleason** [basecamp/bc3-api#140]
It would nice to be able to see the last time a person did something (e.g. post, applaud, ping, campfire talk, etc.), to see who's actually using Basecamp and who isn't, and automatically cleanup accounts that have been inactive long enough that it's likely the person has left the organization.

**Comment by rosa** [comment]
Hey @NoahGleason, sorry for the super late reply 😓 We aren't planning to add this to the API, I'm afraid. [The reports feature](https://3.basecamp-help.com/article/93-reports) in the app might be helpful for you, though! In particular the Activity one, which [you can filter by person](https://3.basecamp-help.com/article/93-reports#someones-activity).
