### ISSUE TITLE
Renamed Companies not Reflected in API

### ISSUE THREAD

**Issue by rileypaulsen** [basecamp/bc3-api#141]
We recently renamed a company/organization. For new employees who have been added after the change, the company name is reflected accurately in the API, but for users that existed before the change, the old name still shows up.

In both cases, the company ID property is the same in the data, but the name is different.

**Comment by rosa** [comment]
@rileypaulsen, you are right! This was a caching bug that we just fixed. From now on company name changes should be reflected on the responses.
