### ISSUE TITLE
TODO edits no longer trigger webhook push

### ISSUE THREAD

**Issue by archon810** [basecamp/bc3-api#142]
Hi,

As of today, editing TODOs no longer creates a webhook push whereas before updates, such as updating a title or tweaking a TODO's content, would ping our Slack (via our custom BC3 -> Slack webhook processor script).

Did something change here, @georgeclaghorn?

**Comment by archon810** [comment]
cc @SeBsZ

**Comment by packagethief** [comment]
Hey @archon810. No changes that we're aware of, and I see todo edits being relayed to webhooks in my personal account. If you edit your webhook in Basecamp you should see the last five deliveries logged (scroll down to the bottom of the screen). That might provide some clues.

If everything looks ok from your end, feel free to shoot us a message at https://basecamp.com/support with your account details and we can take a closer look.

**Comment by archon810** [comment]
@packagethief I looked at this again, and right now description edits are actually hitting the webhook, but title edits don't.

Here everything that says "updated this to-do" were title edits, and none of them hit the webhooks.

![image](https://user-images.githubusercontent.com/469543/31786441-593fa8f4-b4bd-11e7-81f8-b2cce5aef199.png)

**Comment by packagethief** [comment]
Thanks @archon810. Do you see webhook delivery attempts for those to-do updates when you edit the webhook itself? We list the last five events there.

Send us a message at https://basecamp.com/support and we can take a closer look at your account to see what's up!

**Comment by archon810** [comment]
@packagethief Just found the webhook page.

![image](https://user-images.githubusercontent.com/469543/31844587-82437c34-b5ae-11e7-947b-996f8074e755.png)

TODO created (no description) - todo_created fires
**TODO added description - no webhook fires**
TODO tweaked title - todo_content_changed
TODO tweaked description - todo_description_changed
TODO tweaked title and description - todo_content_changed

There are 2 issues here. One is no webhook fires when a description is added to a TODO, at all. I think this is an oversight on BC's part.

The 2nd issue is we somehow don't react to todo_content_changed, only todo_description_changed. I can't be sure anymore if something changed here, but perhaps not and it was always buggy on our end? We'll start processing todo_content_changed too, especially considering it fires when title and description are tweaked at the same time.

For some reason we also watch for todo_title_updated, but I don't even see that ever get called. Maybe it's deprecated (or never existed?)?

**Comment by archon810** [comment]
Btw, is there a list of webhook kinds? Searching Google or this project for todo_content_changed produces 0 results.

**Comment by SeBsZ** [comment]
I looked into this, and confirm there is an issue with a webhook not firing (it doesn't show up on the https://3.basecamp.com/3093264/buckets/3054437/webhooks/14560/edit page)

The original post here mentioned updating a title or tweaking content - those do fire webhooks. What doesn't fire a webhook is adding a description to a todo when there was none.

Steps to reproduce:

1. Create a new todo. todo_created fires.
2. Open the todo and click Edit
3. Add some Notes. **No webhook fires.**
4. Edit todo again, remove or modify the notes, todo_description_changed fires.
5. Anytime you add notes when there were none, no webhook fires.

**Comment by archon810** [comment]
Also curious about `todo_adopted`.

**Comment by archon810** [comment]
@packagethief Any updates?

**Comment by packagethief** [comment]
Hey @archon810.

> no webhook fires when a description is added to a TODO, at all. I think this is an oversight on BC's part.

That sounds likely. I'll investigate.

> Btw, is there a list of webhook kinds? Searching Google or this project for todo_content_changed produces 0 results.

It doesn't look like it. The [webhooks documentation](https://github.com/basecamp/bc3-api/blob/master/sections/webhooks.md#webhooks) lists some but a quick glance shows it's incomplete. I'll get it updated.

**Comment by archon810** [comment]
Hooray! Could you re-open this ticket please @packagethief or did you file new ones?

**Comment by packagethief** [comment]
Hey @archon810. You should now receive webhook events when a description is added to a to-do (`todo_description_changed`). You'll also get them for some other spots we were missing:

- Adding a description to a to-do list (`todolist_description_changed`)
- Adding a start date or due date to a to-do (`todo_{starts,due}_on_changed`)

I'll work on updating the documentation next.

**Comment by kirtan227** [comment]
Is there any way that we can update the issues from our website and it reflect on my  github account

**Comment by SeBsZ** [comment]
For completeness, am I right that `todo_{starts,due}_on_changed` no longer exists, and has been replaced by `todo_scheduled`, `todo_unscheduled`, and `todo_rescheduled`?

**Comment by rosa** [comment]
Ah, @SeBsZ, you're correct. `scheduled`, `unscheduled` and `rescheduled` are the events that are triggered for any scheduled recordings, such as `Todo` or `Schedule::Entry`.

**Comment by SeBsZ** [comment]
Still no changelog that we can subscribe to to inform us of these API changes?
