### ISSUE TITLE
Trial expired / Inactive account

### ISSUE THREAD

**Issue by eripoche** [basecamp/bc3-api#148]
Is there a way to know if the user account trial is expired through the Basecamp 3 API?

**Comment by jeremy** [comment]
Yep, if you get a 404 Not Found response with a `Reason: Account Inactive` header. Updated docs in #162.

**Comment by rvanbaalen** [comment]
Related to this, is there a way to know if a Basecamp user is currently on the Basecamp trial?

**Comment by rosa** [comment]
Hi @rvanbaalen! No, I'm afraid we don't expose this through the BC3 API. Sorry about that!
