### ISSUE TITLE
Get position of a To-do

### ISSUE THREAD

**Issue by trackedsupport** [basecamp/bc3-api#151]
Right now you can reposition a to-do but you can't get the current position of a to-do. It would be nice to see it returned whenever you retrieve a to-do. Thanks!

**Comment by rosa** [comment]
@trackedsupport we just added this! Not only for to-dos, but for all positioned recordings (for example, to-do lists have positions too). Note that archived, trashed or completed (to-dos, in that case) aren't positioned.
