### ISSUE TITLE
we will ever get an solid answer to this?

### ISSUE THREAD

**Issue by kamekun** [basecamp/bc3-api#152]
we want to know a way that an admin user from BC3 can see all the projects and teams. 
vía api  we need to know the projects / teams / to-dos  status with an special  user access.

Right now to do this, when a team/project is created we need to asign a user in order to that user be used on our dashboard. can we implement this that was already implement on BC2?

Regards.-

**Comment by georgeclaghorn** [comment]
> we want to know a way that an admin user from BC3 can see all the projects and teams.

We don’t have plans to add this at the moment. Sorry!
