### ISSUE TITLE
API/CURL dont return all assigned teams / projects

### ISSUE THREAD

**Issue by kamekun** [basecamp/bc3-api#155]
~~hello, currently the api dont return the correct value, im in 5 team, but the api only return 3;   i get the team with this: https://3.basecamp.com/xxxx/projects.json~~ 

~~The same with the projects, the api (curl and web) return less projects that i have assigned; i wait a few days to see if the api need update somehow but the problem still occurs..~~

PD: sorry was my mistake...  i need to paginate my call to the  api becasuse only return 15 results each page, is there a way to only filter the purpose? to topic or team?

Regards.-

**Comment by jeremy** [comment]
Hey @kamekun, client-side filtering is the way to go. 👍
