### ISSUE TITLE
Folder Creation webhook

### ISSUE THREAD

**Issue by jenslogic** [basecamp/bc3-api#160]
Hi, 

I would appreciate if Basecamp 3 could have an API command for folder creation.
Use case is pretty simple:
If a user a creates a folder in Basecamp 3 (project/doc&files) the same folder is created within a dropbox.
By that I can duplicate all files and the folder structure of a project in a dropbox.

cheers, jens

**Comment by jeremy** [comment]
Cool idea @jenslogic. You'll be able to implement when [webhooks](https://github.com/basecamp/bc3-api/blob/master/sections/webhooks.md#webhooks) support folders.

**Comment by georgeclaghorn** [comment]
We just added folder support to webhooks. Tick the box next to “Folder” when setting up a webhook:

<img width="718" alt="screen shot 2018-02-28 at 9 51 12 am" src="https://user-images.githubusercontent.com/94129/36793973-f4df5716-1c6c-11e8-8050-c20ee1fd3e0a.png">

**Comment by jenslogic** [comment]
Perfect. It works!

mit besten Grüßen
best regards

Jens Gnad
___________________________________________________________
LOGIC media solutions GmbH

Von: George Claghorn [mailto:notifications@github.com]
Gesendet: Mittwoch, 28. Februar 2018 15:52
An: basecamp/bc3-api <bc3-api@noreply.github.com>
Cc: Jens Gnad <jgnad@logicmedia.de>; Mention <mention@noreply.github.com>
Betreff: Re: [basecamp/bc3-api] Folder Creation webhook (#160)


We just added folder support to webhooks. Tick the box next to “Folder” when setting up a webhook:

[screen shot 2018-02-28 at 9 51 12 am]<https://user-images.githubusercontent.com/94129/36793973-f4df5716-1c6c-11e8-8050-c20ee1fd3e0a.png>
