### ISSUE TITLE
Get to-dos that are assigned to me

### ISSUE THREAD

**Issue by ilyaivjev** [basecamp/bc3-api#161]
How can i get only to-dos that are assigned to me?

**Comment by jeremy** [comment]
Hey @ilyaivjev, this isn't covered by our API as of Feb 2018.

**Comment by jeremy** [comment]
#92

**Comment by foxontherock** [comment]
So, you consider it OK to get a complete backup of all our data, to find tasks assigned to 1 person?
We would like to get that feature too.

**Comment by gasbo** [comment]
+1
