### ISSUE TITLE
Return Client name in projects response

### ISSUE THREAD

**Issue by trackedsupport** [basecamp/bc3-api#165]
Right now there are different responses between https://3.basecamp.com and https://3.basecampapi.com.

Example: /3941198/projects/6599393.json

The former returns the following which the latter does not. Specifically, I would like to get the client name via basecamp API. 

	"people_count": 1,
	"people_sample": [
		{
			"id": 17245235,
			"avatar_url": "https://3.basecamp-static.com/3941198/people/BAhpBDMkBwE=--48d0a53ad1afbfe2e794d1d1b11390b56f3ca07b/avatar-64-x4?v=1"
		}
	],
	"archived": false,
	"trashed": false,
	"playgrounded": false,
	"edit_tools_app_url": "https://3.basecamp.com/3941198/buckets/6599393/dock/edit",
	"active_status_app_url": "https://3.basecamp.com/3941198/projects/6599393/status/active",
	"trashed_status_app_url": "https://3.basecamp.com/3941198/projects/6599393/status/trashed",
	"client_name": "apple",
	"clientside_url": "https://3.basecamp.com/3941198/buckets/6599393/client/board",
	"avatars_sample": [
		"https://3.basecamp-static.com/3941198/people/BAhpBDMkBwE=--48d0a53ad1afbfe2e794d1d1b11390b56f3ca07b/avatar-64-x4?v=1"

**Comment by rosa** [comment]
@trackedsupport, we'll look into adding client information to the `/project/:project_id.json` response 👍

**Comment by rosa** [comment]
@trackedsupport now the `GET /projects.json` and `GET /projects/:projec_id.json` responses include client information. You can see an example [here](https://github.com/basecamp/bc3-api/blob/master/sections/projects.md#get-projects), but basically the following is included:
```json
    "client_company": {
      "id": 1033447819,
      "name": "Leto Brand"
    },
    "clientside": {
      "url": "https://3.basecampapi.com/195539477/buckets/2085958500/client/board.json",
      "app_url": "https://3.basecamp.com/195539477/buckets/2085958500/client/board"
    }
```

I hope this helps!
