### ISSUE TITLE
Feature request: endpoint to create publications

### ISSUE THREAD

**Issue by ArondeParon** [basecamp/bc3-api#171]
It is currently not possible to create publications (public links) to entities in Basecamp through the API.

If this is not intended, it would be _really_ nice to add this to a future API release so that it is possible to generate public links through the API.

**Comment by rosa** [comment]
Hey @ArondeParon! Sorry for the super late reply 😓 We aren't planning to support creating public sharing links from the API, I'm afraid. You'll have to continue using the app for that.
