### ISSUE TITLE
Webhook default types: all or none? 

### ISSUE THREAD

**Issue by akf** [basecamp/bc3-api#172]
https://github.com/basecamp/bc3-api/blob/master/sections/webhooks.md states: 

"A webhook can be subscribed to updates from the types detailed below. The default is to subscribe to all of them:"

That doesn't seem to be the case. I tried creating a webhook specifying only the payload_url. The result seemed to be a webhook that fired on _no_ types, because I poked around in my test project creating and editing Todos and making other updates and never saw traffic to my payload_url. When I did a GET on the webhook, it returned this: 

```
{
    id: 126972,
    active: true,
    created_at: '2018-03-26T23:30:44.230Z',
    updated_at: '2018-03-26T23:30:44.230Z',
    payload_url: 'https://xxxxxxxxxxxxxx/integrations/bc3/7078070',
    types: [],
    url: 'https://3.basecampapi.com/3913464/buckets/7078070/webhooks/126972.json',
    app_url: 'https://3.basecamp.com/3913464/buckets/7078070/webhooks/126972',
    recent_deliveries: []
}
```

After double-checking the payload_url and a few other things, I updated the endpoint specifying types, posting: 

```
{
    payload_url: 'https://xxxxxxxxxxxxxx/integrations/bc3/7078070',
    types: [ 'Todo', 'Schedule::Entry' ],
    active: true
}
```

And now the webhook posts to my payload_url when I complete a Todo, update a schedule entry, and so on. 

I can pretty well predict that Todo and Schedule::Entry are the types I need; I was just using the "simplest" case of creating a webhook  first.

**Comment by rosa** [comment]
@akf you are right! This might be a bug, I'll look into it and let you know, thanks for pointing it out.

**Comment by rosa** [comment]
Yes, it was a bug! We just pushed a fix for it, so the default type should be _all_ again when you create a webhook without including `types`. Thanks for catching this 😄
