### ISSUE TITLE
Todo Updates -- add "content" field

### ISSUE THREAD

**Issue by akf** [basecamp/bc3-api#175]
I'm back! So, I reworked my code to pass the fields explicitly listed in "update a todo" and #174 and I kept getting a 500 error. Adding "content" fixed it, so I think you need that in there as well (or there is a bug).

**Comment by rosa** [comment]
Ha, true! It's explicitly listed as **required** in the [creation endpoint](https://github.com/basecamp/bc3-api/blob/master/sections/todos.md#create-a-to-do), and when I copied the parameters from that endpoint over to the update endpoint I left it out accidentally. I fixed the documentation now 😃

**Comment by akf** [comment]
Thanks for the quick responses! I guess I really get tunnel vision when I look at the Update documentation.
