### ISSUE TITLE
Sub todolist not appeared in todoset and I cant find how can I get them

### ISSUE THREAD

**Issue by developh** [basecamp/bc3-api#179]
Sub todolist not appeared in todoset and I cant find how can I get them

![todolists]()

**Comment by georgeclaghorn** [comment]
Hey @developh! We call those sub-lists “groups.” Check out the documentation for [to-do list groups](https://github.com/basecamp/bc3-api/blob/master/sections/todolist_groups.md).

**Comment by developh** [comment]
Perfect! you saved my day!
