### ISSUE TITLE
SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by goldhat** [basecamp/bc3-api#180]
I'm trying to trade the code for token using curl post and the error I'm seeing is SSL certificate problem: unable to get local issuer certificate. The post data seems correct. I'm testing this on localhost, which doesn't have an SSL certificate. Is it possible to build and test without an SSL cert?

Other thought was maybe some headers need to be set in the request?

**Comment by rosa** [comment]
Hey @goldhat, sorry for the super late reply! I totally missed this 😓 Did you get that to work at the end? I'm not quite sure what you meant by localhost, but you can test the API from anywhere using `curl` and following [our guide](https://github.com/basecamp/bc3-api#making-a-request).

**Comment by rosa** [comment]
I'm closing this issue, as there doesn't seem to be a problem with the API. Feel free to [contact support](https://basecamp.com/support) if you need any more help!
