### ISSUE TITLE
All users?

### ISSUE THREAD

**Issue by GeertClaes** [basecamp/bc3-api#181]
When I call the users API to get all users using
`curl -s -H "Authorization: Bearer $ACCESS_TOKEN" https://3.basecampapi.com/$ACCOUNT_ID/people.json | json_pp`

I seem to see myself but the rest are all either "dummy" users ("personable_type" : "DummyUser") and one "personable_type" : "Integration"?

**Comment by rosa** [comment]
It sounds like you are just grabbing the first page of results, without continuing fetching pages of users. Take a look at our [documentation about pagination](https://github.com/basecamp/bc3-api#pagination) and see if that solves your problem.

**Comment by GeertClaes** [comment]
I have not checked about pagination yet, but even if its the first page, why are there these "dummy" users we almost certainly never added?

**Comment by rosa** [comment]
@GeertClaes these dummy users belong to the sample team and project, a sort of playground added to an account when it's created, just to allow users to explore and play around with Basecamp. There is a sample Customer Support team, and a project for making a podcast. You can remove these from your account if you want.

**Comment by GeertClaes** [comment]
That sample project was deleted, so should those members still show up?

**Comment by rosa** [comment]
@GeertClaes yes, they aren't removed when the sample projects are. I realise I implied they would go away when you removed the sample projects in my reply, sorry about that! 

These dummy users are only visible to account admins, though. For any other regular user in the account, the `GET /people.js` endpoint only returns users that are visible for them, which translates to users that share any projects. Dummy users shouldn't be returned there in that case.

**Comment by repentant** [comment]
Sorry to bring this back in but I'm struggling with listing all users. Is there a way I can filter removed users? I simply want to list all active users of the account.

**Comment by rosa** [comment]
@repentant, we don't have a way to filter out any kind of users in the [`GET /people.json` endpoint](https://github.com/basecamp/bc3-api/blob/master/sections/people.md#get-all-people). However, the response from that endpoint depends on the authenticated users. For admins, that will return all users in the account (including deleted users, integrations, dummy users, etc). For regular users, that will include only users sharing projects with the authenticated user. That should exclude any removed users that don't have access to any of the projects the authenticated user is in. 

If you are still struggling with listing all users in the account, I'd advise taking a look at [how pagination works](https://github.com/basecamp/bc3-api#pagination). It might be a pagination issue.
