### ISSUE TITLE
/projects.json?status=active 400 Bad Request

### ISSUE THREAD

**Issue by Sunhat** [basecamp/bc3-api#183]
Hi,

Client error: `GET https://3.basecampapi.com/[REMOVED_FOR_GITHUB]/projects.json?status=active` resulted in a `400 Bad Request` response  

Requesting 
```
/projects.json?status=trashed
/projects.json?status=archived
```
both work, and in order to request ?status=active, you have to remove status from the request

**Comment by rosa** [comment]
@Sunhat yes, `status` accepts only `trashed` and `archived` as values, [as stated in the documentation for this endpoint](https://github.com/basecamp/bc3-api/blob/master/sections/projects.md#get-projects). Any other value provided in `status` is considered a `Bad Request`.
