### ISSUE TITLE
Todo list not returning any todos

### ISSUE THREAD

**Issue by cy-josh** [basecamp/bc3-api#186]
Hi there, I'm attempting to retrieve todos from a list where all items have been completed, but no matter what query I try, it always returns an empty object.

1. The project is active
2. The todo list is **not** archived or trashed
3. Out of 30 todos, only 1 is archived

I've tried the following URL by itself, as well as with **completed** set to true and/or **status** set to archived or trashed. It always returns '[]'.
https://3.basecampapi.com/3100565/buckets/5762476/todolists/795379906/todos.json

![screen_shot_2018-07-28_at_11_43_52_pm](https://user-images.githubusercontent.com/19497787/43363037-512f6c1c-92c0-11e8-98f1-69625bdb4e89.jpg)

The direct site link to the json also returns '[]' (https://3.basecamp.com/3100565/buckets/5762476/todolists/795379906/todos.json)

Any idea what's going on?

**Comment by rosa** [comment]
Hey @cy-josh! I suspect the reason you are seeing this behaviour is that your to-dos aren't really part of the to-do list you linked (`795379906`), but of a _group_ nested inside it. You can find more information about to-do groups and how to retrieve them from the API [here](https://github.com/basecamp/bc3-api/blob/master/sections/todolist_groups.md#list-to-do-list-groups). You can try replacing the ID of the `Pre-Launch Check List` to-do list from your screenshot by the ID of the `Administrative` to-do group, and see if that returns the expected to-dos.

**Comment by cy-josh** [comment]
Hi @rosa, I didn't realize that grouped todos were nested even deeper. I'll give that a try!

**Comment by rosa** [comment]
@cy-josh how did it go? Is it ok to close this one now?

**Comment by cy-josh** [comment]
@rosa I think we're good here, thanks!

**Comment by rosa** [comment]
Thank you!
