### ISSUE TITLE
Add Company to project and adding people to client side

### ISSUE THREAD

**Issue by dsliter** [basecamp/bc3-api#187]
I'm not seeing in your documentation where I can add company or someone to the client side.

1) Is there a way to add users to the client-side? I'm getting data in which I have all the client information to add and create a client but am not seeing how or if I can do that in the API.

2) I would also like to be able to assign a company to a project.

Thanks for the help,
Dieter Sliter

**Comment by dsliter** [comment]
On other thing. Is there a way to grab all the companies we have in Basecamp 3.

**Comment by rosa** [comment]
Hey @dsliter! Unfortunately our API currently doesn't support adding people to the clientside, or enabling the clientside for a project assigning a client company (if that's what you meant in your second question).

We don't have any endpoints to list all the companies that exist in a Basecamp 3 account, but you can get these from the [`GET /people.json` endpoint](https://github.com/basecamp/bc3-api/blob/master/sections/people.md#get-all-people). Each user visible to the authenticated user returned in the response will include their company information, so you can get all the companies that have users in that way.

**Comment by dsliter** [comment]
@rosa,

Thanks you for the response. Right now I do use the /people.json endpoint to download all the clients and users and run checks to see if they are our internal users or a external company we are working with.
 
Are there any plans to enable creation and editing to the client side through the API or was it a design decision that this is not enabled?

The reason I ask is currently it takes our production manager 28 min to completely enter a job into basecamp3 because of the complexity of our projects on basecamp3. I'm currently trying to automate this process of creating a basecamp3 project through a email set by a Zapier web hook. I can't do this through Zapier because there are all kids of conditions that are stored on my internal database that I use to figure out who gets assigned to what parts of a project. I've been able to create and edit most of what I need to automate the process. The client side was the last piece of the puzzle.

Thanks for the help.

**Comment by rosa** [comment]
We don't have any plans right now, I'm afraid. If we were to implement something to add clients to projects, it's more likely to be something based [on the new way to work with clients](https://m.signalvnoise.com/launch-a-brand-new-way-to-work-with-clients-in-basecamp-3-6a78b1175c5d) and not with the clientside 😞 

> currently it takes our production manager 28 min to completely enter a job into basecamp3 because of the complexity of our projects on basecamp3
 
That sounds like a lot. Have you tried to [contact support](https://basecamp.com/support) describing your workflow in case there is a faster way to achieve what you need?
