### ISSUE TITLE
Sending message client side through API

### ISSUE THREAD

**Issue by dsliter** [basecamp/bc3-api#189]
Is there away through the API to send a client side message to the client? I'm trying to reduce the human error that happens with our current way of copying and pasting a message. I'm also trying to use this to link into our reporting system for our end of month reports. 

Thanks
Dieter

**Comment by rosa** [comment]
@dsliter no, we don't currently support sending client side messages via the API. I'm closing this issue in favour of #139, that covers this and also approvals.
