### ISSUE TITLE
Webhooks do not trigger for linked Dropbox / Box / One Drives files

### ISSUE THREAD

**Issue by mwbrooks** [basecamp/bc3-api#190]
Hey Basecampers,

Your API has been a breeze to use and the webhooks have been performing reliably, but I've recently came across a small issue.

## Expected Behaviour

I expect webhooks to trigger for all newly created/uploaded *Docs & Files.*

I typically use the project's *Latest Activity* tab as a barometer for what *Docs & Files* activity should be broadcasted by a webhook. Currently, all created/uploaded/linked files are displayed in the *Latest Activity* feed. The only exception are new folders.

![image](https://user-images.githubusercontent.com/21328/45342031-8994aa00-b551-11e8-806d-28586346e91b.png)

## Current Behaviour

Currently, webhooks do not trigger for linked Dropbox / Box / One Drive files.

**Overview of the supported Docs & Files features:**

Docs & Files Feature | Displayed in Latest Activity | Triggers Webhook
------------ | ------------- | -------------
Published Documents | ✅ | ✅
Uploaded Files | ✅ | ✅
Linked Google Drive files | ✅ | ✅
Linked Dropbox files | ✅ | ❌
Linked Box files | ✅ | ❌
Linked One Drive files | ✅ | ❌

## Extra Detail

I recently spoke with Sylvia from Basecamp's support team because Dropbox / Box / One Drive files were not displayed in the *Latest Activity.* With Sylvia's help, this issue was recently resolved and she recommended that I report the missing webhook support as a Github issue.

**Comment by rosa** [comment]
Hey @mwbrooks, thanks for this great report! 👏 You are right, we currently don't trigger webhooks for these events, but I don't see why we shouldn't, so we'll look into adding that 👍

**Comment by mwbrooks** [comment]
Thanks for the kind words, @rosa! 👋It's great to know that you'll look into adding support for those events soon. Right now, I'm not inconvenienced, so I totally understand if it's low-priority on your side.

**Comment by rosa** [comment]
Thank you @mwbrooks! We just added support for webhooks triggering when you link other kind of file that is not a regular document or a Google Drive document: https://github.com/basecamp/bc3-api/commit/eeaae03ae298a5dfc325bcd28370275c4831ce05

This new `CloudFile` type includes linked Dropbox, Box and OneCloud files. Having all of them grouped together made this much simpler, that's why we added support so quickly. I hope this is enough for your purposes!

**Comment by mwbrooks** [comment]
Hey @rosa! Wow, that was incredibly quick!

The `cloud_file_created` event and `CloudFile` type work for my situation. If we want to detect the specific type of service, then we can always match against the linked URL. By only inspecting a single event and type, the rest of the implementation is kept a little tighter.

In only a few minutes, I was able to add support to Dropbox / Box / OneDrive:

![image](https://user-images.githubusercontent.com/21328/45465746-5e35ca80-b6cb-11e8-8238-559836e6bd13.png)

Thanks again! 🙌 
Michael

**Comment by rosa** [comment]
Nice! 👏 I'm really happy this is enough for your purposes 🎉
