### ISSUE TITLE
Feature Request: Get Attachments

### ISSUE THREAD

**Issue by cy-josh** [basecamp/bc3-api#193]
The API allows adding attachments to a todo, but what about getting all attachments from a todo? I would ask the same of comments, can we get attachments from comments as well?

**Comment by rosa** [comment]
Hi @cy-josh! Attachments are always returned as part of the _rich text_ body/content of the recording you are retrieving from the API, in the same format in which they are attached (via `bc-attachment` tags). This applies to comments, to-dos, messages... Any kind of recording with a rich text field. You can find more details [here](https://github.com/basecamp/bc3-api/blob/master/sections/rich_text.md#inserting-an-image-or-file-attachment).

**Comment by cy-josh** [comment]
@rosa, is the rich text body only returned when retrieving a single todo? I'm not seeing that in the response when requesting a list of todos.

**Comment by rosa** [comment]
@cy-josh, it's returned when retrieving multiple to-dos as well, as part of [the `GET /buckets/1/todolists/3/todos.json` response](https://github.com/basecamp/bc3-api/blob/master/sections/todos.md#get-to-dos). The rich field for to-dos is `description`. Not sure if by requesting a list of todos you mean [requesting a to-do list](https://github.com/basecamp/bc3-api/blob/master/sections/todolists.md#get-a-to-do-list), which as you said, won't return any individual to-do.

**Comment by cy-josh** [comment]
Thanks @rosa, I do see that in the todos and comments response now. Sorry I missed that.

**Comment by rosa** [comment]
No worries @cy-josh! Glad you found it there 😄
