### ISSUE TITLE
Events from projects

### ISSUE THREAD

**Issue by gasbo** [basecamp/bc3-api#194]
There is a way to obtain events from projects (e.g. know who added a user to a project)?
It seems that events are limited to recordings.

Thanks.

**Comment by rosa** [comment]
Hey @gasbo, no, unfortunately, we don't have currently a way of obtaining events associated with a project, only with recordings. I'm sorry about that! We _might_ implement this in the future but can't tell when that'd happen (if we finally did it).

**Comment by gasbo** [comment]
Ok, just wanted to confirm it. Thanks!

**Comment by rosa** [comment]
Hi again @gasbo. At the end, we won't be adding this to the API, so I'm closing this issue, sorry about that! The closest alternative we currently support, similar to events for projects are [webhooks](https://github.com/basecamp/bc3-api/blob/master/sections/webhooks.md#webhooks). We don't have a webhook for when a user is added to a project, but we do support a number of other events. Maybe that's useful for your case.
