### ISSUE TITLE
Get latest activity

### ISSUE THREAD

**Issue by mrcasals** [basecamp/bc3-api#195]
Hi!

Is there a way to list the latest activity through the API? I'm particularly interested in getting the count of unread notifications, but I can't seem to find it in the docs.

Thanks!

**Comment by rosa** [comment]
Hey @mrcasals! No, sorry, we don't have any API endpoints that return the number of unread notifications 😞 We don't have plans to add that in the near future either, sorry about that!

**Comment by mrcasals** [comment]
Ouch, that's too bad, I wanted to integrate BetterTouchTool's custom TouchBar with Basecamp notifications to have them always easily visible.. :disappointed: 

I guess you can close his issue then @rosa! Thanks!

**Comment by rosa** [comment]
Thank you @mrcasals, and sorry again!
