### ISSUE TITLE
Request Webhooks for Campfire

### ISSUE THREAD

**Issue by iandanicomarino** [basecamp/bc3-api#196]
Is there any chance for creation of a webhook when a user gets a message via campfire?
Or do you propose any other work around for this.

My use case would be having a trigger (a new message via campfire) and relay that to another app.

**Comment by rosa** [comment]
Hi @iandanicomarino! No, we exclude chat messages (Campfire and pings) from webhook events on purpose. We offer a [chatbot API](https://github.com/basecamp/bc3-api/blob/master/sections/chatbots.md) for that. For your usecase, you could try creating an interactive chatbot, and direct to it any messages you'd like to be relayed to the other app. Then your chatbot would do the relaying.

I hope this helps!

**Comment by iandanicomarino** [comment]
That would mean though that i would have to invoke the chatbot to save a
particular line. What if i want all incoming messages to be passed?

**Comment by rosa** [comment]
> What if i want all incoming messages to be passed?

**Comment by iandanicomarino** [comment]
Are there any chances to see a feature like this down the line. A feature
like streaming perhaps which i believe was supported on campfire before it
was fully integrated into basecamp 3 (
https://github.com/basecamp/campfire-api/blob/master/sections/streaming.md)

**Comment by rosa** [comment]
We don't have it planned at the moment, I'm sorry! It's definitely not impossible we consider to support it, but I'd say chances are low right now.

**Comment by iandanicomarino** [comment]
Thanks for the info Rosa :)  👍
