### ISSUE TITLE
Get due_on on webhook

### ISSUE THREAD

**Issue by jvmasera** [basecamp/bc3-api#197]
When I get webhook with the "todo_scheduled" type, the main information I need does not come together in json, which is due_on. How do I get it?

**Comment by rosa** [comment]
Hey @jvmasera, sorry for the super late reply! I completely missed this. Maybe you have already figured it out, but the webhook payload is common for all types of recordings. It includes the `id` of the created recording, in this case a to-do, and the `id` of the bucket in which the to-do was created. You can use both to request all the to-do details including `due_on` from the [Get a to-do](https://github.com/basecamp/bc3-api/blob/master/sections/todos.md#get-a-to-do) endpoint.
