### ISSUE TITLE
Authentication issue- This Basecamp ID rekeyed its deadbolt.

### ISSUE THREAD

**Issue by upugo-dev** [basecamp/bc3-api#199]
After an account password reset for our basecamp 'master' account- the only account which we care about connecting to basecamp api, I am recieving this error as the response bopdy when I try to POST for an access token via our own app. 

'This Basecamp ID rekeyed its deadbolt.'

This is after re-registering the application which had seemingly been lost from the page https://launchpad.37signals.com/integrations/, and recieving a new client_id, client_secret, and sucessfully making the POST request for an Auth token via Postman (gaining the verification code from google chrome as per https://github.com/basecamp/bc3-api/issues/48)

I've noticed the refresh_token I recieved was the same as before I broke everything- perhaps this token has been blacklisted? If so, could I please get some support in getting a new one, or un-blacklisting it! 

Thanks

**Comment by rosa** [comment]
@upugo-dev have you gone through the authorisation flow again for the user whose password was changed? That is, the part where you redirect this user to  
```
https://launchpad.37signals.com/authorization/new?type=web_server&client_id=your-client-id&redirect_uri=your-redirect-uri
```
and the user is asked whether it's ok to give access to your app? After this, you'll get an one-time verification code that you'll be able to trade for a valid access token and complete the whole OAuth authentication flow.

**Comment by upugo-dev** [comment]
Yes I have done this, still getting the same issue. That's the code added as a query string parameter, right? About 8 chars? 

I am also getting this issue via a type=refresh request for a new token with the refresh token received from the authorization/token endpoint

**Comment by upugo-dev** [comment]
OK, did the authorization flow again for a user password reset and got a new auth token, which has worked to make a API call to api/projects.json, for example, but when using the same client credentials and the new refresh token to do a type=refresh request for a new token I am recieving:

`"error": "authorization_expired"`

**Comment by rosa** [comment]
Hmm... are you sure you are using the new refresh token you got with your new auth token instead of the previous one or the access token itself? It sounds like you are either using an old refresh token, or an invalid refresh token that we can't parse.

**Comment by upugo-dev** [comment]
I was sure I was doing this, but maybe not. Anyway, **it's now working** after another go at getting a new refresh token. Weird that the auth key was valid for API calls but not the refresh token for token requests. I'll mark this closed for now, but comment here if there are any future issues. Thanks :)
