### ISSUE TITLE
Support notification when subscribing for Email forwards

### ISSUE THREAD

**Issue by sebknzl** [basecamp/bc3-api#200]
There is a "Send new people the forwarded email with all comments right now" option when subscribing people for Email forwards.

It would be nice if the same was available through the API.

Thanks

**Comment by rosa** [comment]
Hey @sebknzl, you are right! That option is also available for other kinds of recordings, like to-dos, messages, schedule entries... anything that can have comments and people subscribed to them. We haven't got any plans right now to support this via the API, I'm afraid, so it's unlikely we'll add it.

**Comment by rosa** [comment]
As a workaround, have you thought of simply using the [Update subscription](https://github.com/basecamp/bc3-api/blob/master/sections/subscriptions.md#update-subscription) endpoint followed by [creating a comment](https://github.com/basecamp/bc3-api/blob/master/sections/comments.md#create-a-comment) in the email forward recording? That'd have a similar effect to sending the forward right away to new subscribers.

**Comment by sebknzl** [comment]
Hello @rosa, thanks for your answer.
We've though of that workaround and implemented it like that, thanks. I suppose it'll do, although the subscription-notification through the UI is much nicer.
