### ISSUE TITLE
Update to-do list so that is it visible to the client also

### ISSUE THREAD

**Issue by sewarts** [basecamp/bc3-api#202]
On the to-do list screen UI you can change the privacy to allow the client to see this too.

We need this to be available via the API please.

**Comment by rosa** [comment]
Hey @sewarts! We just documented [the way to achieve this through the API](https://github.com/basecamp/bc3-api/blob/master/sections/client_visibility.md#client-visibility). Give it a try and let us know if you run into any issues!
