### ISSUE TITLE
Schedule repetition information is not available to the API

### ISSUE THREAD

**Issue by ticky** [basecamp/bc3-api#205]
Schedules which repeat do not reflect that information in the API, except in that their “url” has an “occurrence” segment in its path. No information which could be used to compute other occurrences is available.

Notably, requesting the “url” the API returns gives a similar No-Content response to those shown in #204, with the notable difference that the URL given as a redirect in #204 doesn’t include the `.json` extension.

**Comment by rosa** [comment]
You're right, @ticky. I'll look into this together with  #204.

**Comment by rosa** [comment]
This is now fixed, we added a new `recurrence_schedule` attribute, present for recurring schedule entries. You can find [some more details in the docs](https://github.com/basecamp/bc3-api/blob/master/sections/schedule_entries.md#get-a-schedule-entry). Thanks for letting us know about this!
