### ISSUE TITLE
Empty projects list

### ISSUE THREAD

**Issue by zaverden** [basecamp/bc3-api#206]
For one of my users my application can't get bc3 projects via API.

I send `GET https://3.basecampapi.com/_ACCOUNT_ID_/projects.json` (with correct `User-Agent` and `Authorization' headers). 

Response body is `[]` (empty array) and here are response headers:
```
Server: nginx
Date: Wed, 09 Jan 2019 04:24:27 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Permitted-Cross-Domain-Policies: none
Referrer-Policy: strict-origin-when-cross-origin
Accept-CH: DPR,Width,Viewport-Width,Downlink,Save-Data
Public-Key-Pins-Report-Only: max-age=3600; includeSubdomains; pin-sha256="6X0iNAQtPIjXKEVcqZBwyMcRwq1yW60549axatu3oDE="; pin-sha256="Uu5hqMmQleSn68vgjrmAQIz2tFLJ3ra/RLK7zEgYYms="; pin-sha256="Slt48iBVTjuRQJTjbzopminRrHSGtndY0/sj0lFf9Qk="; pin-sha256="LCa0a2j/xo/5m0U8HTBBNBNCLXBkg7+g+YpeiGJm564="; report-uri="https://zapier.com/hooks/catch/3b7uh7/"
X-Robots-Tag: noindex
ETag: W/"e3e655446167c24ac69371ecff7ee153"
X-Total-Count: 0
Cache-Control: max-age=0, private, must-revalidate
X-Release: 6cd3db67777dcb997d78298b20da4870c6f9f690
X-Ratelimit: {"name":"API","period":10,"limit":50,"remaining":49,"until":"2019-01-09T04:24:30Z"}
X-Request-Id: 056f448b-0555-42fb-826b-c50ad0d7f5cb
X-Runtime: 0.039997
Strict-Transport-Security: max-age=15552000; includeSubDomains; preload
X-Queue-Time: 0.0005388259887695312
Timing-Allow-Origin: *
Vary: Accept-Encoding
```

I'm not able to reproduce it since there is a least my primary company in the list. So I believe there may be an issue with user account, or with user permissions.

Could you help me to figure out why there are no projects from API

**Comment by rosa** [comment]
@zaverden, everything looks correct with your request. The `GET /projects.json` endpoint returns all active projects visible by the authenticated user. If you are getting an empty list for them, the reason might be that this user, in particular, doesn't have access to any active projects. Also, the sample projects in the account don't count as active projects, maybe they are expecting these two? Or, if the user has access to archived projects, it's possible to retrieve them by passing an optional `status` parameter, set to `archived` or `trashed`. 

I hope this helps!

**Comment by rosa** [comment]
I'm closing this issue since it seems there is nothing wrong with the API itself. If you run into any more issues feel free to [contact support](https://basecamp.com/support) with all the details 💪

**Comment by zaverden** [comment]
@rosa, thank you for your response. I think I've found a root problem with this user.

When I request authorization (`GET https://launchpad.37signals.com/authorization.json`) with his token API returns that user has 2 bc3 accounts:
```
{
  "expires_at": "2019-01-23T02:54:15.000Z",
  "identity": {
    "id": *******,
    "email_address": "*********@************.com",
    "first_name": "******",
    "last_name": "*********"
  },
  "accounts": [
    {
      "id": *******,
      "name": "Account Name-none",
      "product": "bc3",
      "href": "https://3.basecampapi.com/*******",
      "app_href": "https://3.basecamp.com/*******",
      "hidden": false
    },
    {
      "id": *******,
      "name": "Account Name",
      "product": "bcx",
      "href": "https://basecamp.com/*******/api/v1",
      "app_href": "https://basecamp.com/*******",
      "hidden": false
    },
    {
      "id": *******,
      "name": "Account Name",
      "product": "bc3",
      "href": "https://3.basecampapi.com/*******",
      "app_href": "https://3.basecamp.com/*******",
      "hidden": false
    }
  ]
}
```

The 1st account is the empty one. The 3rd account has projects (I believe user expects to see it).

So I have several questions for this situation:
1. How can I achieve the same for my user? (I need it for testing purpose)
2. Are both accounts active? (the 1st account name has '-none' suffix)
3. What is the best practice to handle this situation? should we provide a page where user can choose account he want to use?

**Comment by rosa** [comment]
Ah, I see! 

> How can I achieve the same for my user? (I need it for testing purpose)

You can sign up for an additional trial account under your existing identity, that's totally fine!

> Are both accounts active? (the 1st account name has '-none' suffix)

I'm don't know 😕 The `-none` suffix is not added by us, it's part of the name the account owner set up. 

> What is the best practice to handle this situation? should we provide a page where user can choose account he want to use?

We don't have a recommended practice for this case but that solution sounds good to me! 👍

**Comment by zaverden** [comment]
thank you, @rosa
