### ISSUE TITLE
Endpoint to get "Boosts"

### ISSUE THREAD

**Issue by lucanos** [basecamp/bc3-api#207]
I have read through the documentation, but I cannot see anything on how to poll the API for Boosts. Preferably for a whole Company/Team/Project, and with a Timeframe, (to use to run a Scoreboard arrangement).

**Comment by rosa** [comment]
Hey @lucanos! We don't offer any endpoints to fetch boosts, that's why you couldn't find it documented. We don't plan to offer any in the future, I'm afraid, boosts will remain an app-only feature.  Sorry about that!

**Comment by lucanos** [comment]
Hi @rosa,

Thanks for the reply.

It's a bit of a shame that this isn't even on your feature wishlist, considering that the User Behaviour I have seen shows that getting Boosts is engaging and fun, but it is completely isolated - apart from someone manually collecting all the data, there is no way to identify and reward Team Members who display a positive pattern of behaviour across multiple Projects/Threads.

I'm sure that your data structure was not built in such a way as to make getting this data impossible. And whilst it may not be something which has been frequently requested by other to date, I think the gamification and engagement benefits of either exposing this data through the API, or offering your own Boost Boards is the next logical step for that feature.

As I said, I know it is not currently planned to be offered, but if it could be added to either the API or the Basecamp Wishlist, I think it would make a great platform even better.

**Comment by yyolk** [comment]
Is this closed for good? I'd like boosts for a lot of the same reasons @lucanos speaks of

- counting "votes", since I can amplify participation in several use cases if I can count boosts that are "+1" or ":+1:" or "/yes" ... etc.
- moderation
- auto-bot replies

**Comment by rosa** [comment]
Hey @yyolk, yes, I'm sorry, it's closed for good.

**Comment by lucanos** [comment]
Kind of disappointing that a company which positions itself as being innovative and customer-focused is so closed to customer feedback and suggestions...

**Comment by rosa** [comment]
So sorry, @lucanos, I understand you're disappointed. We are very small too, and need to choose carefully what to work on. We wrote a bit about this in relation to the API [here](https://github.com/basecamp/api#realistic-expectations).

**Comment by sliday** [comment]
Hi @rosa Would you reconsider opening boosts in 2020? I'm building https://karmabot.chat and would be super-interested in closer integration with Basecamp.

**Comment by rosa** [comment]
Hi @sliday! Unfortunately not, we'll continue to keep boosts in the application only in 2020 as well. I'm sorry 😞  Best of luck with karmabot.chat!
