### ISSUE TITLE
Get all to-dos for a template

### ISSUE THREAD

**Issue by trackedsupport** [basecamp/bc3-api#209]
It seems to me that you should be able to do this with recordings.

**Comment by rosa** [comment]
The `GET /projects/recordings.json` endpoint is for _projects_ only, so you can't use it for templates. However, you can get use regular [GET to-dos](https://github.com/basecamp/bc3-api/blob/master/sections/todos.md#get-to-dos) endpoint with the template as bucket. That'd work perfectly.

**Comment by trackedsupport** [comment]
Thanks but how do I do that? To get the todos I need a todo list ID. To get the todo lists for a template, I need the todo set id and there is no index for todo sets. Normally you can retrieve a project and you will get all the dock details but you don't get that for templates.

**Comment by rosa** [comment]
Ah! @trackedsupport you are right. We don't return the dock details for templates right now. Let me look into that!

**Comment by rosa** [comment]
@trackedsupport we just added the dock info to the `GET /template/:id.json` as well: https://github.com/basecamp/bc3-api/commit/5c72ca1a2700b3c852485c1431706430baa26611
You should be able to use that to get the to-do set and then the to-do lists.
