### ISSUE TITLE
Feature request: Completed and uncompleted tasks joint request

### ISSUE THREAD

**Issue by jjperezaguinaga** [basecamp/bc3-api#210]
Unless I'm mistaken reading the [Todos API specification](https://github.com/basecamp/bc3-api/blob/master/sections/todos.md), right now we would need to query the _todos_ endpoint twice in order to get the joint result of all todos that had been created within a todo list. This is a bit suboptimal, as I would need to request twice the endpoint to get all the todos that compress the real status of a todoset.

That being said, I understand the need for sometimes wanting only completed OR uncompleted task. My suggestion is to add an additional query parameter (e.g. `all`) that can be passed to get the joint response. I understand `status` provides a way to poke at _archived_ or _trashed_ todos, but I believe would be good to merge those as well through the same query parameter.

**Comment by rosa** [comment]
Hey @jjperezaguinaga, you are correct, you'd need to query that endpoint more than once if you want to get all `active`, `archived` and `trashed` to-dos. It's very similar to what happens now in the UI. We do return completed and uncompleted to-dos if you don't specify the `completed` parameter set to `true`, so in reality you only need extra queries for archived and trashed. 

We don't have any plans to implement an additional query parameter to that endpoint, so you'll need to do these extra queries to get to-dos that aren't active, but if you let me know your use-case I might suggest an alternative.

**Comment by jjperezaguinaga** [comment]
@rosa Thank you for your quick response. For some reason, I'm unable to retrieve both `completed` and `uncompleted` todos through the API, but most likely this is an issue with my Basecamp client. Thanks anyway!
