### ISSUE TITLE
Get todos not returning completed todos

### ISSUE THREAD

**Issue by t4r4d4ctyl** [basecamp/bc3-api#211]
Maybe I'm missing something but after going over the documentation repeatedly it seems like when I simply get a list of todos that they should be returning completed todos from the todolist as well. But this isn't happening.

I have a list of 35 todos, 4 of which are completed. When I get the todos.json for that list, I get two pages of results, 31 results total, none of which are completed.

**Comment by rosa** [comment]
Ah, no, my apologies @t4r4d4ctyl, I was wrong, and I realise that our documentation is not clear at all and the behaviour of this endpoint is not very intuitive, but it's working as intended. I'll fix the docs. I was confused with the behaviour when a `status` parameter is provided. If `status=archived` or `status=trashed`, the request returns all to-dos with that status, completed and pending. If the `status` parameter is _not_ provided, the endpoint returns all _active_ to-dos, which doesn't include completed to-dos. To get completed to-dos, you need to perform another request with `completed=true`. I'll make sure this is clear in the docs.

**Comment by t4r4d4ctyl** [comment]
Hi Rosa,

Thanks for responding. What you said doesn't really make sense, because if
I get a list of todos with the completed parameter, such as this:

/todos.json?completed=true

I can see that the status of the completed todos is "active". So it seems
that if the default behavior is to return all active todos, that the
completed ones should be included.

The behavior of including completed todos is desired, regardless. I'd
rather filter to exclude values than filter to specifically include them.

**Comment by rosa** [comment]
@t4r4d4ctyl yeah, I didn't explain myself properly, implying that completed to-dos aren't active, they are (as they aren't archived or trashed). I also agree that returning all to-dos by default would be desirable, and more consistent with the behaviour when `status=archived` or `status=trashed`. However, that'd be a breaking change, so we cannot change that endpoint to return all to-dos now.

**Comment by t4r4d4ctyl** [comment]
@rosa can you explain why you wouldn't consider this a bug, then?

**Comment by rosa** [comment]
@t4r4d4ctyl it was an issue with our documentation, as it wasn't clear that only active pending to-dos were being returned on `GET /todos.json` requests. This is now clear in the documentation, and this is the intended behaviour for this endpoint (arguably not the most convenient one, I'd agree with that), and thus not a bug.

**Comment by t4r4d4ctyl** [comment]
@rosa That's a pretty classic "It's not a bug, it's a feature!" ;)
