### ISSUE TITLE
Project webhook

### ISSUE THREAD

**Issue by namerci** [basecamp/bc3-api#212]
How can I keep up-to-date projects assigned to user? After Oauth call I can fetch all projects for that user, store them in my database and that's good. But if project changed status for example to `archived`, how can I know that? 

The only way that I know is to call api on every X minute(s) to fetch all projects and change status. But that mean, there will be a gap that projects are out of sync. 

Is there any other way? Are you planning to add some kind of webhooks for projects? I.e. on status change and user added / removed?

**Comment by rosa** [comment]
Hey @namerci! No, unfortunately, we don't have any plans to add webhooks for project events in the future. The only way to know if a project has been archived is via another request like you mentioned. Sorry about that!
