### ISSUE TITLE
Endpoint for email forwards replies

### ISSUE THREAD

**Issue by jjperezaguinaga** [basecamp/bc3-api#213]
When calling my `inbox_forwards` via the endpoint `https://3.basecampapi.com/$BASECAMP/buckets/$BUCKET/inbox_forwards/$INBOXEID.json`, I'm able to retrieve the information of a specific email I am interested. I can even see `replies_count` and `replies_url`. I am then suggested to retrieve the replies via the URL `https://3.basecampapi.com/$BASECAMP/buckets/$BUCKET/inbox_forwards/$INBOXEID/replies.json`, but I'm unable to see that endpoint in the [documentation](https://github.com/basecamp/bc3-api/tree/master/sections). Seems it is not a [Recording](https://github.com/basecamp/bc3-api/blob/master/sections/recordings.md) as in "Replies" isn't part of the options given by `type`. The forwards endpoint `https://github.com/basecamp/bc3-api/blob/master/sections/forwards.md#get-a-forward` doesn't describe anything about replies, and I can't see anywhere in the documentation information about it.

So, can I query my inbox forwards replies as suggested by the endpoint response, and it just not documented, or this is not really provided by the current API?

**Comment by rosa** [comment]
@jjperezaguinaga you are right! We are missing the documentation for forwards inbox replies. You can query your inbox forwards replies as suggested by the response. The undocumented endpoints work in a very similar way to the [Client replies](https://github.com/basecamp/bc3-api/blob/master/sections/client_replies.md#client-replies) endpoints. I'll add the missing documentation soon.

**Comment by jjperezaguinaga** [comment]
Thanks @rosa! Please update this thread whenever that is the case 🙏

**Comment by rosa** [comment]
Of course, so sorry for the delay, @jjperezaguinaga! Here are the two endpoints for getting inbox replies documented: [Inbox Replies](https://github.com/basecamp/bc3-api/blob/master/sections/inbox_replies.md#inbox-replies).
