### ISSUE TITLE
Error getting access token

### ISSUE THREAD

**Issue by biswajit-paul** [basecamp/bc3-api#214]
When I am trying to get access token from saved refreshed token, I am getting this error:

```
<b>Fatal error</b>:  Uncaught TypeError: Argument 1 passed to League\OAuth2\Client\Provider\AbstractProvider::prepareAccessTokenResponse() must be of the type array, string given, called in /public_html/support/vendor/league/oauth2-client/src/Provider/AbstractProvider.php on line 529 and defined in /public_html/support/vendor/league/oauth2-client/src/Provider/AbstractProvider.php:708
Stack trace:
#0 /public_html/support/vendor/league/oauth2-client/src/Provider/AbstractProvider.php(529): League\OAuth2\Client\Provider\AbstractProvider-&gt;prepareAccessTokenResponse('This Basecamp I...')
#1 /public_html/support/upload.php(15): League\OAuth2\Client\Provider\AbstractProvider-&gt;getAccessToken(Object(League\OAuth2\Client\Grant\RefreshToken), Array)
#2 {main}
  thrown in <b>/public_html/support/vendor/league/oauth2-client/src/Provider/AbstractProvider.php</b> on line <b>708</b><br />
```

My code to get access token:

```
$grant = new \League\OAuth2\Client\Grant\RefreshToken(); 

$provider = new \League\OAuth2\Client\Provider\GenericProvider([
    'clientId'                => getenv('CLIENT_ID'),
    'clientSecret'            => getenv('CLIENT_SECRET'),
    'redirectUri'             => getenv('REDIRECT_URI'),
    'urlAuthorize'            => getenv('AUTH_URL'),
    'urlAccessToken'          => getenv('TOKEN_URL'),
    'urlResourceOwnerDetails' => ''
]);

$token = $provider->getAccessToken( $grant, [
    'refresh_token' => $refreshToken,
    'type'          => 'refresh'
] );
```

Thanks for help in advanced.

**Comment by rosa** [comment]
Hey @biswajit-paul, I think it might be better to open an issue or ask for help in https://github.com/thephpleague/oauth2-client, since it looks like that error comes from the OAuth2 library you are using and not from our API. 

I hope that helps!

**Comment by biswajit-paul** [comment]
@rosa  Thanks for your quick response. I will get back to you soon after I get any response from this issue: https://github.com/thephpleague/oauth2-client/issues/775

**Comment by biswajit-paul** [comment]
@rosa I have updated libraries via composer update. Now I am getting this error: "**Invalid response received from Authorization Server. Expected JSON.**" So, I logged the response on line 537 in file vendor/league/oauth2-client/src/Provider/AbstractProvider.php. The response is: "**This Basecamp ID rekeyed its deadbolt.**" 

What should I do now?

**Comment by rosa** [comment]
Ah! That means the user for which that refresh token was issued has changed their credentials since then. You need to go through the authorization flow again, and get a new refresh token. That one should be fine now.
