### ISSUE TITLE
add is_client to update-who-can-access-a-project

### ISSUE THREAD

**Issue by sewarts** [basecamp/bc3-api#218]
Hi

Is it possible to put in a request to add is_client to the

https://github.com/basecamp/bc3-api/blob/master/sections/people.md#update-who-can-access-a-project

At the moment you can add company_name which seems a bit pointless if you then can't add them as a client as all users added this way just get added to my business.

**Comment by rosa** [comment]
Hi @sewarts! That endpoint is specific to add _team users_. Adding client users to a project requires ensuring the project has a client company associated (or building one) and clients enabled (or enabling them). Currently, we don't have plans to add support for these via the API, I'm sorry. Client users would need to continue being added directly through the UI.
