### ISSUE TITLE
Locate person and the projects they are included on using their email address

### ISSUE THREAD

**Issue by sewarts** [basecamp/bc3-api#220]
Hi

Is it possible to locate a person and the projects they are included on using their email address?

Currently we are looping through every project and then every person in each project to find a match and hitting your rate limits constantly.

Thanks

**Comment by rosa** [comment]
Hey @sewarts, no, unfortunately, that's not possible. It's not even possible through the UI since the whole set of projects a person has access to is visible only by that person in general (if the viewer is a different user, they couldn't see the projects they don't have access to).
