### ISSUE TITLE
PUT on todo failing with 422 error

### ISSUE THREAD

**Issue by stephanie-jauss** [basecamp/bc3-api#221]
Doing a PUT https://3.basecampapi.com/9999999/buckets/1/todolists/1.json with the result from GET https://3.basecampapi.com/9999999/buckets/1/todolists/1.json fails with unhelpful 422 error.

**Comment by rosa** [comment]
Hey @stephanie-jauss, does it work  fine if you pass a similar payload to [the example](https://github.com/basecamp/bc3-api/blob/master/sections/todolists.md#example-json-request-1)?The response from  `GET /buckets/1/todolists/1.json` includes many more attributes and data than those that can be updated via `PUT /buckets/1/todolists/1.json`.

**Comment by stephanie-jauss** [comment]
I tried with the example data, too - same error.

**Comment by rosa** [comment]
@stephanie-jauss could you [get in touch with our Support team](https://basecamp.com/support) providing more details about the issue (specific URL you're hitting, headers, etc)? Sounds like something is wrong with your specific implementation. They should be able to help you!
