### ISSUE TITLE
Getting people on a project API did not return enough data

### ISSUE THREAD

**Issue by namnhce** [basecamp/bc3-api#222]
**Description**

As a User, I used https://github.com/basecamp/bc3-api/blob/master/sections/people.md#get-people-on-a-project API.  When I retrieve all the people on my project, the number of people on project returned was not sufficient.

**Expected Result:**  
This endpoint has to return all people participating in this project. 

**Actual Result:**
When the quantity of member = 30, the amount of member returned is less than 30.

**Comment by namnhce** [comment]
**Description**

As a User, I used https://github.com/basecamp/bc3-api/blob/master/sections/people.md#get-people-on-a-project API.  When I retrieve all the people on my project, the number of people on project returned was not sufficient.

**Expected**  
This endpoint has to return all people participating in this project. 

**Actual Result:
When the quantity of member = 30, the amount of member returned is less than 30.

**Comment by rosa** [comment]
Hey @namnhce, I suspect this might be a pagination issue. The `GET /projects/1/people.json` endpoint is paginated, as the majority of our endpoints returning collections are. It sounds like you are only retrieving the first page of results. You can read more about pagination [in our docs](https://github.com/basecamp/bc3-api#pagination).
