### ISSUE TITLE
How do I delete/revoke an OAuth application

### ISSUE THREAD

**Issue by SeBsZ** [basecamp/bc3-api#224]
I'm trying to figure out how to delete or revoke an application for which I've created OAuth credentials in the past from this page: https://launchpad.37signals.com/integrations . I've clicked everywhere, but I do not see a delete button anywhere. Am I crazy?

**Comment by rosa** [comment]
Hey @SeBsZ! You aren't crazy. Unfortunately we don't currently expose any way to delete integrations from that page. We need to add it. [You can get in touch with our support team](https://basecamp.com/support), though, and they'll be able to delete any integrations for you.

**Comment by rosa** [comment]
@SeBsZ we just fixed this. Now you can delete any of your applications from the application's edit page. You'll see a link on the bottom like this:

<img width="546" alt="Screenshot 2019-04-24 at 18 15 42" src="https://user-images.githubusercontent.com/813033/56680936-8b6a4280-66c8-11e9-865a-6f7b80176c27.png">

And that'll take you to a page to confirm the deletion. 

Sorry for not having added this until now!

**Comment by archon810** [comment]
Wow that was fast!

**Comment by SeBsZ** [comment]
Wow, that is awesome. Thanks!
