### ISSUE TITLE
feature request: grant "teams" access to projects via the API, rather than arrays of people

### ISSUE THREAD

**Issue by upugo-dev** [basecamp/bc3-api#225]
I'd like to programatically grant specific groups of people access to projects of certain types using https://github.com/basecamp/bc3-api/blob/master/sections/people.md#update-who-can-access-a-project

Currently I am manually electing the people via some logic I've written (actually using a tag in their name string to filter) but a much better solution would be to grant access to a `team` rather than a array of `people`. That way if people leave/join the team their project access is updated accordingly, and so on.

It seems like via the basecamp3 UI 'add people to project' I can add an entire company, but I'm wanting to do this for internal user (staff access). I guess creating a "company" with the desired staff as members, in place of teams would be a hacky workaround? Add company to project?

Or should I add everyone I want give access to projects of type A to a project "A staff", then whenever a project of type A (lets say A1) is created, https://github.com/basecamp/bc3-api/blob/master/sections/people.md#get-people-on-a-project on "A staff" and add those people to A1?

**Comment by rosa** [comment]
Hi @upugo-dev! We don't have a way currently to add everyone from a company to a project. However, what you mentioned about having everyone from group A added to project "A staff" and then fetch users from that project to add them to another project seems like a perfectly fine solution to me. 

In fact,[ _Teams_ are a kind of projects in Basecamp](https://3.basecamp-help.com/article/25-teams-and-project#teams), and I think that would suit your use case perfectly. For example, we have a _Programmers_ team and a _Designers_ team. They work exactly in the same way with respect to the API, so you can still use [the `GET /project/:project_id/people.json` endpoint](https://github.com/basecamp/bc3-api/blob/master/sections/people.md#get-people-on-a-project). The only difference with respect to regular projects is that they are shown in a different area in your account homepage and that the purpose indicated in the API responses is `team`:
```json
    {
        "id": 34656251230981,
        "status": "active",
        "created_at": "2017-04-25T13:48:33.178Z",
        "updated_at": "2019-01-29T08:55:43.264Z",
        "name": "Example team",
        "purpose": "team"

    }
```

I hope this helps!

**Comment by upugo-dev** [comment]
OK, yes this helps, thanks a lot, however;

> everyone from group A added to project "A staff" and then fetch users from that project to add them to another project seems like a perfectly fine solution to me.

This will achieve what I want to some degree, however consider this scenario: if someone is removed from the team their access to existing team projects won't be revoked; all that will happen is _they won't be added to future projects at that team's level_. 

So, you can't really grant a _team_ permission to a project, but merely all of the people within that team individually ?

**Comment by rosa** [comment]
> if someone is removed from the team their access to existing team projects won't be revoked; all that will happen is they won't be added to future projects at that team's level.

Yes, that's totally correct. 

> So, you can't really grant a team permission to a project, but merely all of the people within that team individually ?

Exactly, you can't grant _a team_ permission to a project, only to all the people individually. The same is true for companies as well. When you add everyone from a company to a project from the UI, that's really just a convenience to select everyone from a company individually. People added later to that same company won't have access automatically to that project unless you add them. We don't have a "team" feature such as the one you describe in Basecamp, unfortunately.

**Comment by upugo-dev** [comment]
> We don't have a "team" feature such as the one you describe in Basecamp, unfortunately.

Ok, well there lies my feature request then!

In the meantime, for my special teams I guess I could set up webhooks and write receivers to detect any member changes, and then add/remove them from projects as required. 

Is there any way to group projects in basecamp?

**Comment by rosa** [comment]
Webhooks are only available for recording events, I'm afraid, not projects or people events. Projects can't be grouped either. Being able to group people in teams is something that we've had in mind for a while, although I'm not sure if we'll get to implement it. It's not a feature request for the API itself, but for the whole app. Grouping projects, however, is not something we are considering.

**Comment by upugo-dev** [comment]
> It's not a feature request for the API itself, but for the whole app

Where would I register interest about this then?

> Grouping projects, however, is not something we are considering.

Dang, that's annoying. I guess I'll have to go back to using my labels in people/project strings and regex for them 😆

**Comment by rosa** [comment]
> Where would I register interest about this then?

I've already noted it internally 👍🏻

> Dang, that's annoying. I guess I'll have to go back to using my labels in people/project namestrings and regex for them 😆

Oops, sorry 😓 We also use some name conventions for our projects and have found it to be enough for our purposes, without needing additional grouping.

**Comment by upugo-dev** [comment]
> Oops, sorry 😓 We also use some name conventions for our projects and have found it to be enough for our purposes, without needing additional grouping.

I'm sure it works fine until you give clients or non-technical staff access and they go and change the name!!!

**Comment by rosa** [comment]
> I'm sure it works fine until you give clients or non-technical staff access and they go and change the name!!!

Ouch. Yeah, fortunately, that doesn't happen in our case. In any case, clients shouldn't be allowed to edit project names (but other staff added to Basecamp as team users certainly can).

Since there's nothing else to do with respect to our API, I'm closing this issue. Thanks for your understanding!
