### ISSUE TITLE
Add webhook pings for TODO moves between lists

### ISSUE THREAD

**Issue by archon810** [basecamp/bc3-api#226]
Hi,

I saw that there's no official support for moves via API https://github.com/basecamp/bc3-api/issues/89, but what about webhook notifications about moves across lists? We'd love to be notified when a BC TODO is moved around.

cc @sebsz @rosa

**Comment by rosa** [comment]
Hey @archon810! We already support these webhook notifications for to-dos moving _across projects_, you should see a `todo_inserted` event in the payload sent to your webhook URL. We don't trigger any kind of event when you move a to-do across lists or groups _in the same project_ (you won't see this in the project's activity feed, for example), so we won't add support for that kind of events in webhooks, sorry.

**Comment by archon810** [comment]
> We don't trigger any kind of event when you move a to-do across lists or groups in the same project (you won't see this in the project's activity feed, for example), so we won't add support for that kind of events in webhooks, sorry.

This is unfortunate, because it's very valuable information. For example, we have a list for News to cover now, and we have one for Embargoed news. It's pretty important to be notified when TODOs move between these two lists, for example.

Please consider this as a feature request and pass it down to the rest of engineering.
