### ISSUE TITLE
If-None-Match on People on project route

### ISSUE THREAD

**Issue by toddgeist** [basecamp/bc3-api#227]
Hello,

Should we be using Etags and "If None Match" headers on people on project routes?  It doesn't appear to be working. I always get back the full result.  Here is what I am sending

```
-X GET https://3.basecampapi.com/ACCOUNTID/projects/PROJ_ID/people.json -H \"Accept: application/json\" -H \"Authorization: Bearer <TOKEN>\" -H \"If-None-Match: W/\"f535b27388ded1f87b4392f887775f31\"\" -H \"User-Agent: MYAGENT\"
```

Did miss something?

What routes should we be using cache rules with?  Does that list exist anywhere?

Thanks

Todd

**Comment by rosa** [comment]
Hey @toddgeist! As you noticed, that endpoint doesn't use HTTP caching. We don't have a list of the endpoints that have it, but most do. You can always send `If-None-Match` and `If-Modified-Since`, though.
