### ISSUE TITLE
Need ability to create Questions and Answers

### ISSUE THREAD

**Issue by nikkilocke** [basecamp/bc3-api#230]
There does not seem to be an API call to create a Question, or to create a Question Answer.

**Comment by rosa** [comment]
Hi @nikkilocke, yes, that's right. We don't support this through the API. The API is not intended to be a 1:1 map of all features supported in the application, you can find more about this [here](https://github.com/basecamp/api#realistic-expectations).

**Comment by SamuelSeifu** [comment]
When will this be available?
