### ISSUE TITLE
Update Project API sometimes returns wrong description

### ISSUE THREAD

**Issue by nikkilocke** [basecamp/bc3-api#232]
Sometimes, when I use the update project api (PUT company/projects/id) with a name and description, the project json returned has the original description, not the new one. A subsequent call the get project returns the correct, altered description.

This behaviour is not 100% consistent - sometimes it returns the changed description, sometimes the original.

Is this a load balancing issue?

**Comment by rosa** [comment]
Oh, strange! You should see the updated description in the response from the [Update projects](https://github.com/basecamp/bc3-api/blob/master/sections/projects.md#update-a-project) endpoint in all cases if the update was successful. You mention `PUT company/projects/id`, but the endpoint to update projects is `PUT /projects/:id`, I wonder if this is related to the behaviour you're seeing, although `PUT /company/project/:id` should return a `404 Not Found`. 

If you are using the correct endpoint, `PUT /projects/:id` endpoint, could you grab all headers from the request and response and [get in touch with our Support team](https://basecamp.com/support)? You can link to this issue and mention me, and they'll send it to me to investigate.

**Comment by nikkilocke** [comment]
Just to clarify, the url I was using was https://3.basecampapi.com/<our company id>/projects/<project id>.json, which I believe is correct?

**Comment by rosa** [comment]
Yes, `https://3.basecampapi.com/:account_id/projects/:project_id.json` is correct.

**Comment by rosa** [comment]
There was indeed a bug related to cache invalidation involving this endpoint, causing the inconsistent behaviour described. We've pushed a fix for this so now you should be getting always the updated project after updating.

Thanks a lot for letting us know!

**Comment by nikkilocke** [comment]
Hi Rosa,

Thanks for the fix. I have rerun my test a few times, and it is 
all working now.

Regards,

Nikki

-- 
Nikki Locke, Trumphurst Ltd.  PC & Unix consultancy & programming
http://www.trumphurst.com/
