### ISSUE TITLE
Creating a webhook as a Basecamp Client user

### ISSUE THREAD

**Issue by mwbrooks** [basecamp/bc3-api#234]
Hello,

I've searched the API documentation and closed issues, so I apologize if this has already been answered.

### Problem

We have a Basecamp Client user who receives a 403 response when we try to create a webhook.

### Reason

There's no additional information in the `headers['reason']` or response `body`, but my assumption is that a Client of a Basecamp Account cannot register webhooks. This makes sense because Clients have restricted access but webhooks trigger on all project activity.

### Solution

1. Is it true that Clients are unable to create webhooks? Or do I have a deeper issue on our end?
1. In the [webhook section](https://github.com/basecamp/bc3-api/blob/master/sections/webhooks.md) it would be helpful to document that Clients are unable to create webhooks. That was the first place where I looked when we received the 403 response.

Thanks for the help!
Michael

**Comment by rosa** [comment]
Hi @mwbrooks! You're totally correct, clients aren't allowed to create, edit or retrieve webhooks, you aren't doing anything wrong. This should be documented as you said, so I'll add this information to the webhook section shortly. Thank you for pointing this out!

**Comment by mwbrooks** [comment]
Hi @rosa! Thanks for the quick response, clarification, and docs update! 🎉
