### ISSUE TITLE
User type flags (admin/owner/client) not updated in bc3 api

### ISSUE THREAD

**Issue by 008killer** [basecamp/bc3-api#235]
I just updated my account users from **basecamp website**.
But all **people/person/profile** api endpoints not updated these flags !
Is that a bug ? Or I am missing something here ?

**Comment by rosa** [comment]
It could be a caching bug, from what you describe. Could you provide some more details so we can have a look? The whole URL of the requests and if you have the `X-Request-ID` header returned by us would be very helpful.

**Comment by 008killer** [comment]
X-Request-ID: 33ab3217-1abb-4b38-a44c-1fab27ec1b1b
User with ID {24791137} is Admin in this account but "admin" flag is false
Url :
https://3.basecampapi.com/{AccountId}/projects/{ProjectId}/people.json
I also look other urls like "get profile" but the flag is "false"

**Comment by rosa** [comment]
Aha, yes, it was a caching bug. I've bumped the cache for the users in your account and will work on fixing the root cause. You should see the right flags returned now. Thanks for letting us know about this!

**Comment by rosa** [comment]
We've just deployed a fix for the root cause of this problem, shouldn't run into stale cached admin/owner flags anymore.
