### ISSUE TITLE
Create people endpoint

### ISSUE THREAD

**Issue by huynguyenh** [basecamp/bc3-api#236]
Hi guys, 

I'm wondering whether create people endpoint is under progress now. I saw it from the original roadmap here https://github.com/basecamp/bc3-api/issues/1#issue-141890191. But not seeing any update. 

Thanks

**Comment by rosa** [comment]
Hey @huynguyenh! I'm afraid not, in the end, we decided not to implement that endpoint. You can consider [this list of endpoints](https://github.com/basecamp/bc3-api#api-endpoints) the final one, we won't be adding new ones. 

Sorry about that!
