### ISSUE TITLE
Rescheduled to-do webhooks do not include the previous due dates

### ISSUE THREAD

**Issue by mwbrooks** [basecamp/bc3-api#237]
Hello Basecamp team,

I've noticed that the webhook event for rescheduling to-dos doesn't contain details about what changed. I would find it very useful to know what dates changed and their previous values when a rescheduled to-do event triggers.

I understand that this could be a tricky improvement to implement, but it would be greatly appreciated! 🙏 

### Expected Behaviour

When a to-do's start date (`starts_on`) or due date (`due_on`) is changed, I'd expect the webhook to include details about what properties changed and their previous value.

I'd expect these details to be included in all 3 webhook events related to rescheduling to-dos:
- `todo_scheduled`
- `todo_rescheduled`
- `todo_unscheduled`

### Current Behaviour

Currently, I can't find a way to get the to-do's previous dates or determine what date changed without storing the data myself. For privacy and performance, I don't want to do this.

### Implementation Example

I don't have the best suggestion for an implementation. It's tricky because the unset value for `due_on` or `starts_on` is `null`.

One approach would be to use the webhook details to store the previous values for both properties. Developers could then fetch the recording to get the latest property values and make a comparison:

```json
{
  "details": {
    "previous_due_on": "2019-08-26",
    "previous_starts_on": null
  }
}
```
_In the above example, we can see from the webhook details that the to-do previously had a due date (2019-08-26) and no start date. When we fetch the latest recording, we can find out what changed._

### Real-world use case

I work on a product that uses webhooks to share project activity with team members outside of Basecamp. Currently, when a to-do is rescheduled, we notify everyone with the current due date and start date. However, unless the user is familiar with the to-do, they must log in to Basecamp to understand what changed (start date or due date or both).

Our users would like to know what changed, similar to how Basecamp displays it in a comment:
![image](https://user-images.githubusercontent.com/21328/63469296-b8342980-c41e-11e9-9dd6-a51be96f888a.png)

**Comment by rosa** [comment]
@mwbrooks, thank you so much for this detailed description of the problem and your proposal for implementation. I'll look into it, I'm not sure when/if I'll be able to work on it, but I really appreciate the work you put into this 🙏

**Comment by mwbrooks** [comment]
Thanks a lot, @rosa! 🙂 

Like I said in the original post, I understand that this will probably be a lot more work than it appears from the outside. We're not blocked or serving a poor experience to our customers. But I saw this missing functionality as an improvement to the BC3 API and it would help our customers focus with reduced noise.

**Comment by rosa** [comment]
Hi again @mwbrooks! I've been looking into this and it's quite unlikely we implement this, so I'm closing this issue. I really appreciate your understanding, and I'm sorry I don't have better news regarding this 😞 Please let us know of any other issues you encounter, hopefully, we'll have better solutions for those!
