### ISSUE TITLE
Auto-add common users to new To do messages

### ISSUE THREAD

**Issue by andrewicus** [basecamp/bc3-api#238]
With the unique workflow we follow within my design org, we would benefit from the ability to automatically add People all people who have previously been added to comments within any other To do on a To do List. From the documentation, I'm not certain this is possible via the API. If it is, we would be willing to pay contracting fees to have a plugin built to accomplish this.

**Comment by rosa** [comment]
Hi @andrewicus! I'm not sure I follow exactly what you're trying to achieve. Is it adding people as subscribers to new to-dos added to a to-do list? Have you looked into [webhooks](https://github.com/basecamp/bc3-api/blob/master/sections/webhooks.md#webhooks)? You could use them to be notified about new to-dos, and then use the [Update Subscription](https://github.com/basecamp/bc3-api/blob/master/sections/subscriptions.md#update-subscription) endpoint to add people automatically to that to-do. To get the list of people, you mention "all people who have previously been added to comments within any other To do on a To do List". You could fetch this list using the [Get subscription](https://github.com/basecamp/bc3-api/blob/master/sections/subscriptions.md#get-subscription) endpoint for each of these to-dos (and keep this list stored somewhere, so you wouldn't have to build it every time a new to-do is added). 

I hope that helps! We don't offer any plugin building services or accept contracting fees to add functionality to the API.
