### ISSUE TITLE
How to add attachment to chat using API?

### ISSUE THREAD

**Issue by loogitakurrey** [basecamp/bc3-api#239]
Hello,
1. I am trying to post an attachment to chat lines in a campfire in basecamp using basecamp3 API.
Simple content is getting created but attachments are not getting created.
`{
	"content":"hello"
}`
How to add an attachment to chat lines?
2. I am getting a 400 error on adding rich-text to the content.
` {
  "subject": "Kickoff",
  "content": "<div>testing</div><bc-attachment sgid="BAh7CEkiCGdpZAY6BkVUSSIuZ2lkOi8vYmMzL0F0dGFjaG1lbnQvMTM4MzAxMjEwP2V4cGlyZXNfaW4GOwBUSSIMcHVycG9zZQY7AFRJIg9hdHRhY2hhYmxlBjsAVEkiD2V4cGlyZXNfYXQGOwBUMA==--539659284a0a6790af7" Content-Type="image/jpeg" caption="My photo"></bc-attachment>",
  "status": "active"
}');`
Not able to understand why it is not taking these value. 
I am following this doc:
https://github.com/basecamp/bc3-api/blob/master/sections/rich_text.md
Please Let me know how I can resolve this issue.

**Comment by rosa** [comment]
Hi @loogitakurrey, what you're seeing is expected. We don't support rich text in Campfire lines posted via the [Create Campfire line endpoint](https://github.com/basecamp/bc3-api/blob/master/sections/campfires.md#create-a-campfire-line). As you can see in the docs, the required `content` parameter is plain text. 

The only way to add attachments to a Campfire via the API is [using Chatbots](https://github.com/basecamp/bc3-api/blob/master/sections/chatbots.md). The [Create line](https://github.com/basecamp/bc3-api/blob/master/sections/chatbots.md#create-a-line) endpoint for chatbots supports rich text and the possibility of adding attachments, as well as other HTML tags. 

I hope this helps!

**Comment by rosa** [comment]
For the record: my reply above was incorrect. We don't support rich text in Campfire lines even if posted from a chatbot. I was confused and our docs aren't very clear either, so I'll be clarifying them. The answer to this issue is that it's not possible to upload attachments to Campfires or Pings via the API.
