### ISSUE TITLE
How to send chat lines with different people as creator?

### ISSUE THREAD

**Issue by loogitakurrey** [basecamp/bc3-api#241]
I want to create a chat line for any person in the basecamp using API.
currently, only I can send is the content to create chat lines. How to create chat lines for a different person?

**Comment by rosa** [comment]
@loogitakurrey what do you mean? The chat lines created via the [Create a Campfire endpoint](https://github.com/basecamp/bc3-api/blob/master/sections/campfires.md#create-a-campfire-line) would have the authenticated user as the creator. There's no way to create lines with a different creator than the currently authenticated user. Is this what you are referring to?

**Comment by rosa** [comment]
Ah, I understood what you meant because of this other comment: https://github.com/basecamp/bc3-api/issues/240#issuecomment-527739412. It's not possible to send a message from a chatbot and having a different creator, other than the chatbot. Sorry about that!
