### ISSUE TITLE
Missing Complete and Uncomplete for To-do Lists

### ISSUE THREAD

**Issue by trackedsupport** [basecamp/bc3-api#242]
For to-dos there is an endpoint to complete and uncomplete them, can we get the same to-do lists?

**Comment by rosa** [comment]
@trackedsupport do you mean an endpoint to mark all to-dos in a to-do list as complete? No, we don't have these endpoints. It's not even an action available in our app. To-dos have to be completed/uncompleted individually. You can archive and unarchive to-do lists by using the generic [archive/unarchive endpoints for recordings](https://github.com/basecamp/bc3-api/blob/master/sections/recordings.md#archive-a-recording).

**Comment by trackedsupport** [comment]
Sorry late-night thinking made that issue. Thanks for the info!
