### ISSUE TITLE
Feature request: need an endpoint to add a new person to Basecamp

### ISSUE THREAD

**Issue by rsarikon** [basecamp/bc3-api#243]
Hi Team,

I want to add new employees (who don't yet have access to Basecamp) to Basecamp. Is there an existing endpoint that I can use?

**Comment by rosa** [comment]
Hi @rsarikon! You can use the [`Update who can access a project` endpoint](https://github.com/basecamp/bc3-api/blob/master/sections/people.md#update-who-can-access-a-project), providing the new people in the `create` parameter:
> `create` - an array of new people with `name` and `email_address` properties, and optional `title` and `company_name` properties.

**Comment by rsarikon** [comment]
Thank you :)
