### ISSUE TITLE
Example does not work ("No chat message content found in the request body")

### ISSUE THREAD

**Issue by Calamari** [basecamp/bc3-api#244]
I am trying to build a reporting bot for our campfire, but somehow cannot get it to work.

Down in the [Chatbot README](https://github.com/basecamp/bc3-api/blob/master/sections/chatbots.md) the example is 

```bash
curl -s -H "Content-Type: application/json" -d '{"content":"Good morning"}' \
  https://3.basecampapi.com/$ACCOUNT_ID/integrations/$CHATBOT_KEY/buckets/1/chats/2/lines.json
```

If I use this (and replace the `$ACCOUNT_ID` and `$CHATBOT_KEY` with the real one of course) I only get 

```json
{"error":"No chat message content found in the request body"}
```

Since there are not that many infos to work with I am a bit clueless, so what am I missing?

**Comment by rosa** [comment]
Hey @Calamari! The sample `curl` is working fine for me. Are you using the right `bucket_id` and `campfire_id`? That is, here: `  https://3.basecampapi.com/$ACCOUNT_ID/integrations/$CHATBOT_KEY/buckets/:bucket_id/chats/:campfire_id/lines.json`

Over in your project's Chatbot configuration screen, you also have an alternative `curl` (that does the same as the sample above) with the values already set, under _Send line from this integration to campfire…_ You can try that one out as well.

**Comment by Calamari** [comment]
I copied the URL from the GitHub hook page (since it is the only page I can see with the URL to use) and rechecked (and recopied) the values for bucket and chat (it's the same as in the Web URLs). If they would be wrong, the API would return a 404 with a "Not Found" error message. That does not seem to be the problem.

I also tried it out sending it via Ruby (in case my curl is wrong), but get the same response.

I know, it's hard to help me, since I have no idea what else I can provide to make it easier. :)

**Comment by Calamari** [comment]
Ok, I will try it differently. Where should I get the right link? This is what I see.

The list page:
![Screenshot_2019-09-17_11-57-57](https://user-images.githubusercontent.com/149719/65031992-94430580-d942-11e9-9fbe-f76f446f241f.png)

and if I click on the Bot:

![Screenshot_2019-09-17_11-58-08](https://user-images.githubusercontent.com/149719/65032006-99a05000-d942-11e9-9c36-37330db7bd54.png)

But I don't see any chatbot key somewhere. The only thing that I saw was in the "Use Github?"-hint at the bottom of the list page. But that is not bound to any chatbot, so I guess, that is why that URL does not work.

So the question, what do I miss? Where am I supposed to get the URL (or key) from?

**Comment by rosa** [comment]
Ah! The values for the GitHub integration wouldn't work with that example, since that example is for your own chatbots, not for the GitHub one (that only works with requests coming from GitHub with GitHub's payload format). 

You need to create a custom chatbot like that `TestBot` you added, and the details are shown when you click on _Send line from this integration to campfire…_. For some reason, the `<details>` and `<summary>` tags aren't not working for you. That's odd, what browser are you using? This is what you should see:
<img width="770" alt="Screenshot 2019-09-17 at 12 03 24" src="https://user-images.githubusercontent.com/813033/65032521-9a85b180-d943-11e9-9a3b-255e5d4e39bc.png">

**Comment by rosa** [comment]
You can also get that URL via the API, using the [Get chatbot endpoint](https://github.com/basecamp/bc3-api/blob/master/sections/chatbots.md#get-a-chatbot).

**Comment by Calamari** [comment]
Now, that clears things up. I wondered if I miss something. That this line is expandable is really not obvious on the latest Firefox on Ubuntu (it is on chrome though).

Using the line provided in that hidden feature ;), that everything works.

You might wanna add a bit of CSS for Firefox users. Might help future users.
But for me this issue is resolved now.

Big Thanks for the help!

**Comment by Calamari** [comment]
Btw. there is no possibility, that a Chatbot can post a message to a message board, is there?

**Comment by rosa** [comment]
Ah, good catch! I didn't realise Firefox didn't show the small triangle for `<summary>` and `<details>`. I'll log this internally so we can improve it. Glad that it's working now and sorry for the confusion.  

About the message board, that's right, chatbots can't post there. You need to use the [Create message API endpoint](https://github.com/basecamp/bc3-api/blob/master/sections/messages.md#create-a-message).

**Comment by Calamari** [comment]
Which is not possible to do, without OAuth, so sadly no way to post messages there like published tags (and all that changed) from github.

But it is what it is. 

Thanks again :)
