### ISSUE TITLE
Gallery attachment support in API

### ISSUE THREAD

**Issue by martinambrus** [basecamp/bc3-api#245]
Hi guys,

It's been a while since you started to [support galleries](https://m.signalvnoise.com/new-in-basecamp-3-image-galleries/) in your BaseCamp editor, however this functionality seems to be missing from the API. We tried various ways to create a gallery with the images we've uploaded as attachments but to no avail.

The following code seems to generate the correct markup for an attachment that would actually display as real gallery in the editor itself when I edit the page but when viewing a page updated via the API to include newly attached images, the page just shows images on top of each other as usual:

`<bc-attachment presentation="gallery" sgid="' . $attachment_data->attachable_sgid . '"></bc-attachment>`

Are we missing something? And if not, would it be possible to implement the gallery functionality into the API?

Thanks!

**Comment by rosa** [comment]
Hi @martinambrus! You aren't missing anything, I'm afraid we don't support creating image galleries via the API unfortunately, and we don't plan to add support for that in the future. You can read a bit more about what to expect from API features [here](https://github.com/basecamp/api#realistic-expectations). I'm sorry I don't have a better answer for you.

**Comment by rosa** [comment]
Hey @martinambrus, some good news, I was wrong! Fortunately, my colleague @javan was there to let me know about my error 🙌 . We do support the gallery presentation for image attachments in rich text, exactly as you tried to post them, but they need to be inside their own container element (a `<div>`, typically). That is:

```
<div>
  <bc-attachment presentation="gallery" sgid="..."></bc-attachment>
  <bc-attachment presentation="gallery" sgid="..."></bc-attachment>
</div>
```

I'll be adding this to our Rich Text docs. 

Sorry for the confusion!
