### ISSUE TITLE
Get all projects endpoint does not return all projects

### ISSUE THREAD

**Issue by viraf** [basecamp/bc3-api#246]
Get all projects does not return all projects. It returns only 15 projects. As per this issue [here](https://github.com/basecamp/bc3-api/issues/8 ) the call to get all the projects were not paginated. Has this changed recently?

**Comment by rosa** [comment]
Hi @viraf! Yes, this changed around March 2017. This endpoint is now paginated using a geared pagination ratio as described in [the Pagination section](https://github.com/basecamp/bc3-api#pagination). 

I hope this helps!
