### ISSUE TITLE
"Unknown Basecamp ID" for refreshing the customers Token

### ISSUE THREAD

**Issue by amirkoklan** [basecamp/bc3-api#247]
when we are trying to refresh our customer's tokens, we get the following error.
why is that ?

```
401 Client error: `POST https://launchpad.37signals.com/authorization/token` resulted in a `401 Unauthorized` response:
Unknown Basecamp ID.
```

I would appreciate an immediate response as it made our Application broken.

**Comment by rosa** [comment]
Hey @amirkoklan! That error happens if the refresh token you're using corresponds to an identity that no longer has any active accounts in Basecamp. You can check with your customer if they cancelled their account(s) or if they were removed from the account(s) they were part of.
