### ISSUE TITLE
500 Error while trying to create schedule

### ISSUE THREAD

**Issue by martinambrus** [basecamp/bc3-api#248]
Hi guys,

I'm wondering what we're doing wrong here. All other API calls that create tasks, notebooks, documents and comments work for me but when I try to add a new scheduled entry, I get a 500 Error back every time.

I have verified the URL (which works if I just request a GET on it via Postman and lists all schedule entries), tried this with the simplest payload but to no avail.

This is the URL I'm calling for both, GET and POST (GET works): https://3.basecampapi.com/PROJECT_ID/buckets/BUCKET_ID/schedules/SCHEDULE_ID/entries.json

Here's my payload:
```
array ( 'summary' => '2009 03 05, Shopping Cart SEO Report', 'starts_at' => 1236211200, 'ends_at' => 1236207600, 'description' => '', )
```

... and here's the response:

```
HTTP/1.0 500 Internal Server Error
X-Request-Id: 3f6f0ff7-be01-4a01-bc3c-b8e4bd57f072
Cache-Control: no-cache
Server: BigIP
Connection: close
Content-Length: 3096
```

This is a screenshot of what the actual API call returns:

![image](https://user-images.githubusercontent.com/7406402/66569653-49e12d00-eb6c-11e9-9028-d3d13d8b16e7.png)

Hope you guys can help :)

With friendly regards,
Martin Ambrus

**Comment by rosa** [comment]
Hi @martinambrus, sorry about the error, and thanks for including all the response details in the issue, very useful! I believe you might be hitting a variation of #115, which we still need to fix. Basically, the `starts_at` date can't be a timestamp/epoch. Could you try providing the date as a valid ISO 8601 string?

**Comment by martinambrus** [comment]
Hi @rosa, 

Thanks for your help :) The ISO date formatting worked. 
Maybe it's worth changing documentation for it, which says to provide a timestamp?

Thanks again.
Martin

**Comment by rosa** [comment]
> Maybe it's worth changing documentation for it, which says to provide a timestamp?

Oops! Yes, absolutely. Thanks for catching this!
