### ISSUE TITLE
Messages > Trash a message - No instructions?

### ISSUE THREAD

**Issue by chriswthomson** [basecamp/bc3-api#249]
Hi,

https://github.com/basecamp/bc3-api/blob/master/sections/messages.md - Trash a message doesn't appear to be documented.

It links to https://github.com/basecamp/bc3-api/blob/master/sections/recordings.md#trash-a-recording

I've tried DELETE to: 
- `/buckets/{projectId}/messages/{messageId}.json`
- `/buckets/{projectId}/messages/{messageId}/status/trashed.json`
-  `/buckets/{projectId}/recordings/{messageId}/status/trashed.json`

None seem to work.

Can this doc please be added?

**Comment by chriswthomson** [comment]
Ah - figured it out. It's a `PUT` request to `/buckets/{projectId}/recordings/{id}/status/trashed.json`.

Might still be an idea to clarify this more in the docs?

**Comment by rosa** [comment]
@chriswthomson what do you suggest? We already say this in the docs:

> **Trash a recording**
> `PUT /buckets/1/recordings/2/status/trashed.json` 
> will mark the recording with an ID of 2in the project with ID 1 as trashed.

I think it's quite clear that it needs to be a `PUT` request to that path, but happy to add some extra clarification if you have any suggestions.

**Comment by chriswthomson** [comment]
Hi @rosa - thanks for the reply.

I think the issue is on my end, I missed this line in recordings.md:

> Most of the data structures in the Basecamp 3 API are represented as "Recordings", with generic actions available to be performed.

Once I'd read that, trashing message/comments made much more sense. Cheers

**Comment by rosa** [comment]
Ah, perfect! No worries, and thanks for letting me know! 👍
