### ISSUE TITLE
Creating a project from an existing template

### ISSUE THREAD

**Issue by thomasrumbold** [basecamp/bc3-api#250]
Is there a way to create a project programmatically, from an existing template? Do you pass the template as a parameter?

Thanks :)

T

**Comment by rosa** [comment]
@thomasrumbold, did you check the [`Create a project construction` endpoint](https://github.com/basecamp/bc3-api/blob/5c72ca1a2700b3c852485c1431706430baa26611/sections/templates.md#create-a-project-construction)?

**Comment by thomasrumbold** [comment]
Blimey, I completely missed this. This is spot on. Cheers.

T
