### ISSUE TITLE
What does it mean: 422 unprocessable entity

### ISSUE THREAD

**Issue by ademc** [basecamp/bc3-api#251]
Hi,

I can use successfully create comment api, until i create an attachment. When i created an attachment, all comment creating api calls failing: 422 unprocessable entity? What is this? What does it means?
There is no significant description. Only pain, no gain :)

Even i do not put <bc-attachment... into content, there will throw same error.

**Comment by rosa** [comment]
Hey @ademc! It usually means that something in your payload is wrong semantically and prevents the comment to be created, eg. missing a required attribute. If you provide a `X-Request-Id` value (you should get these in the response from us), we can look at what exactly is wrong.

**Comment by ademc** [comment]
Hi @rosa 

It is so simple.
This code works well

`var request ={.....};
ApiCall("https://3.basecampapi.com/......./comments.json",request,.....);`

This code not works


```
var attachmentRequest = {...};
ApiCall("https://3.basecampapi.com/...../attachments.json",attachmentRequest ); //<--- this line works well

//-----------This line complately same as above one----------
var request ={.....};
ApiCall("https://3.basecampapi.com/......./comments.json",request,.....); //<-----this line gives an error: 422


//---Of course this is not work too. if i add attachment part into content-----
var request ={.....};
request.content += "<bc-attachment sigid='.....'></bc-attachment>";
ApiCall("https://3.basecampapi.com/......./comments.json",request,.....); //<-----this line gives an error: 422
```

If i comment out attachment create api call, comment creation does not give any error.

**Comment by rosa** [comment]
I'm not sure from that code, I can't see the request body you're sending or know the particulars about `ApiCall` and its arguments. If you can provide the `X-Request-Id` or the URL of your request, I can look at our logs. Otherwise, I can't really help.
