### ISSUE TITLE
Rate Limits clarification

### ISSUE THREAD

**Issue by martinambrus** [basecamp/bc3-api#252]
Hi guys,

In your docs, you state that: 

> You can perform up to 50 requests per 10-second period from the same IP address for the same account.

I'd like to clarify - same account means requesting data for the same account ID in the URL (i.e. https://3.basecampapi.com/ACCOUNT_ID)?

Sorry if this looks obvious but I'm making sure you don't mean 50 requests per 10-second period from the same OAuth authorized APP rather than the account ID.

Thanks :)

**Comment by georgeclaghorn** [comment]
Yes, that’s correct.
