### ISSUE TITLE
"Pinned" flag missing from project response

### ISSUE THREAD

**Issue by hawkinsjb1** [basecamp/bc3-api#257]
I would like to be able to display pinned projects at the top of a list, is there any way to include a "pinned" boolean?

![pinnedProjects](https://user-images.githubusercontent.com/22828049/71753842-7a71f380-2e49-11ea-8a08-2f834c106100.PNG)

**Comment by rosa** [comment]
Hi @hawkinsjb1! First of all, apologies for the delay replying 😓 With the holidays, this issue completely slipped through the cracks. 

You can already get this from [the current response](https://github.com/basecamp/bc3-api/blob/master/sections/projects.md#get-a-project), the attribute is called `bookmarked` (it's a boolean). I hope this helps!

**Comment by hawkinsjb1** [comment]
Ah great, sorry I missed that!

**Comment by rosa** [comment]
Oh, no, no worries at all! It wasn't obvious 😊
