### ISSUE TITLE
Trash an upload?

### ISSUE THREAD

**Issue by gohanman** [basecamp/bc3-api#258]
Is it possible? There's a link in the Uploads documentation labeled "Trash an upload" but it goes to the section on "Trash a recording". There isn't a "Trash an upload" section on the Uploads documentation page despite listing it as an endpoint.

**Comment by rosa** [comment]
Hi @gohanman! Yes, that's right. Uploads are recordings and thus you can use the `/recordings/:recording_id/status/trashed.json` endpoint to trash an upload (and any other kind of recording). 

I hope this helps!
