### ISSUE TITLE
Get a to-do API 404 error Not working 

### ISSUE THREAD

**Issue by rajesh-smartwebtech** [basecamp/bc3-api#259]
Hi @lifo 
```
Get a to-do
GET /buckets/1/todos/2.json will return the to-do with an ID of 2 in the project with an ID of 1.
```

There are not working get single todo by todo id and project id 
I think the source api changed 

Thank you

**Comment by rosa** [comment]
Hey @rajesh-smartwebtech! Are you trying literally the bucket with ID `1` and to-do with ID `2`? These are fictional IDs included in the documentation as examples.

**Comment by rajesh-smartwebtech** [comment]
Hi @rosa 

i am trying following as example documentation syntax 
```
GET /buckets/[ProjectID]/todos/[TodoID].json
```
I have responded 404 all time Screenshot below 
![image](https://user-images.githubusercontent.com/35251001/73738564-b65ee800-476a-11ea-820e-a6241326b75b.png)


Thank you

**Comment by rosa** [comment]
Ah, got it! A couple of comments that might help:

- [The domain to be used in API calls](https://github.com/basecamp/bc3-api#making-a-request) is **3.basecampapi.com** instead of the app domain, 3.basecamp.com.
- Does the user authenticated by the access token you're using in the `Authorization` header have access to that to-do in particular? 

I hope this helps!

**Comment by rajesh-smartwebtech** [comment]
Hi @rosa 

There are same response 404 return in json string 
```
{
    "status": 404,
    "error": "Not Found"
}
```
![image](https://user-images.githubusercontent.com/35251001/73739719-c8418a80-476c-11ea-850e-56a9583a0e4b.png)

Thank you

**Comment by rosa** [comment]
Have you checked that the user authorized by your access token has access to the bucket you're accessing?

**Comment by rajesh-smartwebtech** [comment]
Hi @rosa 

I have checked and added access of bucket for access token
Then try but same 404 status return 

Thank you

**Comment by rajesh-smartwebtech** [comment]
Hi @rosa 
There are screenshot of project app when i update todo etc then return  trigger on my endpoint with response 
 
![image](https://user-images.githubusercontent.com/35251001/73746567-77855e00-477b-11ea-8b38-37a1f1ad0103.png)

Here on json  body -> recording -> url 
There are url provided by basecamp  

I try on this url same 404 erorr 

i think may be there are issue on basecamp api or something missing on documentation of api 

Thank you

**Comment by rosa** [comment]
Thanks for the extra details, @rajesh-smartwebtech. Could you provide the `X-Request-Id` returned in one of the 404 response headers? I'll check the logs using that and see if we figure out what's going on.

**Comment by rajesh-smartwebtech** [comment]
Hi @rosa 
Sure , requested header on got ```X-Request-Id``` was  ```e4b4e66f-dbe7-43a8-a8e2-44fd84e73faf```

Thank you

**Comment by rajesh-smartwebtech** [comment]
Hi @rosa 
Thank you for support
There are local proxy issue ...

**Comment by rosa** [comment]
Oh, great! I checked our logs for that `X-Request-Id` and looks like we did return a 404 due to the authorised user not having access to that bucket, just in case it helps for the future.

**Comment by rajesh-smartwebtech** [comment]
Hi @rosa 
Thank you !! :star: :+1: :+1:

 is it possible for my token auto update because it some time expired 
are there any api for it 
i was look all api but i don't found any kind of api 

Thank you

**Comment by rosa** [comment]
Yes! [We issue refresh tokens you can use to get a new access token](https://github.com/basecamp/api/blob/master/sections/authentication.md#oauth-2-from-scratch) (currently these expire in 2 weeks).

> We issue refresh tokens. Use them to request a new access token when it expires (2 week lifetime, currently).
```POST https://launchpad.37signals.com/authorization/token?type=refresh&refresh_token=your-current-refresh-token&client_id=your-client-id&redirect_uri=your-redirect-uri&client_secret=your-client-secret```

**Comment by rajesh-smartwebtech** [comment]
Hello @rosa 
i have checked but no ideal 
how to find client_id and client_secret for refresh token api 

so can you know me ?

Thank you

**Comment by rosa** [comment]
Hey @rajesh-smartwebtech, you can check these in https://launchpad.37signals.com/integrations, selecting the integration you're interested in.
