### ISSUE TITLE
How Get Public URL from Attachment in comment

### ISSUE THREAD

**Issue by dinhbang** [basecamp/bc3-api#260]
Hi All,

I want to sync data from Basecamp to Jira. My customers are using Basecamp, but my team is using Jira. so I want to when customers comment to-do on Basecamp then It will sync comment to Jira. I am using webhook and almost working as well. I am only have small issue. When customer attachment in comment (Using Richtext for attachment). The webhook can get bc-attachment the same: 

> bc-attachment sgid="BAh7CEkiCGdpZAYHDFKVUSSIuZ2lkOi8vsdfsdfsdfsdfdFjaG1lbnQvMTY5ODM0MjIzP2V4cGlyZXNfaW4GOwBUSSIMcHVycG9zZQY7AFRJIg9hdHRhY2hhYmxlBjsAVEkiD2V4cGlyZXNfYXQGOwBUMA==--3e0eb277e68e258619db43ec0218f1b57d72983f" content-type="image/jpeg" url="https://preview.3.basecamp.com/4436335/blobs/8efb3210-4d54-11ea-b9ad-a0369f740fe3/previews/full/image_original_mobile.jpg" href="https://storage.3.basecamp.com/4436335/blobs/8efb3210-4d54-11ea-b9ad-a0369f740fe3/download/image_original_mobile.jpg" filename="image_original_mobile.jpg" filesize="113978" width="426" height="758" previewable="true" presentation="gallery"

From Jira My team can't access URL in bc-attachment. so, My question how can get public URL which we can access without login Basecamp

Best regards,
Bang T.

**Comment by rosa** [comment]
Hi Bang! I'm afraid that's not possible, attachment URLs and preview URLs require authentication and there's no way of generating a public URL for them. The only solution I can think of, if you need to include these attachments in Jira, would be to download the attachments from your authenticated integration and upload them to Jira (I assume their API allows you to upload attachments in comments).

**Comment by dinhbang** [comment]
Hi @rosa I understood. The Basecamp API does not support download in bc-attachment. You mean I need to login my account via browser (Chrome, Firefox,...) then download and upload by manually? How Can I download it while I have client_id, client secret?
