### ISSUE TITLE
People endpoint returns success but people not added to project

### ISSUE THREAD

**Issue by DavidPaul123** [basecamp/bc3-api#261]
Calling the people endpoint to add a new person to the project, using the create parameter like this
`{
  "create": [
    {
      "name": "Some Person",
      "email_address": "some.person@email.com",
      "title": "",
      "company_name": ""
    }
  ]
}`

A successful response is return but it only contains 2 empty arrays (granted/revoked) and no user is added to the project.

**Comment by rosa** [comment]
Hi @DavidPaul123! Could you provide the value of the `X-Request-ID` header you got back in the response? I'll take a look with that.

**Comment by DavidPaul123** [comment]
Hello @rosa!  Thank you for the quick reply.  

Here is an `X-Request-ID` header from one of my attempts
`X-Request-ID: 48778472-312b-4137-bc87-66f6fa9fa569`

Thank you!

**Comment by rosa** [comment]
Thanks @DavidPaul123! Looks like we're failing to parse your request's body but not sure why. Are you setting `Content-Type: application/json` correctly?

**Comment by DavidPaul123** [comment]
doh! That was definately it.  Thank you @rosa

**Comment by mwilliams1188** [comment]
Having the same issue and I did set Content-Type.

Request cb7270ac-12eb-45ef-a53f-e188f266b616

**Comment by rosa** [comment]
Hey @mwilliams1188, I looked into your request and could only see a valid `grant` array of people IDs, that were correctly added to the project.

**Comment by mwilliams1188** [comment]
Gotcha. I didn’t think I saw a response body from the request though? Did I just miss it?

**Comment by rosa** [comment]
Hey @mwilliams1188, so sorry for the delay! I just saw this comment, it totally slipped through the cracks 😓 
> I didn’t think I saw a response body from the request though? Did I just miss it?

Do you mean a response from Basecamp API to your update request? You should have received a response like [the one in this example](https://github.com/basecamp/bc3-api/blob/master/sections/people.md#example-json-response-1). Are you still having trouble with that?
