### ISSUE TITLE
How to obtain company logo

### ISSUE THREAD

**Issue by hawkinsjb1** [basecamp/bc3-api#262]
I'm not sure if this is available as I can't find much related to account 'logos.' I see that on the web, the image address is stored under https://storage.3.basecamp.com/{accountId}/account/logo, which redirects users to a login screen if not authenticated. I'm trying to use the image on a mobile app though just passing in the access token as a header along with the storage url doesn't seem to be the way to go. Is this a header issue or are these protected images inaccessible?

**Comment by rosa** [comment]
Hey @hawkinsjb1, yes, I'm afraid we don't expose the company logo via any API endpoint. I'm sorry about that.
