### ISSUE TITLE
Todo webhook doesn't include due_on

### ISSUE THREAD

**Issue by marcmll** [basecamp/bc3-api#264]
Hello Basecamp team,

I've noticed that none of the following webhooks include the due_on attribute: 
+ `todo_created`
+ `todo_scheduled`
+ `todo_rescheduled`

It would be great to have the information about the due_on date, especially when a webhook is triggered due to exactly that attribute: `todo_scheduled`, `todo_rescheduled`.

### Expected Behaviour
When a todo is created, or a due date is added and/or changed, I'd expect the webhook to include the due_on date, at least in the details of the webhook.

### Current Behaviour
None of the `todo_created`, `todo_scheduled`, `todo_rescheduled` webhooks include the due_on attribute in any form: neither in the details, nor in the recording.

### Use Case
Our team is currently working on a tool which integrates with Basecamp and synchronises todos using the webhooks. It would be great if the webhooks included the due_on attribute, as it would avoid having to additionally send a GET request each time a todo is created and or the due date is added/changed.

**Comment by rosa** [comment]
Hi @marcmll! Thanks for using our API and opening this issue. Like in https://github.com/basecamp/bc3-api/issues/147, https://github.com/basecamp/bc3-api/issues/197, the webhook payload is common for all types of recordings. It includes the `id` of the created/scheduled/rescheduled recording, in this case the to-do, and the `id` of the bucket to which the to-do belongs. You can use both to request all the to-do details including `due_on` from the [Get a to-do](https://github.com/basecamp/bc3-api/blob/master/sections/todos.md#get-a-to-do) endpoint.
