### ISSUE TITLE
todo_created webhook call has missing due_on field

### ISSUE THREAD

**Issue by JBNavadiya** [basecamp/bc3-api#266]
We're looking for due_on field in webhook call but unable to find it. We're also not able to see it anywhere in the documentation.

Additionally, we have noticed that there is a separate todo_rescheduled webhook call & it doesn't contain the due_on value.

Can you please help?

**Comment by rosa** [comment]
Hey @JBNavadiya! Like in https://github.com/basecamp/bc3-api/issues/147, https://github.com/basecamp/bc3-api/issues/197 and https://github.com/basecamp/bc3-api/issues/264, the webhook payload is common for all types of recordings. It includes the `id` of the created/scheduled/rescheduled recording, in this case the to-do, and the `id` of the bucket to which the to-do belongs. You can use both to request all the to-do details including `due_on` from the [Get a to-do](https://github.com/basecamp/bc3-api/blob/master/sections/todos.md#get-a-to-do) endpoint.
