### ISSUE TITLE
Client Introductions

### ISSUE THREAD

**Issue by akshayklr057** [basecamp/bc3-api#267]
I am accessing Basecamp3 API to get messages, comments, client correspondences and client replies. 
I also want to access the "client introductions" and replies on that under client board, but currently there is no API to do that.

**Comment by rosa** [comment]
Hey @akshayklr057! No, I'm afraid we don't support client introductions (or replies to them) in the API, that's why you couldn't find docs for it. Sorry about that!

**Comment by akshayklr057** [comment]
@rosa Is it possible to add this API for the Basecamp3? Do you have any plans on doing so?

**Comment by rosa** [comment]
Hi @akshayklr057, no, unfortunately, no plans for this, I'm sorry.
