### ISSUE TITLE
How can we tell if a project is deleted?

### ISSUE THREAD

**Issue by trackedsupport** [basecamp/bc3-api#270]
This question may pertain to any resource but I noticed a project that a customer said is deleted in Basecamp, sometimes returns a `Failed.  Response code = 404.  Response message = Not Found.` and other times returns a `Failed.  Response code = 401.  Response message = Unauthorized.` message. How do I know if the project has been deleted or not using the API?

The documentation says "API requests may 404 due to deleted content, an inactive account, missing user permissions, etc." So Im nervous to remove their projects because of a 404 error when that may just mean that one user doesn't have permissions to the project yet.

**Comment by rosa** [comment]
Hey @trackedsupport! Sorry for the delay. You can't know if a project has been deleted vs. not made accessible using the API, nor you can know via the app. You can get the project status as part of the response to [`GET /projects/:project_id.json`](https://github.com/basecamp/bc3-api/blob/master/sections/projects.md#get-a-project), via the `status` attribute, which will let you know if the project is archived or trashed, but once the project is deleted, we'll return a 404, which would be the same response, as you said, for when a user doesn't have access to the project. This behaviour is also true for the web app, so this is not something we'll support. One possible solution is to store projects on your side per user, so if a user doesn't have access to a project, the effect is the same as if the project would have been deleted for them. You can always fetch the list of projects accessible for a user hitting `GET /projects.json` and keep that up-to-date.
