### ISSUE TITLE
HTTP: 401 Unauthorized when performing user_agent flow.

### ISSUE THREAD

**Issue by sabs21** [basecamp/bc3-api#271]
I'm working on a chrome extension which will utilize Basecamp's API, but I can't seem to authenticate. I've followed [your guide](https://github.com/basecamp/api/blob/master/sections/authentication.md) in the "OAuth 2 from scratch section". I've gotten to step 4, but it's not clear what I should do from here considering I'm using the user_agent flow. 

I thought I already got the access token, but when I try to make a call to the API (GET https://launchpad.37signals.com/authorization.json) I just get a 401 Unauthorized error. What's confusing me is that the parameters within the URL I get back at step 3 include the access_token and refresh_token: https://kb...ma.chromiumapp.org/chrome-extension://kb...ma/popup.html#access_token=BAh...547&expires_in=1209600&refresh_token=BAh...333

One final note, in my GET request I made sure to include the User-Agent and Content-Type headers. Is this a bug or am I missing something?

**Comment by rosa** [comment]
> I thought I already got the access token, but when I try to make a call to the (GET https://launchpad.37signals.com/authorization.json) I just get a 401 Unauthorized error.

Huh, how are you providing the access token when you make this request?

**Comment by sabs21** [comment]
When I perform a request to https://launchpad.37signals.com/authorization/new?type=user_agent&client_id=your-client-id&redirect_uri=your-redirect-uri using chrome.identity.launchWebAuthFlow( ... ) from chrome's identity API, I get back this URL: https://kb...ma.chromiumapp.org/chrome-extension://kb...ma/popup.html#access_token=BAh...547&expires_in=1209600&refresh_token=BAh...333

This URL contains the access_token (so it says).

**Comment by rosa** [comment]
@sabs21 right! I just checked and `chrome.identity.launchWebAuthFlow` should do the OAuth 2.0 dance for you, so it's correct you get the access token and refresh token after it finished successfully. My question is: once you have the `access_token`, how are you sending it on your next call to `GET /authorization.json`?

**Comment by sabs21** [comment]
I grabbed the access token from the url once the launchWebAuthFlow process finished, then I tested the call within postman to just double check that it actually worked. I performed a GET request to https://launchpad.37signals.com/authorization.json with an authorization header containing the bearer token. 

I just tried the request through postman again and I got more information than I did yesterday. Yesterday I was only able to see that I had received a 401 error, but today I got this error: 
`"error": "OAuth token could not be verified. The internal checksum failed, so the token data was somehow mangled or tampered with."`

Here's an image of my postman request: https://puu.sh/FZUxE/2c771330df.jpg

**Comment by rosa** [comment]
Aha, I see! Yes, that screenshot from Postman looks correct, that's the right way to send the access token. I wonder if somehow you extracted the token from the URL and copied some trailing characters rendering the token invalid?

**Comment by sabs21** [comment]
I've retried the call, but this time letting my code remove the string from the url and I'm still getting the same issue. I'm going to attach some code snippets which I'm currently using to try and nail down the authentication process.

**getBasecampData.js**
`
var authButton = document.getElementById("authButton");
authButton.addEventListener("click", function() {
  gainPermission();
});

function gainPermission() {
  // getCredentials makes an AJAX request to get data from credentials.json.
  // The callback contains credentials.json data
  getCredentials( function(callback) {
    credentials = JSON.parse(callback);
    authUrl = 'https://launchpad.37signals.com/authorization/new?client_id=' + credentials.client_id
                                                             + '&redirect_uri=' + credentials.redirect_uri
                                                             + '&type=user_agent';
    // Let chrome.identity handle user_agent flow.
    chrome.identity.launchWebAuthFlow(
      {'url': authUrl, 'interactive': true},
      function(redirect_url) {
        // Organize the parameters in the returned url into an object.
        params = getParameterObj(redirect_url);
        document.getElementById('test').innerHTML = params.access_token;
    });
  });
}

// Basic AJAX call to return credential data through a callback.
function getCredentials(callback) {
  var url = '../credentials.json';

  var request = new XMLHttpRequest();
  request.overrideMimeType("application/json");
  request.open("GET", url, true);
  request.onreadystatechange = function() {
    if (this.readyState == 4)
    {
      if (this.status == 200)
      {
        var result = this.responseText;
        callback(result);
      }
    }
  }
  request.send();
}

function getParameterObj(redirect_url)
{
   var params = redirect_url.split("&");
   return {
     access_token: params[0].split("=")[1],
     expires_in: params[1].split("=")[1],
     refresh_token: params[2].split("=")[1]
   }
}
`

**popup.html**
`<!DOCTYPE html>
<html>
<head>
	<title>Test Extension for Basecamp 3 API</title>
	<meta charset="utf-8" />
</head>
<body>
  <nav>
		<button id="authButton">Authorize Basecamp</button>
	</nav>
	<p id="test"></p>
	<script src="./JS/getBasecampData.js" type="application/javascript"></script>
</body>
</html>
`

**Comment by sabs21** [comment]
Previous post was too long...

**popup.html**
<!DOCTYPE html>
<html>
<head>
	<title>Test Extension for Basecamp 3 API</title>
	<meta charset="utf-8" />
</head>
<body>
  <nav>
		<button id="authButton">Authorize Basecamp</button>
	</nav>
	<p id="test"></p>
	<script src="./JS/getBasecampData.js" type="application/javascript"></script>
</body>
</html>

I'm just posting these in case you guys wanted to try and test this on your end

**Comment by sabs21** [comment]
I've went and coded the web_server auth flow, got the access token and everything works fine. I don't think the user_agent flow works as intended for google extensions.

**Comment by rosa** [comment]
Ahh! So sorry, @sabs21! I hadn't realised you were using the `user_agent` type. That's right, for this kind of integration you need to use the `web_server` type. Apologies for not noticing that before 😓
