### ISSUE TITLE
Recordings/Comments within a specific date-range

### ISSUE THREAD

**Issue by akshayklr057** [basecamp/bc3-api#272]
Hi team,
Is there a way to get recordings, client correspondences & client-replies based on a specific time range. For example, if I want to extract all three for past one day only, is there a way to do that? 
While exploring the API, I see that the response gives you "created_at" & "updated_at" times but I was not able to find if we can get responses based on time/date.

**Comment by rosa** [comment]
Hey @akshayklr057! Just like with topics in BCX (https://github.com/basecamp/bcx-api/issues/230), it's not possible to filter these based on date/time ranges. We don't have plans to implement support for this, sorry.
