### ISSUE TITLE
OpenAPI 3 Spec

### ISSUE THREAD

**Issue by itsbalamurali** [basecamp/bc3-api#273]
Do you guys have an OpenAPI 3 specification or postman collection?

**Comment by rosa** [comment]
Hi @itsbalamurali, no, I'm sorry! We just have the simple curl examples you can find throughout the docs.

**Comment by itsbalamurali** [comment]
@rosa are you planning to put one together?

**Comment by rosa** [comment]
Not at the moment, no, I'm sorry.
