### ISSUE TITLE
Update allowed styling on messages to match Web UI

### ISSUE THREAD

**Issue by nvaken** [basecamp/bc3-api#275]
As mentioned in #83 there is only styling allowed that is accessible through the Web UI and if I'm reading the last comment correctly the API allowed styling should actually match the Web UI. There are some styling features that I'm missing; dividers, predefined text and background colors. Could these be added so the API would actually match the Web UI again?

**Comment by rosa** [comment]
Hi @nvaken! Yes, these styles were added later to the UI. Have you tried to look at the HTML generated by the editor and include it in the content created by the API? For example, for an horizontal rule:

```html
<bc-attachment content-type="application/vnd.basecamp.horizontal-rule.html"><figure class="attachment attachment--content attachment--horizontal-rule">
  <hr>
</figure></bc-attachment>
```

In any case:
> the API allowed styling should actually match the Web UI

This is not exactly true. The last comment said:
> We're likely not going to support any formatting in the API that we don't support on the web.

That is, if it's not supported on web, it won't be supported in the API. That doesn't make the converse true, though. There might be elements allowed in the UI that aren't supported in the API.

**Comment by nvaken** [comment]
@rosa thanks for clarifying, makes sense that the api will not support every single api styling. 

To check what styling is to be used, do you mean requesting a comment with the styling through the API?

**Comment by rosa** [comment]
Yes! Or inspecting the HTML directly in the browser.

**Comment by nvaken** [comment]
Thanks, will do!
