### ISSUE TITLE
Change currently logged in user account

### ISSUE THREAD

**Issue by giacomoalbe** [basecamp/bc3-api#276]
Hi all!

I'm working on a CLI tool to operate Basecamp from the terminal, in addition to the web interface. 

Everything works fine, but I'm facing issues regarding how to change the account for the logged in user. 

I have two different "workspaces" (idk what's the right Basecamp jargon, sorry), and I'd like to select with an  API call what to use, so that if I choose Account1 and I ask for /projects, I then only retrieve the projects related to that account. 

Is it possibile to do? If not, how can I get all the projects the current logged in user owns (or uses)?

Btw, I'm using Basecamp free, is this a pro feature?

**Comment by rosa** [comment]
Hey @giacomoalbe! The account ID is included in the URL of the requests, as explained [here](https://github.com/basecamp/bc3-api#making-a-request). Using the `GET /projects` endpoint as an example, you'd do:
```
GET https://3.basecampapi.com/111111111111/projects.json
```
to get all projects for account `111111111111`, and
```
GET https://3.basecampapi.com/222222222222/projects.json
```
to get all projects for account `222222222222`. 

This is how you change the account for the logged-in user, using the IDs of the accounts the user has access to.
