### ISSUE TITLE
Can't sign in

### ISSUE THREAD

**Issue by ursedaniel** [basecamp/bc3-api#278]
Hello, hitting the sign in button over https://launchpad.37signals.com/signin doesn't do anything, no requests in network, no error in console.
Same if i click the button to sign in with google and same if I hit the button to reset my password.

L.E. Apparently this issue happens in Chrome, in Firefox it works.

**Comment by rosa** [comment]
Hi @ursedaniel! Login in Chrome is working perfectly for me. You might have some extension or content blocker preventing you from signing in. Get in touch [with our Support Team](https://basecamp.com/support) and they'll be able to help you. This GitHub repo is for issues related to our public API.
