### ISSUE TITLE
Improve "Update who can access a project" to Create/Add Client users to a Project

### ISSUE THREAD

**Issue by dmabram** [basecamp/bc3-api#279]
Enhancement request:

It looks like you can create and add regular users to a project:

https://github.com/basecamp/bc3-api/blob/master/sections/people.md#update-who-can-access-a-project

but you can't create and add Client users to a project.

**Comment by rosa** [comment]
Hi @dmabram! This is right, that endpoint is to add team users only. As explained in https://github.com/basecamp/bc3-api/issues/218#issuecomment-477911178, we don't have plans at the moment to add support for adding support for client users, I'm sorry!
