### ISSUE TITLE
Allow other URL schemes in rich-text `a#href` attributes

### ISSUE THREAD

**Issue by carlo** [basecamp/bc3-api#280]
Using BC3 on a Mac, I'd like to be able to link rich-text elements in notes or comments to local entities.  For example, I use Bear and would like to be able to create and later use links to Bear notes, e.g. `bear://x-callback-url/open-note?id=…`.

Right now I am able to use those URIs as link targets when editing a note in BC3 but when the note/comment is rendered, the `href` attribute of the link isn't set, so those links aren't pointing anywhere.

**Comment by rosa** [comment]
Hey @carlo, thanks for letting us know about this. Currently, we don't have plans to allow other schemes like `bear://`, I'm sorry.
