### ISSUE TITLE
API Docs & Files - upload zip file

### ISSUE THREAD

**Issue by JanVrabel** [basecamp/bc3-api#281]
Hi bc team, I am looking for possibilities to automate a few processes in our company and right now I am experimenting with your bc3 api for a few days (impressive work btw), unfortunately I am not able to go succesfuly through zip file upload into Docs & Files. I was trying mostly "Documents" endpoint (because I noticed, over the web page there is possibility to upload also zip file), but from my iOS code I am still receiving 406. I am probably missing something or just did not fully understand your doc in case of "Documents". Can You help me pls by answering to:

1) Am I looking on good endpoint (Documents) or for purpose of zip file upload into "Docs & Files" vault there is some another endpoint?
2) If "Documents" is the right one, how exactly (and into which part of request) is necessary to append zip file data?
3) Parameters "title", "content", "status" are in doc marked as "required parameters", but I am not sure, if those parameters are standard http(s) parameters, or they should be added into request body, or into request header? (base on Your curl example I would expect, they are not belongs to header, but I just wanto to be sure)
4) is there some example of uploading any other file type? (except text/json format). I was looking for something like this more than 3 hours without any success

thnx a lot

**Comment by JanVrabel** [comment]
my bad, I missed the "Upload" endpoint. I finally understand how the workflow works (if someone else will looking for that):

1) at first attachment has to be created by "Attachments" endpoint, which returns sgid of this attachment
2) after that this sgid has to be used in "Upload" endpoint

**Comment by rosa** [comment]
Yes! The "Upload" endpoint is exactly what you need here 😊  Happy you figured it out!
