### ISSUE TITLE
Getting 403 errors when trying to load images/files embedded in Messages/Comments

### ISSUE THREAD

**Issue by jonwatty** [basecamp/bc3-api#282]
Hey folks,

I am noticing many images and files that are in messages/comments are throwing a 403 error.  The API calls I am using are working fine as far as I can tell as they return the correct json but if someone has embedded an image, it doesn't seem like the permissions are passing through.  Looking at the API documentation and comparing it with what is in the content, it looks like the files are hosted in AWS and some kind of proxy is being used to from the Basecamp side.  The URL I see when inspecting the code where the API is being used is https://preview.3.basecamp.com.  When loaded in a browser with an authenticated session (Not an API call), will redirect to an AWS URL and display the image.  I tested it with a non-authenticated session and I get the said 403 error.  In the documentation, it appears images would be hosted at https://3.basecamp.com so I am guessing this was moved over to AWS at some point and the API is not updated to allow the OAuth authentication to access that URL?

Cheers,
Jon

**Comment by foxontherock** [comment]
The api "token" doesn't allow the document to be downloaded.

When I query my comments for a task, I see that the "src" looks like: 
https://preview.3.basecamp.com/id.../blobs/(guid)/previews/full/img_xx.jpg

If I open that link from an anonymous browser, I get a 403.

You must be connected to basecamp 3 UI (not the API) to be able to download it.
If you have the right to see the document, the url is then redirected to its AWS S3 location, with a temporary link that will expire in 86400 minutes I think.
But, That temporary link can be used used by someone who doesn't have access to the task and is not connected.

Also, before the last updates of chrome (80 I think), we were able to "preview" the documents in our app using an <img src...>, but now, there's a CORS limitation and the preview no longer works from the browser!

**Comment by rosa** [comment]
Hey @jonwatty, @foxontherock, sorry for the late reply! As you've noticed, the URLs for attachments and their previews aren't API URLs. Downloading attachments is not supported by the API. You can find some more details in this related issue: https://github.com/basecamp/bc3-api/issues/215#issuecomment-473659858
