### ISSUE TITLE
Oauth2 Golang "error":"redirect_uri_mismatch"

### ISSUE THREAD

**Issue by adarosci** [basecamp/bc3-api#283]
I'm trying to do oath2 authentication, I'm relying on the documentation
https://github.com/basecamp/api/blob/master/sections/authentication.md

I'm already receiving the code and I'm making the request for / token in order to obtain the access token, but no matter what I do I always get the same answer.

**{"error": "redirect_uri_mismatch"}**

I tried to use Golang's specific library for oauth
https://godoc.org/golang.org/x/oauth2
but I am trying the same answer.

could someone give me a light of what I may be doing wrong.

sorry for English, I used translation for help me

this is my code
`
package main

import (
	"encoding/json"
	"fmt"
	"io/ioutil"
	"net/http"
	"strings"
	"time"

	"github.com/go-chi/chi"
	"github.com/go-chi/chi/middleware"
	"github.com/go-chi/cors"
)

// CredentialOAuth credential return oauth
type CredentialOAuth struct {
	Type         string `json:"type"`
	ClientID     string `json:"client_id"`
	ClientSecret string `json:"client_secret"`
	RedirectURI  string `json:"redirect_uri"`
	Code         string `json:"code"`
}

func main() {
	r := chi.NewRouter()

	// A good base middleware stack
	r.Use(middleware.RequestID)
	r.Use(middleware.RealIP)
	r.Use(middleware.Logger)
	r.Use(middleware.Recoverer)

	cors := cors.New(cors.Options{
		// AllowedOrigins: []string{"https://foo.com"}, // Use this to allow specific origin hosts
		AllowedOrigins: []string{"*"},
		// AllowOriginFunc:  func(r *http.Request, origin string) bool { return true },
		AllowedMethods:   []string{"GET", "POST", "PUT", "DELETE", "OPTIONS"},
		AllowedHeaders:   []string{"Accept", "Authorization", "Content-Type", "X-CSRF-Token"},
		ExposedHeaders:   []string{"Link"},
		AllowCredentials: true,
		MaxAge:           300, // Maximum value not ignored by any of major browsers
	})
	r.Use(cors.Handler)
	r.Use(middleware.Timeout(60 * time.Second))

	r.Post("/token", func(w http.ResponseWriter, r *http.Request) {
		fmt.Println("redirect token ->", r)
	})

	r.Get("/auth", func(w http.ResponseWriter, r *http.Request) {

		// usando oauth
		obj := CredentialOAuth{
			ClientID:     ".....",
			ClientSecret: ".....",
			Code:         r.FormValue("code"),
			RedirectURI:  "http://localhost:3333/token",
			Type:         "web_server",
		}

		data, _ := json.Marshal(obj)
		payload := strings.NewReader(string(data))

		// requisição manual
		client := &http.Client{}
		req, err := http.NewRequest(
			"POST", "https://launchpad.37signals.com/authorization/token", payload)

		req.Header.Add("Content-Type", "application/json")

		if err != nil {
			fmt.Println(err)
		}

		res, err := client.Do(req)
		defer res.Body.Close()
		body, err := ioutil.ReadAll(res.Body)

		fmt.Println(string(body))

		w.Write(body)
		w.WriteHeader(http.StatusOK)
	})

	http.ListenAndServe(":3333", r)
}
`

**Comment by rosa** [comment]
Hey @adarosci, so sorry for the delay replying! What value for `redirect_uri` have you configured in https://launchpad.37signals.com/integrations?
