### ISSUE TITLE
Is Project Archiving suppported?

### ISSUE THREAD

**Issue by rileypaulsen** [basecamp/bc3-api#284]
PUT requests for projects appear to only support changing the name and description. Is it possible to archive a project via the API?

**Comment by rosa** [comment]
Hey @rileypaulsen! No, we don't support that via the API for projects, [only for recordings](https://github.com/basecamp/bc3-api/blob/master/sections/recordings.md#archive-a-recording). I'm sorry about this.

**Comment by rileypaulsen** [comment]
No problem just checking to make sure we hadn't missed it.
