### ISSUE TITLE
Can't work with clients in API

### ISSUE THREAD

**Issue by sonofskywalker3** [basecamp/bc3-api#285]
I can't create a client user via the API, or find any way to allow clients to view different ToDo lists or documents. Can this be implemented please?

**Comment by miguelff** [comment]
Hey @sonofskywalker3, as explained in https://github.com/basecamp/bc3-api/issues/218#issuecomment-477911178, the API only support the creation of _team users_. For now, we don't have plans to add support for adding clients via the API, sorry.

**Comment by sonofskywalker3** [comment]
Could you possibly explain to me why that is? The automation I've been able to achieve is great, but not being able to do anything with clients using it is really breaking my workflow. Right now I can create everything I need, but I have to send an email to my drafts, then manually add the client, and manually change what he can view, before I can go into my drafts and send the email. It's cumbersome and would really be very helpful to be able to automate these steps somehow.
