### ISSUE TITLE
Mentions in chatbot commands

### ISSUE THREAD

**Issue by leonatherton** [basecamp/bc3-api#287]
When mentioning others inside a chatbot command, the mention is seen as the ￼ character.

Is it possible for the chatbot to see who was mentioned?

**Comment by rosa** [comment]
Huh, that's odd! Have you tried adding mentions simply as `@name` (plain text)?

**Comment by leonatherton** [comment]
Sorry, I didn't make this clear enough.

When commanding a chatbot, e.g.
`!chatbot command that includes a mention e.g. @rosa`

The chatbot sees
`"command":"command that includes a mention e.g. ￼"`

Is it possible for the chatbot to determine who I mentioned in my command?

**Comment by leonatherton** [comment]
Ah, my mistake - I understand now. That does indeed allow the chatbot to see the mention.

I can make do as-is, but it _would_ be nice (and improve UX) if the person commanding the chatbot could use the rich text mentions.

Even substituting rich text mentions with plain text ones on the backend would be ok, though having the attachable_sgid value would be ideal (to make identifying the mentionee a little easier).

Thanks

**Comment by rosa** [comment]
No problem, @leonatherton! I agree, that'd be definitely a nice to have. We aren't currently adding new features like that to our API and probably won't in the future, but we'll definitely take this into account if we do.
