### ISSUE TITLE
What's the best way to verify if OAuth refresh token flow is working properly

### ISSUE THREAD

**Issue by rvanbaalen** [basecamp/bc3-api#288]
I've implemented the entire OAuth auth flow and all is working just fine. However, I don't see a way to properly emulate 'expired' tokens and thereby triggering the OAuth token refresh flow in my application.

Could you advise how to test this? How can I emulate an expired token to verify that the refresh token flow is working properly?

Thanks.

**Comment by rosa** [comment]
I think this would depend on your own environment and how your app is setup. I'd probably use a stub for the API calls in my tests, having it reply with a 401 response and a `OAuth token expired` error message, then verify that the next step after that is to perform the refresh token flow.

**Comment by rvanbaalen** [comment]
Thanks rosa that might just be enough. 

I could not find anywhere what the response of Basecamp would look like in this scenario (even dug through the OAuth spec). 

If a 401 + expired message is what I'm looking for, that will help.

Related to this scenario; when a user changes their password in Basecamp, am I correct in assuming that refreshing the token automatically won't work (due to the 'deadbolt rekeyed' message)?

**Comment by rosa** [comment]
> Related to this scenario; when a user changes their password in Basecamp, am I correct in assuming that refreshing the token automatically won't work (due to the 'deadbolt rekeyed' message)?

Yes, that's right! The user would need to re-authorise your integration so you get a new refresh token in this case.

**Comment by rvanbaalen** [comment]
And when its rekeyed, the status code will be 401 as well? So the software needs to interpret the error message (expired vs rekeyed) to determine the course of action, correct?

**Comment by rosa** [comment]
@rvanbaalen yes, exactly! When rekeyed, you'll get a 401 with a `This Basecamp ID rekeyed its deadbolt.` error message, but this error will be returned when you try to use your refresh token to get a new access token.

**Comment by rvanbaalen** [comment]
Thanks! Thats all I needed. As it turns out I've also got an expired token saved from previous testing so I can verify it's all working as intended now.
