### ISSUE TITLE
Another way to get a single comment

### ISSUE THREAD

**Issue by renehernandez** [basecamp/bc3-api#290]
I was testing how to get a [single comment by id](https://github.com/basecamp/bc3-api/blob/master/sections/comments.md#get-a-comment) and I found out that the following URL structure also works:

```
/buckets/<project_id>/recordings/<recording_id>/comments/<comment_id>.json
```

Compare to the suggested one in the link which is:

```
/buckets/<project_id>/comments/<comment_id>.json
```

Is the first URL supported or does it just work by chance?

**Comment by rosa** [comment]
Hey @renehernandez! First of all, sorry for the delay replying. That URL is not "officially" supported but should work exactly in the same way as the URL mentioned in the docs. It probably will continue working but might be safer to rely on the documented one 😊
