### ISSUE TITLE
/xxx/people.json returns garbage

### ISSUE THREAD

**Issue by foxontherock** [basecamp/bc3-api#291]
We recently starts receiving lots of users from the /people.json endpoint that have nothing to do with our account...

We fix the app by keeping only the "personable_type":"User".

But, what are these other "personable_type", and why do you return them in the /people.json route?
These are some of the types we got, I suppose there's more maybe?
User
Integration
DummyUser
Tombstone
Outsider

**Comment by rosa** [comment]
Hey @foxontherock, the `/people.json` endpoint hasn't changed, it has always returned these users with different `personable_type` values if the authenticated user has access to them. You can read a bit more about that in https://github.com/basecamp/bc3-api/issues/181#issuecomment-450371107.

**Comment by foxontherock** [comment]
Ok... but some customers of our app told us about that like if it's new! Maybe it's not...

For 1 particular user, we need to loop 10 pages of people, that is 1000 users, only to get a list of 30 valid users at the end, the same they see on your UI.

**Comment by rosa** [comment]
It's possible these users have been converted to admins and now they can see more people in the account. Depending on your use case, you could perhaps return only people that are in a specific project, using [this end point](https://github.com/basecamp/bc3-api/blob/master/sections/people.md#get-people-on-a-project).
