### ISSUE TITLE
Creating a to-do list returns a 404 error but only for one specific to do list on a specific project

### ISSUE THREAD

**Issue by lunchpaillola** [basecamp/bc3-api#293]
Hey! 

Trying to diagnose why I'm getting a 404 error with the basecamp3 API when trying to create a new to-do list. This issue is only occurring on one user's account for a specific project. The user can post to-do lists on other projects in their account without a problem. 

To create a to-do list, I'm hitting the [/create to-do list endpoint](https://github.com/basecamp/bc3-api/blob/master/sections/todolists.md#create-a-to-do-list) and I have checked the project id, dock id, and account id and those are pulling correctly. The project also isn't archived.

Any ideas why attempting to create one to-do list might return a 404 error while other projects and to-do lists on the same account work without error?

**Comment by rosa** [comment]
Hey @lunchpaillola! Without looking at any logs to investigate your specific case, my first guess is that the authenticated user might not have access to that project in particular. Could you check if this is the case?

**Comment by lunchpaillola** [comment]
Thanks so much for the response @rosa!  This particular user is the owner of the account and they can create to-do lists in their own account just fine,  just not through the API integration currently for only one project.

Basically, I have basecamp connected to a  platform where people can create to-do lists and post those to-do lists to their basecamp account. 

Looking at the server logs, all I'm seeing is a 404 error that triggers when a particular to-do set id is used and the error is "Workflow error - The service Basecamp API - Create to-do list just returned an error (HTTP 404). Please consult their documentation to ensure your call is set up properly. Raw error: {&quot;status&quot;:404,&quot;error&quot;:&quot;Not Found&quot;}" but when the user uses a different project with a different to do set id it posts no problem.

**Comment by rosa** [comment]
> This particular user is the owner of the account and they can create to-do lists in their own account just fine, just not through the API integration currently for only one project.

Can they access the problematic project and create to-dos there from the UI? Even if a user is the account owner, they might not have access to all projects in the account.

**Comment by lunchpaillola** [comment]
Yep! They can access the project and create to-dos from the UI

**Comment by rosa** [comment]
Oh, I see! Could you find the value of a header we return in our response, `X-Request-Id`, for one of these requests to create a to-do list that are failing with a 404? That ID will allow us to check our logs and figure out what's going on.

**Comment by lunchpaillola** [comment]
Hi Rosa! I'm in the network logs in chrome and I'm not seeing an x-request-id in the response header when creating a to-do list. The only time I'm getting the x-request-id for this user is when I authorize the app with basecamp. Is that id still helpful?

**Comment by rosa** [comment]
Hmm... Sounds like the network logs you're seeing in Chrome are the ones for your integration but not the ones from BC3's API. These logs should be server-side, as it should be your application the one doing requests to the BC3 API. Could you inspect these server-side logs to see if you can find the `X-Request-ID`? 

Alternatively, could you email support@basecamp.com and provide the account ID, project ID and email address of the user who's getting this error? You can also mention "Rosa" on that email to support or this GitHub issue so it gets to me quickly. With that information, we should be able to find any clues in our logs.

**Comment by lunchpaillola** [comment]
Thank you so much Rosa! I just sent over the message

**Comment by rosa** [comment]
Wonderful! I'm closing this issue as we'll be troubleshooting over there and it's not an error with the API itself.
