### ISSUE TITLE
GET Vaults

### ISSUE THREAD

**Issue by nickwild-999** [basecamp/bc3-api#294]
Is there anyway I can get all the vaults in a project (nested or not) WITHOUT having to specify the ids of the parent vaults.

I need a JSON array of ALL the vaults in a project

**Comment by rosa** [comment]
Hey @nickwild-999, this is currently not possible but would be possible via [the `GET /recordings` endpoint](https://github.com/basecamp/bc3-api/blob/master/sections/recordings.md#get-recordings), specifying `type=Vault`, which is currently not supported. I'll see about supporting that type in that endpoint.

**Comment by nickwild-999** [comment]
That would be perfect thanks @rosa

**Comment by rosa** [comment]
Hey @nickwild-999, I've just pushed that change and updated the documentation accordingly in https://github.com/basecamp/bc3-api/commit/3b64ab42533a96e0885de55179d3d27a7ffdf949. You should be able to use this to get all vaults in a project. Notice that this will include the root vault (normally named `Docs & Files`) as well.

**Comment by nickwild-999** [comment]
That is excellent news! Thanks for pushing that change so quickly, much
appreciated. We are now moving to a paid subscription! :-)


On 4 February 2021 at 07:40:09, Rosa Gutierrez (notifications@github.com)
wrote:

Hey @nickwild-999 <https://github.com/nickwild-999>, I've just pushed that
change and updated the documentation accordingly in 3b64ab4
<https://github.com/basecamp/bc3-api/commit/3b64ab42533a96e0885de55179d3d27a7ffdf949>.
You should be able to use this to get all vaults in a project. Notice that
this will include the root vault (normally named Docs & Files) as well.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/basecamp/bc3-api/issues/294#issuecomment-773101344>, or
unsubscribe
