### ISSUE TITLE
Another request to support clients via API

### ISSUE THREAD

**Issue by kaitscott** [basecamp/bc3-api#295]
I already see this isn't possible, but I wanted to register another ask for the support to create clients via API.

I'm setting up an integration via Zapier to create a Basecamp project and am sorely disappointed to see that this functionality isn't available. My clients will be filling out a form to trigger the creation of a Basecamp project. I wanted to automatically add clients to the project and then use Messages to send them a welcome note/instructions on next steps.

Without API support for clients, my project managers will have to be notified to add clients manually and I'll need to use a different app to send my onboarding message. Time-to-adoption by my clients increases (it's less likely they'll be at their computers ready to get started by the time my PMs add them vs. within minutes of them filling out the form), it creates work for my PMs, and decreases our Basecamp app usage.

Again, I see that support isn't being considered at this time but I strongly hope that decision is reassessed.

**Comment by rosa** [comment]
Hey @kaitscott, thanks for letting us know. It's definitely helpful to know your use case. We don't have plans at the moment to add this feature to the API but we might reconsider that. I'll be sure to let you know if that happens.
