### ISSUE TITLE
How to get an attachment from a comment?

### ISSUE THREAD

**Issue by vishalsaqbsolutions** [basecamp/bc3-api#296]
Hi,

I want to use the attachments of comments. I am unable to load or download it because it has some authentication issue on the browser. I am getting the content of the comment as <bc-attachment> and also the src of the file or image But unable to use or download or use somewhere another place. 

Is there a way to fetch that attachment so that it can be displayed with the comment elsewhere as well?

**Comment by rosa** [comment]
Hey @vishalsaqbsolutions, I'm afraid this is not possible via the API. You can find more info in this related issue: https://github.com/basecamp/bc3-api/issues/215#issuecomment-473659858
