### ISSUE TITLE
RE: Client Approvals, Client correspondences and Client replies API

### ISSUE THREAD

**Issue by Raj-PMP** [basecamp/bc3-api#297]
Hi There,

I have gone through the API documentation but nowhere mentioned " Client Approvals, Client correspondences and Client replies API's details. 

Actually while trying to fetch these details, getting the following errors, expecting your support for the same.

**500 Internal Server Error for - Client replies** 
**404 error for - Client Approvals  & Client correspondences** 

Cheers 
Raj

![Basecamp Client approvals error](https://user-images.githubusercontent.com/80114454/110147453-b1eb7f80-7e01-11eb-84ae-ddbf1fd3437a.jpg)
![Client corres error](https://user-images.githubusercontent.com/80114454/110147458-b31cac80-7e01-11eb-8a81-7f14f42234c4.jpg)
![Client replies](https://user-images.githubusercontent.com/80114454/110147460-b44dd980-7e01-11eb-9151-d4ed3d434667.jpg)

**Comment by rosa** [comment]
Hey @Raj-PMP, 

> I have gone through the API documentation but nowhere mentioned " Client Approvals, Client correspondences and Client replies API's details.

You can find documentation for client approvals, replies and correspondences in these pages:
- [Client approvals](https://github.com/basecamp/bc3-api/blob/master/sections/client_approvals.md#client-approvals)
- [Client correspondences](https://github.com/basecamp/bc3-api/blob/master/sections/client_correspondences.md#client-correspondences)
- [Client replies](https://github.com/basecamp/bc3-api/blob/master/sections/client_replies.md#client-replies)

It's possible the project you're using in your API requests doesn't support clientside. It's also possible the `baseURL` you're using is incorrect (I can't see the value for that one in your screenshots).

**Comment by Raj-PMP** [comment]
Hey @rosa : Here in the baseurl we have included https://3.basecampapi.com/account_id

**Comment by rosa** [comment]
Could you provide the value for the `X-Request-Id` header returned in our responses? I can have a look in our logs with these and find out more about why these aren't working for you.

**Comment by Raj-PMP** [comment]
Hey @rosa :  X-Request-Id :  5e950add-200f-4c29-8b87-d4bb43dbca9e

**Comment by rosa** [comment]
Aha, I checked and it's what I mentioned in my first comment. The project (bucket) you're using in that request doesn't have clientside enabled, so we return a 404.

**Comment by Raj-PMP** [comment]
@rosa : As per this: https://3.basecamp-help.com/article/118-using-the-clientside#adding-clients-to-the-clientside

Clientside is a way that folks used to work with clients in Basecamp. It's an older feature that is no longer available

**Comment by rosa** [comment]
Yes! That's right @Raj-PMP. Old projects that had the clientside feature before that changed to [the new way of working with clients](https://m.signalvnoise.com/launch-a-brand-new-way-to-work-with-clients-in-basecamp-3/#:~:text=Introducing%20Clients%20in%20Basecamp!&text=That%20means%20you%20can%20assign,do%20it%20with%20your%20clients.) still continue to work with it and are accessible via the API. I wasn't sure if your project was one of this kind.

**Comment by Raj-PMP** [comment]
Hey @rosa : we are not able to access the API for the earlier mentioned endpoints (i.,e) Client replies, Client Approvals & Client correspondence. Whatever mentioned in the shared link, it's all about the dashboard format and not able to find the API information.

**Comment by rosa** [comment]
I'm not sure I follow. Do you mean that the projects you're using in your API requests do have clientside enabled but you're still not able to access these endpoints? Do you see the clientside enabled on the Basecamp app?
