### ISSUE TITLE
Feature request: List of assigned todos to a person

### ISSUE THREAD

**Issue by nekromoff** [basecamp/bc3-api#298]
Hello,

currently it is impossible to get todos assigned to a person. One would need to iterate over all projects, all todo lists and all todos, to get such data.

It would be however easy to add person id as a parameter to the todos endpoint.

This was partially mentioned in #161 three years ago.

**Comment by rvanbaalen** [comment]
I second this. It would be a great feature.

**Comment by nekromoff** [comment]
Actually, my mistake. This would be proper to add to a people/person endpoint. Such as:
`GET /people/2/todos`

**Comment by rosa** [comment]
Hey @nekromoff! I'm sorry, we don't plan to add this feature to the API. The reply here https://github.com/basecamp/bc3-api/issues/92#issuecomment-453435317 still applies though. This is also covered in the app via [What’s on someone’s plate?](https://basecamp.com/features/reports) report, but as we explain [here](https://github.com/basecamp/api#realistic-expectations), the API is not intended to be a 1:1 map of the app features.

**Comment by nekromoff** [comment]
Thanks, @rosa, however that means going over 21k of todos as there is no way to filter by completed and other paramaters.
And that specifically means that your API will either block me (rate limit) or limit me in a way it is impossible to work with (rate limit delays needed to pull data).

**Comment by mlangenberg** [comment]
> or the iCal feed we provide for your own to-dos are the closest features we support

@rosa Where can I find this iCal feed and does it include to-dos without a due date?

**Comment by rosa** [comment]
@mlangenberg you can find it by going to _My Stuff_ > _My Schedule_. There's a link on top that will take you to the links to different calendar apps:

<img width="653" alt="Screenshot 2021-05-04 at 11 54 15" src="https://user-images.githubusercontent.com/813033/116987644-9ac8f100-accf-11eb-8386-4cf43ba7451a.png">

> does it include to-dos without a due date?

No, only to-dos with due date and events.
