### ISSUE TITLE
Feature Request: Add metadata to basecamps

### ISSUE THREAD

**Issue by mocerinoj** [basecamp/bc3-api#30]
I.e. my CRM client ID to a basecamp with the ability to search for it later

**Comment by Sieabah** [comment]
+1

**Comment by joshmassey** [comment]
+1

**Comment by rosa** [comment]
We aren't likely to implement this, at least not in the near future. I suggest to add any metadata like this in [the description of the project](https://github.com/basecamp/bc3-api/blob/master/sections/projects.md#create-a-project), that'll make it searchable too.
