### ISSUE TITLE
Embedding a video to a post

### ISSUE THREAD

**Issue by garyss2000** [basecamp/bc3-api#301]
Hi,

I'd like to know if it's going to be possible to embed a video (other than YouTube) to a post. Specifically, we want to embed Loom videos/links into posts.

I've been reading through the API and section on RichText, and noting that "Allowed HTML tags" has no mention of embed or video tags.

Plus, given this is an API-level integration I assume from a DOM perspective it's not going to allow us to have a toolbar button or paste a link into a post to embed a video to a post.

Can someone give me any guidance around the possibility of embedding a video to a post?

Thanks in advance,
Gary.

**Comment by rosa** [comment]
Hey @garyss2000, uploading the video itself [as an attachment](https://github.com/basecamp/bc3-api/blob/master/sections/attachments.md#attachments) is the closest option you have using the API, I'm afraid.
