### ISSUE TITLE
Can we do personal message to circle via chatbot

### ISSUE THREAD

**Issue by hassanuos** [basecamp/bc3-api#305]
I am working on a chatbot and I want to send a personal message to the employee to keep him updated. 

![image](https://user-images.githubusercontent.com/13483548/123630386-249fc100-d81e-11eb-95c5-e8928f057134.png)

Is there any way to do this? Thanks

@rosa

**Comment by rosa** [comment]
Hey @hassanuos, you can't initiate a ping with a user with a chatbot, but once the user has pinged the chatbot at least once, you can reply to that ping from the chatbot. Another possibility is to have the chatbot create a Campfire line with a mention for someone in your org instead of pinging them (for notification purposes this will have the same effect as a ping).

**Comment by hassanuos** [comment]
@rosa thanks. can you send me any example to reply from chatbot to that particular user ??

**Comment by rosa** [comment]
It works basically in the same way as [creating lines](https://github.com/basecamp/bc3-api/blob/master/sections/chatbots.md#create-a-line), just with a different URL to POST the requests to. You'll get the URL to post replies from the payload sent to your configured URL. When the chatbot is invoked, the payload described [here](https://github.com/basecamp/bc3-api/blob/master/sections/chatbots.md#chatbots) includes a callback URL, under `callback_url`. This is the URL you should use to post your response from the bot, and will correspond to the ping (circle) with the user that invoked the chatbot in the first place.

**Comment by hassanuos** [comment]
@rosa I tried the same thing as you said. But no success.

**Method -1 Tried (Failed)**

`user/11569434`
https://3.basecampapi.com/24125415/integrations/TosdWTx75RqD1iyfYRj9uyrQ/buckets/11178459/user/11569434/lines

**Method-2 Tried (Failed)**
`circle/11569434`
https://3.basecampapi.com/24125415/integrations/TosdWTx75RqD1iyfYRj9uyrQ/buckets/11178459/circle/11569434/lines

POST Content

`{
  "content": "What up?"
}`

![image](https://user-images.githubusercontent.com/13483548/123639590-05f2f780-d829-11eb-9ea5-26e6a64bbf02.png)

**Comment by rosa** [comment]
@hassanuos none of these URLs you're using looks like the `callback_url` we include in the payload sent to the chatbot when it's invoked. Check the one in the example included [here](https://github.com/basecamp/bc3-api/blob/master/sections/chatbots.md#chatbots):
```json
  "callback_url": "https://3.basecamp.com/195539477/integrations/2uH9aHLEVhhaXKPaqrj8yw8P/buckets/2085958501/chats/9007199254741775/lines"
```
Notice the hostname (3.basecamp.com) and the path (no `user` or `circle` included there). Could you ensure you're posting the request to the callback URL received in the response to the chatbot invocation?

**Comment by hassanuos** [comment]
@rosa I know this is not a callback URL because i made a modification in that the below is the exact `callback_url` that i received after invoke.

https://3.basecampapi.com/3780660/integrations/TosWTx75RqD1iyfYRj9uyrvQ/buckets/11178459/chats/1634206987/lines

**Comment by rosa** [comment]
@hassanuos you don't have to make any changes to the `callback_url` received, you need to use that one directly, and POST the chat line there.
