### ISSUE TITLE
Unread Pings and Heys (Notifications)

### ISSUE THREAD

**Issue by ThijmenDF** [basecamp/bc3-api#308]
Hi!

The company I work for use Basecamp for pretty much everything. Sharing files, posting messages, keeping track of to-do's and so on. I've been tasked with showing a personalized 'unread notifications' counter on our dashboard (which exists outside of Basecamp itself).

Unfortionately it would seem this feature doesn't exist? At least, I can't find any documentation about it.

I did find an previous issue #195 where a similar question was asked. Back then, the answer was no, but that was answered 3 years ago now.

Has there been any change of plans regarding this feature?

Thanks in advance.
Thijmen

**Comment by rosa** [comment]
Hey @ThijmenDF! I'm very sorry but no change of plans 😞 The feature still doesn't exist and it's really unlikely we'll add it to the API in the future.

**Comment by rosa** [comment]
Thanks to you! 🙏 ❤️  Have a great day too!
