### ISSUE TITLE
How to get list of completed todos

### ISSUE THREAD

**Issue by rajaarsalan25** [basecamp/bc3-api#310]
Hi, 
I am using the following URL to get the completed todos, but it only returns the todos that are not completed.

https://3.basecampapi.com/id/buckets/id/todolists/id/todos.json?page=1?completed=true

**Comment by rosa** [comment]
Hey @rajaarsalan25, sorry for the delay in replying! Are you still experiencing this problem? If so, could you provide the value of `X-Request-Id` you get in the response? That'll be useful for us to locate your request in our logs and troubleshoot.
