### ISSUE TITLE
question: What does basecamp v4 mean for this repo and the documentation it contains?

### ISSUE THREAD

**Issue by thisislawatts** [basecamp/bc3-api#313]
We have built a few in house integrations based on the tool and keen to understand what we may need to change over the coming months. Are there any breaking changes upcoming around the API surface/behaviour with the new Basecamp version. 

Hope the release is going well for the team :sparkles:

**Comment by rvanbaalen** [comment]
As an add-on developer for Basecamp, I'm very keen to know about the Basecamp 4 API as well. 

Back when Basecamp 3 was released, the API seemed like an afterthought as it wasn't available at the time of BC3 release. I hope with BC4 that this isn't the case and devs get enough time to adapt/update their addons for Basecamp.

**Comment by rosa** [comment]
Hey @thisislawatts and @rvanbaalen! Sorry for the late reply, I missed this. 

We haven't made specific plans for the API related to BC4 when it comes to new features. About breaking changes, we'll try to avoid these and not introduce any unless it's absolutely necessary. If that was the case, we'll notify integration owners with enough time to prepare for these.
