### ISSUE TITLE
Previous due dates in rescheduled to-dos not accessible

### ISSUE THREAD

**Issue by nachocab** [basecamp/bc3-api#317]
I can't figure out how to access this information through the API:

![image](https://user-images.githubusercontent.com/27538/141111739-5c9c6d10-c62a-4b91-a89a-efbb115ee4bf.png)

I can get the latest `due_on` on the Todo, I can see all the 'rescheduled' events associated with that Todo, but it doesn't include a `due_on` field and the Comments associated with the Todo don't include reschedulings.

Where is this information being stored?

**Comment by nachocab** [comment]
Hi @rosa 

Sorry to bother you, but I'm a bit stuck on this. If you had a quick pointer, it would be really helpful

**Comment by rosa** [comment]
Oh, hey @nachocab, so sorry I missed this! 
We don't return specific event details on [the events API](https://github.com/basecamp/bc3-api/blob/master/sections/events.md#events), I'm afraid, so there's no way of getting previous dates like you need 😞 We don't have plans to add these right now. The only alternative I can think of, if you need to get that history, is to [have a webhook](https://github.com/basecamp/bc3-api/blob/master/sections/webhooks.md#webhooks) that notifies you on to-do events. Then you can store the due-on date from creation and on each update.
