### ISSUE TITLE
Feature request: add user as subscriber and notify him.

### ISSUE THREAD

**Issue by sdapkus** [basecamp/bc3-api#319]
Via api it is possible to edit subscribers list, but it is not possible to notify users, if they were added to subscribers list. It is possible to do this from web interface:
![image](https://user-images.githubusercontent.com/58326108/148245460-9ed2e14b-2500-4737-b0d2-469cb3903d3b.png)

**Comment by rosa** [comment]
Hey @sdapkus, thanks for sending this suggestion! We don't have plans to implement this in the near future, but we'll have it into account if we start a round of improvements for the API.
