### ISSUE TITLE
How to get "ACCESS_TOKEN"

### ISSUE THREAD

**Issue by hitinfotech** [basecamp/bc3-api#321]
How we can get ACCESS_TOKEN from login credential ?

**Comment by mike-weiner** [comment]
I would start with the OAuth white paper to get a fundamental understanding of how the ACCESS_TOKEN works with OAuth. That can be found here: https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-05

The Basecamp API also has a good description on how to authenticate with OAuth: https://github.com/basecamp/api/blob/master/sections/authentication.md#oauth-2

I have written a small Python script to demo how to do your own OAuth authentication without an outside library: https://gist.github.com/mike-weiner/0da5c20de450f73263122fdf1db61f26
