### ISSUE TITLE
Is it possible to create a "Door" via the Basecamp API?

### ISSUE THREAD

**Issue by rvanbaalen** [basecamp/bc3-api#322]
I noticed Basecamp now has "Doors". Is there a way, as a third party Basecamp service, to be added to that short list or to create our own "Door" (including brand icon) via the API?

**Comment by rosa** [comment]
Hey @rvanbaalen, I'm afraid not! We haven't built support for this in the API and currently have no plans to add it. More about this decision [here](https://github.com/basecamp/api#realistic-expectations).

**Comment by rvanbaalen** [comment]
Oh that's unfortunate! We're getting a lot of requests from our users if there's some shortcut within the Basecamp interface to our planning software. We contemplated creating a browser plugin for this purpose but the Doors feature is way more elegant!

I guess we're back to the browser plugin drawing board.
