### ISSUE TITLE
Todolists position property does not update

### ISSUE THREAD

**Issue by rvanbaalen** [basecamp/bc3-api#323]
If I have two Todo lists in Basecamp:

- List one {position: 1}
- List two {position: 2}

And I sort the todo lists in Basecamp:

- List two {position: 1}
- List one {position: 2}

This update is not reflected in the API results. When I fetch the Todolists, the API data still shows position 1 for List one and position 2 for List two.

**Comment by rosa** [comment]
Hey @rvanbaalen, that's very odd and sounds like a bug. Could you [get in touch with our support team](https://basecamp.com/support) and include more information so we can debug this? Eg. full URLs for the project and to-do lists, and X-Request-Id returned in the API response.

**Comment by rvanbaalen** [comment]
I'll do that, Rosa

**Comment by jeremy** [comment]
(Closing out, moved to support discussion!)
