### ISSUE TITLE
Is there a way to filter Recordings by date

### ISSUE THREAD

**Issue by rvanbaalen** [basecamp/bc3-api#324]
Right now, when I use the Recordings endpoint to collectively retrieve a bunch of Todos from multiple projects, it loads all the tasks it can find.

Is there a parameter to limit the results to a certain timeframe? For instance using `start_date=01-01-2021` would ignore all todos from before 2021, resulting in less paginated API calls. Your API happy, our back-end happy :-)

**Comment by lewispb** [comment]
There isn't a way to do that, sorry @rvanbaalen.

Depending on your use case you can sort by `created_at` or `updated_at` in descending order, which may help. Once you detect a recording on your target datetime you can safely assume there'll be no more prior to that datetime.

**Comment by rvanbaalen** [comment]
Oh that's unfortunate! The sorting thing might help indeed. 

Being able to filter the query would really benefit both parties; less incoming API requests for Basecamp and faster response times for integrations. Now, we sometimes hit the mac execution time limits of our servers because we have to load data that we're not using.
