### ISSUE TITLE
Facilitating backup

### ISSUE THREAD

**Issue by Tanglo** [basecamp/bc3-api#328]
You are already way ahead of most SaaS products by letting me download my data.  However, there is no mechanism for me to automate this and turn it into a good backup that helps me secure my business data.

I don't like putting the security of my business in the hands of a manual backup process.

Could you please add to the API a function to let me execute the functionality of the download account button that is inside the Basecamp UI?  Then your users could write their own integration to backup Basecamp automatically to a place of their choosing.

**Comment by jeremy** [comment]
Great suggestion @Tanglo. I've relayed it to the product team.

While we do not have _official_ API for this, this capability is _accessible_ via the API. Make a POST request to /accounts/exports.json using your OAuth token and a JSON body with the IDs of the projects to export:
```json
{ "bucket_ids": [ 727173, 277163, 32333, etc… ] }
```
That'll respond with a 302 redirect to the pending export URL. When the export is complete, you'll receive and email and need to download it within 3 days.
