### ISSUE TITLE
Get all ToDo item IDs from a project?

### ISSUE THREAD

**Issue by creativearc-paul** [basecamp/bc3-api#329]
In the BC2 API, I was able to do this:

curl -s -u user:password -H 'User-Agent: MyScripts (my@email.com)' https://basecamp.com/CompanyID/api/v1/projects/ProjectID/todos.json

This would give me the individual ToDos (no matter the list) from a project.

Is this an option with the Basecamp 3 API?

**Comment by jorgemanrubia** [comment]
There is no direct option for this in BC3, sorry. You could achieve this through several calls through these paginated resources:

1. [Fetch projects](https://github.com/basecamp/bc3-api/blob/master/sections/projects.md#get-a-project)
2. For each project, grab the [todosets](https://github.com/basecamp/bc3-api/blob/master/sections/todosets.md).
3. For each todo set, fetch the [todolists](https://github.com/basecamp/bc3-api/blob/master/sections/todolists.md).
4. For each todolist, fetch the [todos](https://github.com/basecamp/bc3-api/blob/master/sections/todos.md).
