### ISSUE TITLE
Get All Completed todo from basecamp list 

### ISSUE THREAD

**Issue by RajaArsalan** [basecamp/bc3-api#330]
I am trying to get all the completed todo from one of the list of basecamp, but I am only receiving 15 completed todos. The Endpoint I am using is below.

ENDPOINT : https://3.basecampapi.com/(PROJID)/buckets/(BUKETID)/todolists/(LISTID)/todos.json?completed=true

I have also tried using a page no at the end of endpoint but it didn't help as well.

FAILED TRY ENDPOINT : https://3.basecampapi.com/(PROJID)/buckets/(BUKETID)/todolists/(LISTID)/todos.json?completed=true?page=1

FAILED TRY ENDPOINT 2 : https://3.basecampapi.com/(PROJID)/buckets/(BUKETID)/todolists/(LISTID)/todos.json?page=1?completed=true

**Comment by lifo** [comment]
This may be due to poorly formatted URL. It should be https://3.basecampapi.com/(PROJID)/buckets/(BUKETID)/todolists/(LISTID)/todos.json?page=1&completed=true
