### ISSUE TITLE
Get All Projects. Default listing quantity?

### ISSUE THREAD

**Issue by creativearc-paul** [basecamp/bc3-api#331]
How many projects are returned by default?

https://github.com/basecamp/bc3-api/blob/master/sections/projects.md#get-projects

**Comment by rosa** [comment]
Hey @creativearc-paul, the `GET /projects` endpoint returns a paginated list of projects, which, in general will contain 15 results on page 1, 30 on page 2, 50 on 3, and then 100 on 4 and above. However, don't rely on these numbers and instead use the `Link` header to fetch the following page. You can read more about it [here](https://github.com/basecamp/bc3-api/blob/master/README.md#pagination).
