### ISSUE TITLE
Include "category" in the "get messages" endpoint

### ISSUE THREAD

**Issue by ptkato** [basecamp/bc3-api#332]
Right now, my use case requires me checking on the category for the messages that comes through the "get messages" endpoint, however given the fact that as of now the messages that come through there don't have the "category" attached to them, I need to dispatch another request to get the full message contents.

Basically that means that if I end up gathering 1000 messages through the "get messages" endpoint, I would need to send 1000 requests to fetch each message's category. That's not ideal, given the limitation of 50 requests per 10 seconds (which is reasonable), it takes a long time; nonetheless it is a waste of bandwidth.

What I am requesting is that the "category" is added to the messages sent through the "get messages" endpoint (`/buckets/<project_id>/message_boards/<message_board_id>/messages.json`).

**Comment by packagethief** [comment]
Hey @ptkato, sorry for the late reply. I just double checked and this is already the case. The JSON for messages includes a `category` key that contains the `id`, `name`, and `icon` of the category. Here's an example from the test I just performed:

```json
"content": "...",
"category": {
  "id": 57428511,
  "name": "Announcement",
  "icon": "📢"
},
```
