### ISSUE TITLE
Add images / attachments when creating new items (todos etc)

### ISSUE THREAD

**Issue by AnActualFridge** [basecamp/bc3-api#333]
I might be missing something, but I can't see a way to add an image or attachment in the request to make a new to-do or schedule event etc.

If this functionality already exists what would a curl request look like to create a to-do and include an image in the description / body of the to-do?

**Comment by jeremy** [comment]
Here's how! https://github.com/basecamp/bc3-api/blob/3f71ee57b278be6e71f51488c71197f600395a2b/sections/rich_text.md#inserting-an-image-or-file-attachment
