### ISSUE TITLE
Set repeat in "Create a to-do" end point

### ISSUE THREAD

**Issue by anlinas** [basecamp/bc3-api#334]
When creating a to-do is there a way to make it a repeating to-do? 

If not I'd like to request the applicable parameters be added to the "Create a to-do" end point. 

Thanks!

**Comment by jeremy** [comment]
Thanks for your request, @anlinas. We haven't exposed an official API for this yet; however, in the meantime you can inspect the parameters used in the browser to see how to set up a repetition schedule.

To create or update the repetition schedule for a to-do, provide `repetition_schedule_attributes` in the to-do JSON body:
```json
{
  "other": "to-do attributes…",

  "repetition_schedule_attributes": {
    "repeats_until": "e.g. 2023-07-22, optional"
    "schedule": {
      "frequency": "every_day|every_week|every_other_week|every_year|every_weekday|every_month|every_day_of_month"
      "days": [ 3, 4 ] # numeric day-of-week/month; optional, depends on frequency
      "week_instance": 2 # numeric week-of-month; optional, depends on frequency
    }
  }
}
```

The `repetition_schedule` is included in to-do JSON, so you can play with a to-do repetition schedule in the browser then fetch it via the API and see how the schedule is configured.

Note that invalid schedules are cleared, so if it seems like your repetition schedule attributes aren't "sticking," check the to-do JSON response. If there's no repetition_schedule, then it was invalid.

Best of luck with your integration!
