### ISSUE TITLE
Getting a to-do list responds with a 404 if the to-do set ID is included in the URL

### ISSUE THREAD

**Issue by johnlpollard** [basecamp/bc3-api#43]
The documentation states "Nesting under the to-do set resource is not necessary for this endpoint" but it actually breaks if it is included. Can you allow for the to-do set ID to be included as well? 

200 - GET /buckets/1/todosets/3/todolists.json
200 - GET /buckets/1/todolists/2.json
404 - GET /buckets/1/todosets/3/todolists/2.json

**Comment by javan** [comment]
Thanks for pointing that out. The URL structure is required, not optional, so I've removed those notes from the docs.

**Comment by johnlpollard** [comment]
Ok thanks, I wasn't sure. We had an issue with ActiveResource and parent_resources that brought this to light.

**Comment by javan** [comment]
Cool. Good to know someone else uses ActiveResource besides us. ;)
