### ISSUE TITLE
Feature Request: Webhooks

### ISSUE THREAD

**Issue by t1mmen** [basecamp/bc3-api#44]
This appeared on the roadmap (https://github.com/basecamp/bc3-api/issues/1), but didn't seem to make it into the public release.

Any concrete plans for this?

References:
https://github.com/basecamp/bcx-api/issues/170
https://twitter.com/jasonfried/status/646744974642540544

**Comment by javan** [comment]
Concrete-ish. We have the plumbing in place, but still need to work out the UI and consider security implications. I don't have an ETA, and will post an update here when there is one.

In the meantime, check out the [Recordings](https://github.com/basecamp/bc3-api/blob/master/sections/recordings.md) API if you haven't already. It's your best option for fetching "what's new".

**Comment by joeldrapper** [comment]
I'm building a bot that should respond to certain things in Campfire chats. Webhooks for Campfires would be really handy!

**Comment by yuanbohan** [comment]
Wait for this, We will move to Basecamp3 from Trello when this feature done.

**Comment by noctivityinc** [comment]
+1 - really need this to make BC3 a viable solution

**Comment by dhh** [comment]
We're going to roll out a webhooks API very shortly. The system is not yet deployed, but there's a preliminary guide to its use available in this PR: https://github.com/basecamp/bc3-api/blob/8f54c7688da27cc4ee126ce2c82c85f919a70462/sections/webhooks.md.

You can comment on that PR directly with thoughts.

Thanks!

**Comment by dhh** [comment]
Note, we're building a separate campfire chat bot API. So that's not part of this webhook API.

**Comment by dhh** [comment]
This is now live!

**Comment by noctivityinc** [comment]
Excellent.  Thanks.



On August 26, 2016 at 3:41:58 PM, David Heinemeier Hansson (
notifications@github.com) wrote:

Closed #44 <https://github.com/basecamp/bc3-api/issues/44>.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/basecamp/bc3-api/issues/44#event-769362701>, or mute
the thread

**Comment by miklb** [comment]
> Note, we're building a separate campfire chat bot API. So that's not part of this webhook API.

@dhh is there an issue or branch that could be tracked/followed to keep up on bot API progress? We've been quite anxious for this.

**Comment by dhh** [comment]
We will be announcing this next week. Hang tight!

**Comment by javan** [comment]
Chatbots are live! 🎉

https://github.com/basecamp/bc3-api/blob/master/sections/chatbots.md#chatbots
https://m.signalvnoise.com/new-in-basecamp-3-chatbots-8526618c0c7d

**Comment by miklb** [comment]
sweet, looking forward to see can adapt to my existing hubot (assuming no one has already done that…)
