### ISSUE TITLE
Archived and Trashed Basecamps not available

### ISSUE THREAD

**Issue by tcannonfodder** [basecamp/bc3-api#45]
Steps to reproduce:

1. Create a new Basecamp
2. Call `/projects.json`
3. Observe the Basecamp is present
1. Archive the Basecamp
2. Call `/projects/archive.json`
3. Observe the response is `204 No Content`, and no Basecamp is present

The same steps apply to trashing a Basecamp, except `/projects/trash.json` is used

**Comment by dirk** [comment]
Also note that the [current API documentation](https://github.com/basecamp/bc3-api/blob/5358b71cb2d9afef4c2baeaa6be7edfa1f34ab83/sections/basecamps.md#get-archived-basecamps) (as of 19 July 2016) states that archived and trashed basecamps should be available at those paths.

**Comment by javan** [comment]
I'm on it

**Comment by javan** [comment]
Thanks for the report! This is fixed now. Note the URL changes:
* `/projects/archive.json` → `/projects.json?status=archived`
* `/projects/trash.json` → `/projects.json?status=trashed`

Let us know if you find more material for our ["How Not to Release an API"](https://twitter.com/tcannonfodder/status/758370855600680961) playbook.
