### ISSUE TITLE
Attachment to be linked to todo entry

### ISSUE THREAD

**Issue by skoshkarev** [basecamp/bc3-api#47]
Is there any way to upload any file to a certain todo (during create or update procedures)?

**Comment by sstephenson** [comment]
First, [create an Attachment](https://github.com/basecamp/bc3-api/blob/master/sections/attachments.md#create-an-attachment) for the file. You will receive an `attachable_sgid` value in the JSON response:

```json
{"attachable_sgid":"123xyz..."}
```

Next, build a [rich text HTML string](https://github.com/basecamp/bc3-api/blob/master/sections/rich_text.md#inserting-an-image-or-file-attachment) containing the attachment. The simplest version looks like this:

```html
<bc-attachment sgid="123xyz..."></bc-attachment>
```

The `sgid` attribute must match the `attachable_sgid` you receive when you upload your file. If you want, you can put additional text around the attachment, or include multiple attachments.

Finally, [create the Todo](https://github.com/basecamp/bc3-api/blob/master/sections/todos.md#create-a-to-do) with the `description` field set to the rich text HTML string.
