### ISSUE TITLE
Where's my access token?

### ISSUE THREAD

**Issue by brianjdoherty** [basecamp/bc3-api#48]
Sorry if this is a dumb question.  I can't find my access token.  In Highrise, I have an API token, but I don't find anything like that in BC3.  I saw in another issue here that a BC2 token would work, but I don't see that in my BC2 account either!  The Highrise token doesn't work.  Am I missing something?  Thanks.

**Comment by georgeclaghorn** [comment]
Hi @brianjdoherty! You aren't missing anything. The BC2 and BC3 APIs do not use API tokens for authentication. BC3 only supports [authentication via OAuth 2](https://github.com/basecamp/api/blob/master/sections/authentication.md#oauth-2).

**Comment by brianjdoherty** [comment]
I'm sure you have good reasons for going in this direction, but I can't imagine simplicity was one of them.  I'm not a real programmer, I just want to do some simple integration between BC3 and an internal system here.  Going around in circles now, can't get it to work.  Got client_id and client_secret, but baffled by next steps.  Tried ruby oauth gem, but it's throwing errors.  Older versions of your API had access tokens that just worked without turning into a full-time job.  Bummer.

**Comment by jeremy** [comment]
For sure, @brianjdoherty. Our primary case for API access is a user _delegating_ authorization to a third-party app. We're aiming to support your case too, since it's super simple and convenient for first-party usage. You'd still use OAuth2 (by passing an Authorization header with your API requests), but you could generate a token manually in a dev-tools area on your account. Stay tuned.

In the meantime, perhaps you can plug in using Zapier's [Basecamp 3 integration](https://zapier.com/zapbook/basecamp3/). Check it out!

**Comment by brianjdoherty** [comment]
OK, I understand.  I’ll check out Zapier’s BC3 integration.  Looking forward to the dev-tools idea.  Thanks! 


On August 19, 2016 at 12:12:50 PM, Jeremy Daer (notifications@github.com) wrote:

For sure, @brianjdoherty. Our primary case for API access is a user delegating authorization to a third-party app. We're aiming to support your case too, since it's super simple and convenient for first-party usage. You'd still use OAuth2 (by passing an Authorization header with your API requests), but you could generate a token manually in a dev-tools area on your account. Stay tuned.

In the meantime, perhaps you can plug in using Zapier's Basecamp 3 integration. Check it out!

**Comment by mrwboilers** [comment]
I'd very much like a simpler method of authentication as well. I just use the API to generate weekly activity reports that get sent to management. This works well in BC2, but just seems completely impractical with the way BC3 requires authentication to be done. I haven't found a way to make it a fully automated process. I just need a report to be generated and emailed. Like the other user above, I'm not a developer. In playing around with OAuth2, it seemed like user intervention was needed every time a call was made to the API. It required using a browser and clicking a link to authorize access. Obviously, this is unacceptable for sending automated reports, as it just isn't possible to actually make it fully automated. I've tried a few different Python OAuth2 modules.

I just took a look at zapier, but that doesn't seem to have the functionality that I'm looking for. I've engaged their support though, so maybe I'm wrong and I just haven't found it yet.

Alternatively, for my needs I wouldn't even need to use the API at all if you offered a simple reporting tool. I don't need much, just a list of all to-dos that were completed in the last 7 days as well as all new to-dos added in the last 7 days. Maybe I'm off base, but I'd guess that reporting ability would be welcomed by a lot of basecamp users! 

I either need a workable API solution, or a reporting tool, or my company will never be able to move from basecamp 2 to 3.

**Comment by tonypartridge** [comment]
Has there be any update to a workable API which doesn't require individual authorization? 

Our scenario is we need to bulk update all outstanding tasks within a project when the client is delaying so we are not left with tons of overdue tasks. I cannot see a way to handle this easily, your API using OAuth2 seems very complicated. I just want to simple generate an Auth Token from my account to fetch all projects, allow the end user to select a project and set a time frame to increase the todo's by. Fairly simple with many other task management API's, but not with BC3 from what I can tel..

**Comment by danielwdunn** [comment]
Any updates to the question regarding a simpler method of authentication that can be automated for reporting purposes?

**Comment by danielhaan** [comment]
Also curious about an update. I'm trying to automate the authentication process for a bot with python, but I am stuck.

**Comment by tonypartridge** [comment]
We gave up, just moved to ActiveCollab instead.

**Comment by danielhaan** [comment]
# Solution:
Hey everyone! I found a solution that works very smooth and only requires a one-time annoying setup:

**1st step**
Go and create your application for basecamp at [integrate.37signals.com](https://integrate.37signals.com). You can set ANY redirect url, it doesn't matter. Keep the client_id, client_secret and redirect url ready for following steps.

**2nd step**
Open this url in a browser with dev-tools (I did it in Chrome):
` https://launchpad.37signals.com/authorization/new?type=web_server&client_id=your-client-id&redirect_uri=your-redirect-uri
`

**3rd step**
Before you do ANYTHING on the page, open up the Network tab in the inspection tool (dev-tool?). Now continue with the process in the browser by logging in and granting the application access (the user you login with will be the one used by your bot/backend scripts that call the API).

When you land on your redirect page, this step is done.

**4th step**
Look in the network tab and notice, that when you were redirected to your redirect url, there was added a query string parameter named **code** which disappears immediately in the actual browser address bar. It will look something like `http://your-redirect-url.com/?code=f34c1ab2`
See screenshot [here](https://i.imgur.com/tUcmQpO.png)

**5th step**
Copy paste that code and perform steps 4 and forward from the basecamp authentication guide at [this section](https://github.com/basecamp/api/blob/master/sections/authentication.md#oauth-2-from-scratch).

What you end up with is 2 tokens: An access token and a refresh token. Your access token lasts for 2 weeks, and whenever it expires, you simply perform this request to get a new access token:
`POST https://launchpad.37signals.com/authorization/token?type=refresh&refresh_token=your-current-refresh-token&client_id=your-client-id&redirect_uri=your-redirect-uri&client_secret=your-client-secret
`

**Final step**
Use this access token in all your sweet API calls from whatever server side code you may need it for and make sure to check for 401 responses (which you should use to perform the refresh request and get a new token).

The refresh token never expires unless it is added to a blacklist, so unless you abuse it somehow, that won't happen.

Best of luck everyone!

**Comment by bidoule** [comment]
@jeremy Are you still "aiming to support [this] case" ? I didn't find any dev-tools area in my account. Sad to see people giving up basecamp because this feature is lacking (and existed with previous version of the API). If I had known that, I wouldn't have migrate to v3.

**Comment by TechnoDeGama** [comment]
I followed danielhaan's instructions and was able to make my first connection to Basecamp. (thanks so much).

However when I follow the instructions for the refresh using

What you end up with is 2 tokens: An access token and a refresh token. Your access token lasts for 2 weeks, and whenever it expires, you simply perform this request to get a new access token:
POST https://launchpad.37signals.com/authorization/token?type=refresh&refresh_token=your-current-refresh-token&client_id=your-client-id&redirect_uri=your-redirect-uri&client_secret=your-client-secret

this step it tells me unauthorized. Is the refresh token the string after the hyphens from my first authorization?

**Comment by jeremy** [comment]
@bidoule, @TechnoDeGama: I recommend you use an OAuth2 client library that'll automate this process for you! Most languages have an existing library you can lean on, or peruse to see how to implement your own own solution.

Here's a great list to start with: https://oauth.net/code/#client-libraries

**Comment by TechnoDeGama** [comment]
Thank you, but this is not helpful. Could you answer this question:

Is the refresh token the string after the hyphens from my first authorization?

**Comment by jeremy** [comment]
@TechnoDeGama, no it isn't.

When you POST your verification code at step 4 in the [OAuth 2 from scratch](https://github.com/basecamp/api/blob/master/sections/authentication.md#oauth-2-from-scratch) guide, you'll receive a JSON response that contains both an `access_token` that you can use right away with our API and a `refresh_token` that you can securely store and use to request access tokens in the future without having the user re-authorize your app.

I mention the OAuth2 client libraries because this flow and implementation of it are fully complete and ready to use, so you can rely on others' work to bypass a lot of troubleshooting steps! 😊

**Comment by TechnoDeGama** [comment]
I got it- thanks for your help.

**Comment by bidoule** [comment]
@jeremy Many thanks for your answer. I wrongly thought that the refresh token was also expiring after some date.

> a refresh_token that you can securely store and use to request access tokens in the future without having the user re-authorize your app.

So I can store this refresh token, and start my cron-enabled script by requesting a new token using this refresh token? And there won't be any problems for requesting new tokens every 5 minutes? Or for two servers using two different access tokens at the same time?

**Comment by jeremy** [comment]
@bidoule Yes, yes, and yes. That's a fine strategy for a cron job. 👍

**Comment by vkathirvel** [comment]
I tried to use the refresh token to get a new access token before the original one expired. The resulting JSON has a new access token and expires date, but no new refresh token. Is the refresh token a one time issue? Or, am I not getting a refresh token as the original token is still active?

**Comment by rosa** [comment]
The original refresh token is still active, @vkathirvel! You can store that one securely and use it whenever you need to get a new access token, as you just did.

**Comment by vkathirvel** [comment]
Thanks @rosa That's good to know. So the refresh token is permanent.
To confirm about security, how does one go about terminating an original refresh token and getting a fresh refresh token?

**Comment by rosa** [comment]
@vkathirvel a refresh token will be invalidated if the user for whom the token was issued in the first place changes their credentials. Getting a new one requires going through the authorization flow again.

**Comment by vkathirvel** [comment]
Thanks @rosa

**Comment by vkathirvel** [comment]
One more question: I couldn't see anywhere on GitHub. What is the exact return message that comes back when the access token has expired? I'm unable to test and get this as my access_token has two weeks left on it.
{
"error": "?"
}

**Comment by rosa** [comment]
Oh, yes, of course! You should get an error like this:
```json
{
    "error": "OAuth token expired (old age). Refresh your token or acquire a new one at <a href=\"https://launchpad.37signals.com/authorization/new\">https://launchpad.37signals.com/authorization/new</a>"
}
```

**Comment by defionscode** [comment]
PSA for anyone that wants to script/etc against basecamp's API. I made a project that lets you generate oauth tokens on demand. https://github.com/zibasec/basecamp-token-broker

**Comment by broskees** [comment]
So I was able to get the access token and such by following your steps fairly easily - but what about the "Account ID" - I see no documentation at all on obtaining that..

**Comment by broskees** [comment]
Figured it out.
