### ISSUE TITLE
Update Schedule Entry

### ISSUE THREAD

**Issue by chait12** [basecamp/bc3-api#49]
Hey,
I'm trying to connect Basecamp 3 by API integration docs.
Update schedule entry endpoint is not working as expected.
My input is proper but things are not working. Please help me.
Getting 500 body Response. Below is the response which I'm getting.

<body>
       <div class="dialog">
           <div class="innercol">
               <h1>Oops, something isn&rsquo;t working.</h1>
               <h2>This is our fault, not yours. We&rsquo;re sorry.</h2>
               <p>It&rsquo;s likely this is a temporary glitch that will be fixed within a few minutes. If you continue to see this error:</p>
               <ul>
                   <li>
                       <a href="http://status.basecamp.com/">Check our status site for an update</a>
                   </li>
                   <li>
                       <a href="http://help.37signals.com/tickets/new">Report this problem to support</a>
                   </ul>
               </div>
           </div>
           <p class="back">
               <a href="javascript:window.history.back();">&larr; Back to previous page</a>
           </p>
       </body>

**Comment by georgeclaghorn** [comment]
Can you share an example of a request you made that failed? What endpoint did you hit and what parameters did you send?

**Comment by javan** [comment]
If you're still having trouble, please send us the `X-Request-Id` response header for your request. We can use it to find the logs and see what went wrong.
