### ISSUE TITLE
Streaming or WebSocket API for Camfires

### ISSUE THREAD

**Issue by JLarky** [basecamp/bc3-api#51]
I see that you have added webhooks api recently https://github.com/basecamp/bc3-api/issues/44#issuecomment-242832243 but I'm looking for something similar to [streaming api](https://github.com/basecamp/campfire-api/blob/master/sections/streaming.md) in camfire.

Actually I think much better solution would be if websocket api that web ui uses was accessible from api, but it's probably very client specific.

**Comment by JLarky** [comment]
I noticed this in https://github.com/basecamp/bc3-api/blob/master/sections/webhooks.md

> (Note that chat isn't amongst the options. We will be providing a chat bot API separately soon.)

So I guess answer to my question is that this part of API is coming and we have to wait for it :)

**Comment by javan** [comment]
That's correct. It's unlikely that we'll add a streaming API any time soon (or ever), but we definitely plan to add some form of chat bot API. Stay tuned! :)

**Comment by JLarky** [comment]
@javan chat bot API as in command/reply or real-time chat api? So basically does this api allow to send messages/attachments to chat and read all of it's messages or it's just "ping/pong" kind of thing?

**Comment by dhh** [comment]
First iteration we are preparing is just ping/pong. You register a command URL, chatters can send text commands to that via POST, whatever the command replies with is instantly inserted into the chat. 

What use case do you have for the realtime streaming?

**Comment by JLarky** [comment]
@dhh I'm working at https://sameroom.io (relevant document is https://sameroom.io/developers) we already support Campfire, but not Basecamp 3.

**Comment by dhh** [comment]
Gotcha, yeah. Would like to get to that use case at some point, but our
first objective is to make it possible for people to make request/response
bots.
