### ISSUE TITLE
Get the completion details for todos

### ISSUE THREAD

**Issue by mdelbo** [basecamp/bc3-api#52]
ie. the date and time of completion and the user who completed the todo.

**Comment by javan** [comment]
You can get those details and more from the [Events endpoint](https://github.com/basecamp/bc3-api/blob/master/sections/events.md#get-events). Look for a `completed` action.

**Comment by mdelbo** [comment]
Thanks. How do I associate it back to a particular todo?

**Comment by javan** [comment]
The event endpoint for `/buckets/1/todos/2.json` would be `/buckets/1/recordings/2/events.json`.

**Comment by jbaiza** [comment]
Hi, 
this approach will create very large amount of unnecessary API requests when bulk import is done (in BC2 REST API there was field completed_at at todo level). 
Let's do simple calculation - Basecamp contains one list with 1000 completed todos. We will need 20 requests (50 per page) to get all todo data. To get the date and time of completion we will need another 1000 requests.
So todo data requests (not calculating net speed, etc) will fit into 10 second period. To get the date and time of completion we will need another 200 seconds (You can perform up to 50 requests per 10-second period).

**Comment by jbaiza** [comment]
Hi,
we tried to get necessary data from the Events endpoint, but it was very slow. It would be very very good to get at least completed_at date and time field together with Todo itself.
@javan - could you add this field to the [To-dos endpoint](https://github.com/basecamp/bc3-api/blob/master/sections/todos.md#to-dos)?

**Comment by javan** [comment]
Done! Completed to-dos now have `completion` data. See the [Get a to-do example](https://github.com/basecamp/bc3-api/blob/master/sections/todos.md#get-a-to-do).

**Comment by jbaiza** [comment]
Thank you, works great!

**Comment by foxontherock** [comment]
So I suppose that the "completion_url" we get in the todo is no longer needed?  Because, every time I try one of these, I get a 404.
e.g. https://3.basecampapi.com/xxx/buckets/yyy/todos/zzz/completion.json

**Comment by rosa** [comment]
@foxontherock that URL is used to complete/uncomplete a todo, via `POST` and `DELETE`. Are you trying it using `GET`? That might be why you are getting a 404.

**Comment by foxontherock** [comment]
@rosa Yes that's what I did, I tried all "xxx_url" parameters from todos to see what they return.
Talking about it, that's not the goal of that closed thread, but what about "bookmark_url"? 
Do I really need to call all of these to get responses like {"bookmarked": false || true}, on every todo, or is there a more efficient way?
