### ISSUE TITLE
Refresh token

### ISSUE THREAD

**Issue by tgwiazdowski** [basecamp/bc3-api#53]
Hi, 
when I try to use access_token I get info that it expired, and a text that I should refresh it or ask for new. I need to perform that with no user action, so I assume I should refresh it. 
But how can I refresh an expired token? What is the endpoint and parameters for that?

**Comment by jeremy** [comment]
Hey @tgwiazdowski – check out our [authentication guide](https://github.com/basecamp/api/blob/master/sections/authentication.md). Most OAuth 2 client libraries can handle this for you. You pass the refresh token to the token endpoint and it returns a new access token.

> Configure your OAuth 2 library with your client_id, client_secret, and redirect_uri. Tell it to use https://launchpad.37signals.com/authorization/new to request authorization and https://launchpad.37signals.com/authorization/token to get access tokens.
