### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by tralston** [basecamp/bc3-api#54]
This has already been brought up in the previous API repo, bcx-api, but when will there be a CORS header for the API? I'd like to run it from javascript instead of a proxy. The old bug report said that it was in the works for a long time.

https://github.com/basecamp/bcx-api/issues/119

**Comment by dhh** [comment]
cc @jeremy

**Comment by RobertJGabriel** [comment]
bump

**Comment by rosa** [comment]
We don't have a concrete plan to add CORS support in the near future, so I'm closing this issue. Using a proxy server is the way to go for JavaScript apps.
