### ISSUE TITLE
Applauding

### ISSUE THREAD

**Issue by binfalse** [basecamp/bc3-api#56]
Is it possible for applications to applaud?

The web page apparently PUTs to `https://3.basecamp.com/XXXX/buckets/YYYY/recordings/ZZZZ/applauding` but this method doesn't seem to exist for applications using the bc3 API.. :(

**Comment by dhh** [comment]
We don't have that exposed right now, but that would be nice. Curious about the use case?

**Comment by openfinch** [comment]
Sorry to revive a dead issue, but I'd be interested in this feature - especially being able to aggregate a person's applause over the entire Organisation; for us a big part of pushing engagement would be to develop leaderboards to determine who is giving and receiving the most positive feedback throughout the team.

**Comment by xolan** [comment]
We'd like to be able to retrieve all applauds across everything and aggregate them. Use-case is basically the same as above.

**Comment by BuffaloJames** [comment]
I agree this would be a useful feature. We use the API to analyze engagement in Basecamp. Since there is no polling feature in Basecamp, we utilize the applause feature as a way to count support.

**Comment by rosa** [comment]
I'm closing this one since [we no longer have applause in Basecamp](https://m.signalvnoise.com/introducing-boosts-an-all-new-way-to-show-your-support-in-basecamp-fae325634998), feel free to open a new one about boosts if there is still a use case that applies!
