### ISSUE TITLE
Features: Using Attachment

### ISSUE THREAD

**Issue by nilesuan** [basecamp/bc3-api#58]
We need an api docs for using attachments. I know there's an upload attachment but we don't know what to do with the sgid.

**Comment by eileencodes** [comment]
Hey @nilesuan! Once you have an `attachable_sgid` you can attach it using the rich text endpoint here: https://github.com/basecamp/bc3-api/blob/ec7788ed6c98fcdf57b702e7963e5e2ad0b362e3/sections/rich_text.md#inserting-an-image-or-file-attachment

Attachments must be attached to something after you create the attachment itself. Attachments are supported anywhere in Basecamp 3 that we offer rich text like comments, messages, todo descriptions, etc.

I'll update the documentation to make that clearer as I can see how that wasn't clear.

**Comment by nilesuan** [comment]
Yeah found it just now thanks!
