### ISSUE TITLE
Features: Attachment on Campfire

### ISSUE THREAD

**Issue by nilesuan** [basecamp/bc3-api#60]
Client wants to attach images on api. Rich-Text doesn't seem to work there so would be great if this is supported.

**Comment by rosa** [comment]
@nilesuan you can achieve this by including the image URL in the content sent when [creating a new line from your chatbot](https://github.com/basecamp/bc3-api/blob/master/sections/chatbots.md#create-a-line). It'll be automatically fetched and display in the Campfire. You'll need to upload the image first somewhere, for example, as [Upload](https://github.com/basecamp/bc3-api/blob/master/sections/uploads.md#get-an-upload) in Basecamp, and then use the `app_download_url` in your line's content.
