### ISSUE TITLE
Get Recording by bucket id is not working

### ISSUE THREAD

**Issue by maulikvora** [basecamp/bc3-api#62]
https://github.com/basecamp/bc3-api/blob/master/sections/recordings.md#get-recordings

as shown in documentation, you can pass bucket ID or comma separated bucket ID list. 
`/projects/recordings.json?type=Message&bucket=1`
I am trying to do that but its giving '404 not found' error.

**Comment by javan** [comment]
It could be that the bucket ID you're requesting doesn't exist or the authenticated person doesn't have access to it. Are you able to access `/projects/1.json` successfully?

If that's not the case, send me the `X-Request-Id` header from the response and I'll take a look:

```bash 
$ curl -I -H "Authorization: Bearer $ACCESS_TOKEN" \
  https://3.basecampapi.com/$ACCOUNT_ID/projects/recordings.json?type=Message&bucket=1

HTTP/1.1 200 OK
...
X-Request-Id: f82d92ff-93e3-4bdd-bc4c-1b4a9bc0f7b2
```
