### ISSUE TITLE
Feature Request : Todos Completed ratio for a Person/Self

### ISSUE THREAD

**Issue by viraf** [basecamp/bc3-api#64]
We are currently using in our Basecamp 2 integration the following endpoint to get a count assigned todos of a person. /ACCOUNTID/api/v1/people/PERSONID/assigned_todos.json 

Can we please have something similar for Basecamp 3 api

**Comment by viraf** [comment]
Any updates on this ?

**Comment by rosa** [comment]
Hey @viraf, sorry for the silence over so many months! We should have replied much sooner 😓 
We aren't going to add this feature to the BC3 API, I'm afraid.

**Comment by viraf** [comment]
Thank you for the reply!
