### ISSUE TITLE
The request was aborted: Could not create SSL/TLS secure channel.

### ISSUE THREAD

**Issue by dsliter** [basecamp/bc3-api#67]
I've been able to authorize my app, and download all the authorization data from Basecamp, but when I try to get all the projects Visual Studio gives me this error: "The request was aborted: Could not create SSL/TLS secure channel". I am using the access_token and the user_agent when I request the projects. I'm using the https://3.basecampapi.com/$ACCOUNTID/projects.json to make the request. Any help on this would be appreciated.

Thanks
Dieter

**Comment by jeremy** [comment]
Assuming you're using C#/.NET, sounds like you're connecting with SSLv3 which is insecure and no longer supported. Give TLS 1.2 a shot: http://stackoverflow.com/questions/2859790/the-request-was-aborted-could-not-create-ssl-tls-secure-channel

**Comment by dsliter** [comment]
That fixed the issue.

Thank you
