### ISSUE TITLE
Retrieving ACCOUNT_ID from API

### ISSUE THREAD

**Issue by chribsen** [basecamp/bc3-api#71]
After authenticating with the Basecamp 3 API, how can I receive the `ACCOUNT_ID` for the logged in user? After searching through this repo, I can't find any documentation of this.

Personally, I was expecting the `ACCOUNT_ID` to be supplied together with the `access_token`. However, this seems not to be the case.

**Comment by javan** [comment]
Check out the [Get authorization](https://github.com/basecamp/api/blob/master/sections/authentication.md#get-authorization) section in our authentication guide.

**Comment by chribsen** [comment]
Thanks, that worked.
