### ISSUE TITLE
People removed from Basecamp are still present in dataset

### ISSUE THREAD

**Issue by joshmassey** [basecamp/bc3-api#75]
I manually removed a dummy account in Basecamp.  The account no longer shows up under the list of people that are on the account, but it does show up under the list of all people returned from the API.

**Comment by jeremy** [comment]
Indeed, we return all people that are on—or have been on—the account. We need to indicate whether the person was removed, too!

**Comment by Sieabah** [comment]
Looks like this is in the response for dead accounts:
`personable_type:"Tombstone"`
