### ISSUE TITLE
No way to relate teams to projects?

### ISSUE THREAD

**Issue by Sieabah** [basecamp/bc3-api#76]
Would it be possible to create some sort of method to relate teams and projects?

**Comment by joshmassey** [comment]
+1

**Comment by jeremy** [comment]
Would you share a bit more of your thinking, @Sieabah?

**Comment by Sieabah** [comment]
Currently we're trying to address the issue of having teams of people being on a project. There really isn't a way to know if there is a _team_ is on a project without going through all users on a project and figuring out if enough of the members match to have a solid answer if a team is on that project.

It was originally figured out by the creator and using their teams, it still wasn't that accurate and fell short if that person hopped teams. Currently we're just parsing out a hash **#teams <team number> <team number>** on project descriptions to figure out what teams are part of the project.

Hope this makes sense, I may misunderstand the reason for teams/projects if they can't be related.

**Comment by Sieabah** [comment]
There also isn't a direct api call to figure out what teams a person is in without querying all the teams.

**Comment by jeremy** [comment]
> having teams of people being on a project

Right. Teams are a place for people to work together. They're a kind of project, not a user group that may be assigned to to-dos, added to projects, etc.

**Comment by Sieabah** [comment]
My point is it _makes sense_ that they would be assigned these things and related to projects.

**Comment by jeremy** [comment]
Certainly :)
