### ISSUE TITLE
Webhook not being triggered when adding a Due Date to a To-Do

### ISSUE THREAD

**Issue by crash13override** [basecamp/bc3-api#77]
Not sure if this is intentional or if it's a bug, but I don't receive any Webhook notification if I add a Due Date to a To-Do that doesn't have one. If I change the name of the To-Do the Webhook is triggered correctly and I can retrieve the Due Date as well, but I would like to be notified also when I just change the Due Date.

Is this supposed to happen and it's not or is it meant to be this way?

Thanks a lot for your help!

**Comment by rodrigozooft** [comment]
Hello there!
Same issue here.
We are integrating [Octopull](https://octopull.us) with Basecamp to convert a to-do element into a task in Octopull, but nothing triggered when the user adds the Due Date.
Best,

**Comment by bwbuchanan** [comment]
The todo_content_changed webhook is also not triggered when the note is modified on the todo.

**Comment by rosa** [comment]
Hey! This should have been fixed already. When you add a due date to a todo, you should receive an event with a payload including:
```json
{
   "id":123456789,
   "kind":"todo_scheduled",
   "details":{  
      "notified_recipient_ids":[  
         789789789
      ]
   },


```
