### ISSUE TITLE
Webhook: Add Webhook ID to the notifications

### ISSUE THREAD

**Issue by crash13override** [basecamp/bc3-api#78]
It would be really useful to have an extra field in the payload of the Webhook notification that could tell me which Webhook ID is actually being triggered.

I need to know it because my SaaS app has many Basecamp users and each one have their own BC account linked. So for each one I create a Webhook to get notified about changes. But in case I have 2 users of my site that are linked with the same Basecamp account, then I will receive the Webhook twice (one for each user) and If I don't have a way to identify to which webhook belongs the notification, I will run my code twice and basically duplicate the actions all the time.

If I had the Webhook ID along with the notification, I would be able to apply the event just to the correct user and no duplication would happen.

Do you think this a too big feature to ask? Do you recommend any workaround until you eventually implement it?

thanks a lot!!!

**Comment by georgeclaghorn** [comment]
Could you avoid adding two webhooks to a single account, perhaps by tracking the IDs of accounts to which you've already added webhooks?

**Comment by crash13override** [comment]
In theory yes, but it would add a layer of complexity because when someone unlinks his Basecamp account I delete the webhooks that are associated with that user so I don't get notified anymore. If I have a "shared" webhook I would have to check if anyone else is still using it and if so avoid deleting it.
Nothing impossible to manage, but would be much easier and nicer to have a direct link to the corresponding Webhook.

Another solution I was thinking is to add an extra parameter to the webhook URL (something like http://mydomain.com/basecamp/callback?user_id=12345) So that I can get it read the user_id back when I get notified.

I think both solutions are a bit of a "hack" and since other big companies are doing it (Google for example), I thought I would give it a try and ask for the feature :)

Thanks again for your reply

**Comment by rosa** [comment]
Hey @crash13override, I think the first solution is the one that makes most sense. If you have two identical webhooks in the same account, buckets and events, both webhooks will fire exactly the same times, and traffic will be always duplicate. To me the correct solution seems to be adding only one webhook for an account and bucket, regardless of how many users you have there, and then delete the webhook only when there aren't any more users associated with it. It doesn't seem like a hack to me.
