### ISSUE TITLE
HTTP response from creating a message does not reflect BC3 API docs

### ISSUE THREAD

**Issue by chribsen** [basecamp/bc3-api#80]
Currently the API returns `HTTP 201 Created` with an empty response upon creating a new message from a chatbot. 

However, your API reads ([link](https://github.com/basecamp/bc3-api/blob/master/sections/messages.md#messages)):
_This endpoint will return `201 Created` **with the current JSON representation of the message** if the creation was a success. See the Get a message endpoint for more info on the payload._ 

Is this a documentation error or an HTTP response error?
FYI: I don't need this fixed, I just spotted the error.

**Comment by rosa** [comment]
@chribsen, sorry for the super late reply on this! I think this was a confusion between the API to be used by chatbots [to post lines in a Campfire](https://github.com/basecamp/bc3-api/blob/master/sections/chatbots.md#create-a-line), which returns `201 Created` and an empty response and it's correctly documented, and the API docs you linked, that refers to creating a message in a [message board](https://3.basecamp-help.com/article/46-message-board). In that case the docs reflect the reality too.
