### ISSUE TITLE
Need a way Change User to Client

### ISSUE THREAD

**Issue by dsliter** [basecamp/bc3-api#81]
I've looked through the site and the api. Is there a way to change a User to a Client preferably through the api. I have hundreds of account that have the "personable_type" set to "User" when they are actually "Clients". My assumption is this is how when a project is created Bc3 can differentiate between the people assigned to the project and the client section. Also when creating a new user and assigning them to the project is there a way to assign them as a client vrs a user?

**Comment by georgeclaghorn** [comment]
Hey @dsliter!

> Is there a way to change a User to a Client preferably through the api.

I'm afraid not. There's no way to change a user into a client via the app or the API. You'd have to remove the users and add new clients, though you can only do that in the app currently. Sorry about that!

> Also when creating a new user and assigning them to the project is there a way to assign them as a client vrs a user?

You can't do that via the API right now. We'll keep it in mind for a future update, but I can't make any promises. Sorry again!

**Comment by dsliter** [comment]
Thank you for your reply. I'd like to make a couple of suggestions for the API. 

1) A way to change users to clients. This may difficult with the way your database is set up but the amount of work to go through our currently 4000 users and figure out which ones are clients and which ones need to be users will take someone weeks to manually do the work.

2) A way to find out which clients are assigned to a basecamp. Currently you give us a way to download the Users unless I'm missing something in the documentation.

3) A way to create a Client or a User without having to create a project first. The only way I see through the documentation is through the "Create" property on the project. I have a data base of thousands of clients and would like to be able to use that to create a client when we get a project for that client. It just reduces that amount of double entry that we are currently doing.

4) From the previous post. When creating a project the ability to designate a user vrs a client.

I appreciate you help.

Thanks
Dieter Sliter
