### ISSUE TITLE
Completed ToDo's in a todo list not available

### ISSUE THREAD

**Issue by abhishek2desh** [basecamp/bc3-api#82]
hello, i' am working on a PHP wrapper for this API, i can see the completion ratio when requesting the todoList of a project.

but when i request the todo's from that particular list it will return empty.
I have observed  this phenomenon mostly in completed list.

**Comment by Sieabah** [comment]
In their forever genius of decreasing your API limit but increasing the required API calls you have to do a GET request to get both sets.

You can see a very rough attempt at an api driver [here](https://github.com/umbc-sga/iTracker/blob/master/app/Classes/Basecamp/BasecampAPI.php#L391)

**Comment by abhishek2desh** [comment]
Thanx @Sieabah for your reply, I reviewed your code.
I found my solution in you code on line # ~400
$list->todos = array_merge($this->get($list->todos_url), $this->get($list->todos_url.'?completed=true'));

i was missing the Query parameter "?completed=true" in my url.
i was not aware that base camp allows filtering of data based on attributes.
