### ISSUE TITLE
Allow inline styling on messages

### ISSUE THREAD

**Issue by chribsen** [basecamp/bc3-api#83]
It's currently not possible to use inline CSS styling on messages (posted from the API to the campfire or message board).
Are there any reasons for this? Without CSS (or any other styling possibilities except HTML) it's quite difficult to create a neatly looking message.

**Comment by jnthnclrk** [comment]
Yes, please! I'd like  to see more styling options as well.

**Comment by georgeclaghorn** [comment]
Can you give an example of the inline styles you'd use?

**Comment by jnthnclrk** [comment]
https://3.basecamp-static.com/assets/desktop-7d9d685a86d718080514fed00e7b589b83b9c9d9c574594234c37458def8cf46.css

**Comment by chribsen** [comment]
As an example, the following CSS properties would be nice to have some control over:

Text styling:
`font-size`, `color`, `text-align`
Image styling:
`border-radius`, `border-width`, `padding`, `margin`
Things like: `background-color` and `position` would also be nice. This would, as an example, allow me to add overlays to an image (e.g. overlaying a play button on a thumbnail image).

**Comment by georgeclaghorn** [comment]
Thanks, @chribsen. The [HTML tags we allow](https://github.com/basecamp/bc3-api/blob/master/sections/rich_text.md#allowed-html-tags) correspond with the formatting options we offer in Basecamp's web UI. We're likely not going to support any formatting in the API that we don't support on the web.
