### ISSUE TITLE
 More reliable way to track rate limits

### ISSUE THREAD

**Issue by urkle** [basecamp/bc3-api#84]
(moved here as posted in wrong repo originally..  ref: basecamp/bcx-api#212

Currently we are utilizing the X-RateLimit header that is sent back with each request to manage rate limits in our API usage. However that header provides a "until" as an ISO8601 timestamp of when the rate limit resets.. This is not very useful as it assumes that your system and our system are perfectly in sync with each other. A better value would be a delta # of seconds. e.g.

X-RateLimit: {"name":"API","period":10,"limit":50,"remaining":0,"until":"2016-01-01T12:00:20Z","until_seconds":3}

That way I do not need to have perfect time synchronization with your servers, as you provide a rounded-up number of seconds until the rate period resets. (thus I can easily sleep on that value and not worry about hitting a rate limit).

And no, sleeping the full 10 seconds every time isn't really a good choice, as right now we are sleeping for over 100 seconds every 5 minutes as it is!  

Ideally increasing the page size would greatly help things!

**Comment by raulpopadineti** [comment]
+1

**Comment by jeremy** [comment]
Done. The `Retry-After` response header now indicates the number of seconds remaining until the rate limit resets.

**Comment by urkle** [comment]
@jeremy thanks for the quick turn around.

**Comment by raulpopadineti** [comment]
@jeremy I don't see the remaining seconds attribute in the `Retry-After` header:

```
X-Ratelimit →{"name":"API","period":10,"limit":50,"remaining":46,"until":"2017-01-30T10:27:10Z"}
```

**Comment by urkle** [comment]
@jeremy we are using the X-Ratelimit header that is included with every response to analyze and determine when to wait.  As opposed to waiting until we receive a 429 and using the headers on that request.

**Comment by raulpopadineti** [comment]
@urkle oh yeah, my bad. I messed up the headers 😄

**Comment by jeremy** [comment]
I'm wary of encouraging using the informational header to manage client-side throttling. Could you share what kind of analysis you're doing? Ideally, the simple "wait <n> sec on 429 responses" rule would provide equivalent behavior.

(Also: the informational header already presents `limit` and `period`, theoretically sufficient to implement any limit/period throttle you wish.)

**Comment by urkle** [comment]
The thinking we are doing is checking the X-ratelimit to see when it gets down to 0 and then wait N seconds so we don't have to make a useless request that gets a 429 response.

**Comment by jeremy** [comment]
In that case, you could check when the `remaining` counter hits 0. This isn't concurrency-safe, though, if you're making requests in other threads/processes.

Hitting a 429 response is OK and encouraged by design. The upside of working hard to avoid it is pretty small. At best, you save the time for one API round trip. But if you have to wait Retry-After seconds after that API response anyway, there's no difference in aggregate performance.
