### ISSUE TITLE
How to get new access token using Refresh Token in Basecamp API ?

### ISSUE THREAD

**Issue by anupambaldi** [basecamp/bc3-api#85]
I successfully got access token using the following endpoint -- 
`https://launchpad.37signals.com/authorization/new`

The complete request is --
 
`https://launchpad.37signals.com/authorization/new?type=web_server&client_id='.$client_id.'&redirect_uri=https://www.mysite.com/basecamps/basecamp_access&state='.$user_id`.'

Now, I want to refresh my access token using refresh token after completing the 14 days of expiration period. I got refresh token in response of authorization process. Below is the complete request -- 
`$url = "https://launchpad.37signals.com/authorization/token";

		$params = array(
		  	'type' => 'refresh',
			'client_id' => $client_id,
			'client_secret' => $client_secret,
			'redirect_uri' => 'https://www.mysite.com/basecamps/basecamp_access',
			'refresh_token' => $refresh_token,
		);`

Here is the curl -- 

`foreach($params as $k => $v) 
 { 
	      $postData .= $k . "=".$v."&"; 
}

 $postData = rtrim($postData, '&');`
$ch = curl_init();
 
	   curl_setopt($ch,CURLOPT_URL,$url);
	   curl_setopt($ch,CURLOPT_RETURNTRANSFER,true);
	   curl_setopt($ch, CURLOPT_HTTPHEADER, array(
		'Content-Type:application/x-www-form-urlencoded'
		)); 
	   curl_setopt($ch, CURLOPT_POST, count($postData));
	   curl_setopt($ch, CURLOPT_POSTFIELDS, $postData);    
	   $output=curl_exec($ch);`

I am getting code expired error everytime when I run the above code. Please tell me where I am wrong or how can I get access token using refresh token in Basecamp 3 API.

**Comment by jeremy** [comment]
Looks like you'll need to URL-escape the params in your POST data. An unescaped refresh token may cause params parsing to fail, leading to a token that can't be parsed or verified.

**Comment by anupambaldi** [comment]
Hi Jeremy, 
Thank you for your quick response. I modified my code as you suggested. Here is my updated code -- 

      `$postData = rtrim($postData, '&');
	   $postData = urlencode($postData);
	   $ch = curl_init();  
	   curl_setopt($ch,CURLOPT_URL,$url);
	   curl_setopt($ch,CURLOPT_RETURNTRANSFER,true);`

I think it worked, but now I got the new error from API side which is as follows -- 

`{"error":"Missing client_id query parameter."}`

These are my POST params ($postdata in above code) -- 

`type%3Drefresh%26client_id%3Dc01c4bf684a131da8eggg40f7447452a7ed16265%26client_secret%3D7eae31c44d66567u3f4642ea80ea55f6f95ac4c%26redirect_uri%3Dhttps%3A%2F%2Fwww.mysite.com%2Fbasecamps%2Fbasecamp_access%26refresh_token%3DBAhbB0kiAbB7ImNsaWVudF9pZCI6ImMwMWM0YmY2ODRhMTMxZGE4ZWRkZDQwZjc0NDc0NTJhN2VkMTYyNjUiLCJleHBpcmVzX2F0IjoiMjAyNy0wMS0xOVQxMjowNTozMloiLCJ1c2VyX2lkcyI6WzMxNDI2NTE1XSwidmVyc2lvbiI6MSwiYXBpX2RlYWRib2x0IjoiOGI3NzAxOWRmYmI3YTQyMGM1MjI4YmU0YjBlODg5YWYifQY6Bk`

This was the one case, and If I encode the params only like this --- 

    ` foreach($params as $k => $v) 
	   { 
	      $postData .= $k . '='.urlencode($v).'&'; 
	   }
	   $postData = rtrim($postData, '&');
$ch = curl_init();`

Then again I am getting the same response as I was getting very first which is -- 

`  {"error":"authorization_expired"}  `

Rest of the code is same as I mentioned previously.
Please guide me where I am lacking in making a correct call to get the refreshed token.

**Comment by jeremy** [comment]
When you encode the full POST data, you're encoding the = and & chars also, which won't work. Your second route will work, though you need to URL-encode the keys as well as the values. Your best bet is to use `[http_build_query](http://php.net/manual/en/function.http-build-query.php)` directly.

**Comment by anupambaldi** [comment]
Hi Jeremy, 

I tried the way you suggested. I used "http_build_query" which reduces the use of "urlencode" in the code. But the response from API is still the same i.e.  

`{"error":"authorization_expired"}`

After using http_build_query I got this POST params -- 

`type=refresh&client_id=c01c4bf684a131da8eddd40f7447452a7ed16265&client_secret=7eae31c44d6665d263f4642ea80ea55f6f95ac4c&redirect_uri=https%3A%2F%2Fwww.mysite.com%2Fbasecamps%2Fbasecamp_access&refresh_token=BAhbB0kiAbB7ImNsaWVudF9pZCI6ImMwMWM0YmY2ODRhMTMxZGE4ZWRkZDQwZjc0NDc0NTJhN2VkMTYyNjUiLCJleHBpcmVzX2F0IjoiMjAyNy0wMS0zMFQxMzoxNzo1NFoiLCJ1c2VyX2lkcyI6WzMxNDI2NTE1XSwidmVyc2lvbiI6MSwiYXBpX2RlYWRib2x0IjoiOGI3NzAxOWRmYmI3YTQyMGM1MjI4YmU0YjBlODg5YWYifQY6Bk`

Please tell me if anything missing in the information I provided you. Please help me to figure it out.

**Comment by jeremy** [comment]
Looks like that's an invalid refresh_token, @anupambaldi. It's missing the embedded message signature which comes after two hyphens (`--`). Please double-check that you're faithfully extracting the refresh token from the when you first obtain the access token.

Also, note that you've exposed your confidential `client_secret` here, allowing anyone to authorize Basecamp users on behalf of your application. **I've reset your client_secret** to seal the leak.

**Comment by anupambaldi** [comment]
Hi Jeremy,
Thank you so much for the support provided by you. Everything is now sorted out. Problem was incomplete extraction of refresh token and using the same for getting new access token. Also, I will be careful about not exposing the client-secret in public, as I already didn't exposed the redirect URI but still it will be taken care.  Thank you again.

**Comment by jeremy** [comment]
You're welcome—Glad we got it sorted out!
