### ISSUE TITLE
Request for a better error code: Getting HTTP 500 when the chat bot doesn't exist

### ISSUE THREAD

**Issue by chribsen** [basecamp/bc3-api#87]
If I try to POST a message to a Campfire, using a deleted chat bot, I'm getting a `HTTP 500 Internal Error` together with a default HTML message saying "Oops, something is not working". 

Suggestion: Return `HTTP 404` instead.

Here's the URL: `https://3.basecampapi.com/<account_id>/integrations/<integration_id>/buckets/<bucket_id>/chats/<chat_id>/lines`

**Comment by jeremy** [comment]
Good call. Fixed to return 401 Unauthorized instead. (The chats/lines resource is still present, but the deleted integration is not authorized to access it.)
