### ISSUE TITLE
Download upload stream via API

### ISSUE THREAD

**Issue by crinabucur** [basecamp/bc3-api#88]
What is the correct way to obtain the stream of an upload?

The only thing that currently works, hardcoded, is a GET request at https://3.basecampapi.com/xxxxx/buckets/yyyyyy/uploads/zzzzzzz/download/versions/qqqqqqq/filename.extension , qqqqqqq being the version number I deduced via the web interface. I get "Unauthorized (401)" for trying without the "versions/qqqqqqq/" fragment.

What was really simple and straightforward in Bcx is now incredibly convoluted (i.e. simple download of a file). Please advise.

**Comment by sstephenson** [comment]
Hi @crinabucur. I’m sorry you’re having a bad experience with the API. Unfortunately we don’t offer an official way to work with older versions of uploads right now. I’m going to leave this issue open as a feature request.

(See also #69)

**Comment by crinabucur** [comment]
Hi @sstephenson , thank you for your reply. I am only interested in the latest version, not old versions. Is there any way to get the stream of the current version of an upload?

**Comment by sstephenson** [comment]
If you only need to access the latest version of an upload, you can use the [Get an upload](https://github.com/basecamp/bc3-api/blob/master/sections/uploads.md#get-an-upload) method. Its JSON response contains a `download_url` property which you can use to download the file.
