### ISSUE TITLE
Oauth2 Gem, Can't refresh access_token

### ISSUE THREAD

**Issue by mocerinoj** [basecamp/bc3-api#90]
I realize this might be more of an issue with the oauth gem I am using but I ran into the similar problem with getting an access_token.. I get `OAuth2::Error: Unsupported type: nil. Expected "web_server" or "refresh".` which I have come to figure out means that the `type='web_server|refresh` is not included in the call. I fixed this and got a proper access_token but am running into the same issue when trying to get a new access_token via the refresh_token.
```
access_token = OAuth2::AccessToken.from_hash(@client,
      refresh_token: refresh_token,
      type: 'refresh'
    )
access_token.refresh!
```

**Comment by georgeclaghorn** [comment]
Sorry, we can’t help with this. As you pointed out, this is an issue with either the OAuth library you’re using or your use of it.
