### ISSUE TITLE
500 error when uploading file to a Basecamp

### ISSUE THREAD

**Issue by highimpactDev** [basecamp/bc3-api#91]
I'm using .NET's WebClient to create and update basecamps. I'm now trying to upload files and when I use the WebClient's UploadFile method basecamp returns a 500 error.  My code looks like this 

postClient.UploadFile(https://3.basecampapi.com/ACCT#/buckets/BASECAMP#/vaults/VAULT#/uploads.json, "POST", "C:\\Users\\dsliter\\Desktop\\Bart.PNG");

I'm setting the headers with my authorization token, and username for the agent and "application/json" for the content-type. There has to be something I'm missing or not understanding after reading the documentation. Any help would be appreciated.

Thanks
Dieter Sltier

**Comment by sstephenson** [comment]
Creating an upload is a two-step process.

First, you need to [create an Attachment record](https://github.com/basecamp/bc3-api/blob/master/sections/attachments.md#create-an-attachment) with the contents of the file in the POST body. You’ll get an `attachable_sgid` in the JSON response.

Second, [create the Upload record](https://github.com/basecamp/bc3-api/blob/master/sections/uploads.md#create-an-upload). The POST body should be a JSON object with the `attachable_sgid` you received above. (See the example JSON request in the linked documentation.)

Why the two-step process? Not all files in Basecamp are Uploads. You can use the same Attachment endpoint to get an `attachable_sgid` for inserting files into [rich text content](https://github.com/basecamp/bc3-api/blob/master/sections/rich_text.md#inserting-an-image-or-file-attachment).

**Comment by highimpactDev** [comment]
Thank you for your response. I used the information you gave me and it fixed my issue. Thanks again.
