### ISSUE TITLE
Feature Request: All todos for a person.

### ISSUE THREAD

**Issue by joehohman** [basecamp/bc3-api#92]
I'm working on a Basecamp 3 version of a script to help me get all of my Basecamp to-dos on a calendar.  I wrote a similar version in BC2, but it was pretty simple because of the getAssignedTodolistsByPerson API call.  

I can't find an equivalent in the BC3 API, so at present I'm iterating through every todo in every todolist in every todoset in every project in my Basecamp account... which results in about 100 API calls just to build the list. It works, but it's incredibly slow and inefficient.

If you know a better way, or if you could implement something similar to the getAssignedTodolistsByPerson call that existed in BC2, I'd really appreciate it!  If I can get this working more efficiently, I'd probably offer it to folks as a free integration since I've found it incredibly useful.

Thanks for your help... and great job on BC3, our team is loving it!

**Comment by javan** [comment]
> I'm iterating through every todo in every todolist in every todoset in every project in my Basecamp account

You can chop that way down by using the Recordings endpoint: https://github.com/basecamp/bc3-api/blob/master/sections/recordings.md#get-recordings. You can't filter by person, but it makes collecting all to-dos (and other types) much easier.

**Comment by joehohman** [comment]
Oh, amazing! Thanks a ton!

**Comment by chandrateqforce** [comment]
Hi joehohman thanks for your info, Even I got the same requirement to get all to-dos in API callout but unable to fetch to-dos in one go, am following this sequence I hit to get all projects from their i got to lists and from their i got all todosets and then am able to fetch all to-dos so please can you help me out with endpoint url to fetch all todos 
Please provide clear steps and if possible please share your info API class to chandu.sekhar60@gmail.com

Please help me out am in need of this API basecamp 

Thanks in advance

**Comment by joehohman** [comment]
Hello chandrateqforce!  You should be able to get all the To-Dos with the Recordings endpoint, but you'll have to do multiple requests to get all the pages of data.  I abandoned my project before completing it because Basecamp added the ability for you to subscribe to your own to-dos in an iCal feed, which was the exact functionality I was trying to build.

**Comment by foxontherock** [comment]
It's special that we were able to get todos for specific user in version 2, but not in 3!  
We now need to get the complete dataset and remove the unwanted results... I think that's too much charge for nothing on both sides, your API and our app...

**Comment by ratnadeep5** [comment]
How can i get all todo's with out pagination in basecamp 3

**Comment by grncdr** [comment]
I would also like a way to get a particular users assignments via the API. I was using the recordings endpoint but it's really quite slow. Especially after another project member adds a lot of new TODOs, the ones I'm most interested in are now on the third or even fourth page.

**Comment by rosa** [comment]
Hey all, I'm sorry for the lack of updates from our side here 😓 I'm finally closing this issue since we won't be adding a filter like this to get your own to-dos to the API. The [GET Recordings](https://github.com/basecamp/bc3-api/blob/master/sections/recordings.md#get-recordings) endpoint or the iCal feed we provide for your own to-dos are the closest features we support.

**Comment by NagyWesley** [comment]
@joehohman @rosa since there is now way to filter by users on your side... is there a way to overcome the pagination page size?? doing multiple requests isn't efficient to get few tasks.

**Comment by rosa** [comment]
@NagyWesley no, sorry, [the page size is variable ](https://github.com/basecamp/bc3-api#pagination)(depending on the page you're requesting) and can't be overridden. Using the [GET Recordings](https://github.com/basecamp/bc3-api/blob/master/sections/recordings.md#get-recordings) endpoint, maybe sorting by `created_at` or `updated_at` in descending order so that you get the to-dos most recently modified first could be a good workaround for you.
