### ISSUE TITLE
Create a Ping

### ISSUE THREAD

**Issue by toddgeist** [basecamp/bc3-api#93]
Can we Ping somebody through the API?

**Comment by rosa** [comment]
@toddgeist you can't do that right now, and if we ever implemented something like this, it'd likely be around [chatbots](https://github.com/basecamp/bc3-api/blob/master/sections/chatbots.md#chatbots). What you can do, however, is to ping an interactive chatbot using the UI and then have the chatbot reply directly to the ping. Do you think this could fit your purpose?

**Comment by toddgeist** [comment]
I think it will.  Thanks :-)

**Comment by rosa** [comment]
👍 👍 Great! Let us know if you encounter any issues with that 😄

**Comment by crockpotveggies** [comment]
Hi there, I noticed that other issues were closed in favour of this, but I'd be really interested in re-opening. I work in an organization that's distributed across the globe, and there are multiple chat mechanisms in place. We are very interested in bridging our chat apps together, and having a fleshed-out `/pings` API would be very useful.

**Comment by crockpotveggies** [comment]
From my understanding, the logic behind making chats "simpler" was so that Basecamp could work well for non-technical people. However, I would argue that exposing an API let's us savvy folk do what we need to do while not compromising the usability of the UI.

**Comment by tino** [comment]
I would really like a way to send a ping from a chatbot! We currently use a shared Campfire to ping people when their notification fails, but that creates noise for all (as you stay unfollowed on a campfire that pings you...).

Please reopen!

**Comment by rosa** [comment]
@tino did you try having a chatbot _reply_ to a ping that a user started using the UI? Maybe that works for you!

**Comment by kingharrison** [comment]
@rosa Is there any movement on this? I have a use case where our application is enterprise level and we sit behind a VPN. We dont have a way to initiate a chatbot back to our application because of security, but we do have the ability to send out messages (we do this with Slack for our internal team). This would be quite nice if we could send Pings from our app for the users. Any chance of adding this? If not, can I ask why to better understand it?

**Comment by kingharrison** [comment]
Thank you for the response @rosa !

First, little bit of fanboying. We REALLY love Basecamp 3. We are starting to setup a project for each of our customers to communicate with them to handle our application. We write an Enterprise level application that handles procurement for warehouse distribution. We have over 500 users across a lot of accounts, and each account would have its own Basecamp Project. The application we write and install exists completely behind our customer's VPNs and there is no public facing allowed. We run on something called a Power Server on the IBM i OS. This server does some stuff VERY well, but also some things it is just weak on. One of the things we have discovered is that the database allows you to access RESTful services via SQL statements (it is actually quite cool https://developer.ibm.com/tutorials/dm-1105httprestdb2/ example:
```
SELECT 
   DB2XML.HTTPGETCLOB('http://www.ibm.com','') 
FROM SYSIBM.SYSDUMMY1
``` )

So now we are looking at how to deliver private information to a single user generated by our application. Basecamp Pings seemed like a very interesting way to do this as we like the software so much. 

Noting the small percentage of users that use the API (which looks to be about 150,000 users based off the percentage and numbers on the front of the site) I do think charging a premium for API access of new features might be possible? 

I wouldn't be scared in potentially funding some of this if need be. 

thank you again for responding!

**Comment by kingharrison** [comment]
Ok if it isn't a Ping could we send a notification in the Hey! inbox?

**Comment by rosa** [comment]
Thanks for the background, that was really interesting! Charging an extra for new API features is not currently in our plans, I'm sorry about that, but thanks for the suggestion anyway. I'm glad you like Basecamp 3. 

> could we send a notification in the Hey! inbox?

You can't directly create notifications but any action that triggers notifications by itself (like assigning a to-do, or posting a message mentioning someone or adding them as subscribers) will do this. The problem I see with your use case is that you need this to be private to a user? In that case, would having a private project that only each individual can access be a possible solution for you?

**Comment by kingharrison** [comment]
Is the mechanism that triggers a notification accessible at all? Knowing perhaps some sort of authorization key, which Basecamp you own, and the user email to trigger a notification? Even if it just sent one sentence?

Doing a project per person isn't really feasible just based off scope.

**Comment by rosa** [comment]
@kingharrison, no, sorry, that's not exposed, not even in the UI. The only way to trigger notifications is via actions that trigger notifications themselves, and from these [mentioning someone](https://github.com/basecamp/bc3-api/blob/master/sections/rich_text.md#inserting-a-mention) would be your best bet.

**Comment by kingharrison** [comment]
Ooooohhh, would it be possible to mention someone that triggers a notification, but the mention doesnt go anywhere?

**Comment by rosa** [comment]
No, I'm afraid not. The mention needs to be in a message, document, and comment, to-do's description, to-do list's description... stored somewhere. When saving the content that contains the mention is when the notification is delivered.

**Comment by kingharrison** [comment]
Gotcha. Well I think I have exhausted all my possible avenues. Sounds like it would take new development to accomplish what were all looking to do. 

Thank you for walking me through it.

**Comment by toddgeist** [comment]
As the guy who originally who posted this, let me just vote once again for this feature.  It is still needed.  :-)

**Comment by kingharrison** [comment]
It does add a lot of value to the product I believe. Something I would gladly pay more for.

-King Harrison
Sent from iPhone
Please excuse all typos

________________________________

**Comment by bondz** [comment]
Just mentioning again that ping support would be wonderful.

**Comment by mrkalmdn** [comment]
We also want this feature for our internal applications. Hoping this would be implemented soon. 🙏

**Comment by jeissonneira** [comment]
Ditto on sending Pings from the API via a chatbot.

**Comment by rosa** [comment]
Hey! Thanks to @jeissonneira following up in https://github.com/basecamp/bc3-api/issues/217#issuecomment-670235778, I realised I hadn't been very clear on the possibilities of using chatbots to ping users. 

I said the way to achieve this would be to initiate a ping with the chatbot via the UI and then have the chatbot reply to it. This sounds as if the chatbot could only ping the user in the _immediate_ reply to the user's message. This is not the case! The only requirement is that the user _initiates_ the ping so that the ping exists. Once the ping exists, the chatbot can continue posting to this ping as if it was a Campfire. The only thing the chatbot can't do is to start a new ping with a user that hasn't pinged them before. It's possible this covers the use cases of people commenting here 🤞

**Comment by dbader** [comment]
Apologies for reviving an already closed issue -- but for the record, I'd also appreciate the ability to send a new ping/direct message through the Basecamp API 🙂

Our use case is similar to what has been mentioned on this thread: creating a chatbot that can notify Basecamp users privately via pings and without requiring the user to initiate a private conversation with the bot first. 

I imagine the API for this could look similar to the chatbots `lines_url` endpoint that exists, e.g. doing a `POST` to `https://3.basecampapi.com/<account_id>/pings/<user_id>/lines` would send a ping to the user, creating the conversation first if needed.

It's been great to see new features being added to Basecamp recently and if we could get a pings API for chatbots next that'd be the icing on the cake 🙂
