### ISSUE TITLE
Get all client approvals and files for a time period?

### ISSUE THREAD

**Issue by andreimoment** [basecamp/bc3-api#94]
I will need to periodically (most likely every few minutes) download all client approvals and associated files and email them to a designated email address. 

How should I approach this? I am not seeing approvals amongst the options in the recordings list which would allow querying multiple projects with one api call. *Get client approvals* requires specifying the basecamp id and would require an api call for each project. 

Also, would the files mentioned in the `<bc-attachment>` part of the client approval `content` be available for download?

`
"content": "<div>OK, here's another one! We've got this business card worked up, just need your yes or no to proceed. Thanks!<br><br></div>\n<bc-attachment sgid=\"BAh7CEkiCGdpZAY6BkVUSSIvZ2lkOi8vYmMzL0F0dGFjaG1lbnQvMTAxOTczMDU0MT9leHBpcmVzX2luBjsAVEkiDHB1cnBvc2UGOwBUSSIPYXR0YWNoYWJsZQY7AFRJIg9leHBpcmVzX2F0BjsAVDA=--010588da163ae8b6777939a970136f79d55b48b8\" content-type=\"image/jpeg\" url=\"https://3.basecamp.com/195539477/blobs/65eb219272af7a61ba216a85ef1f7032cf7a25e1/previews/full/images-images-bcard-2.jpg\" href=\"https://3.basecamp.com/195539477/blobs/65eb219272af7a61ba216a85ef1f7032cf7a25e1/download/images-images-bcard-2.jpg\" filename=\"images-images-bcard-2.jpg\" filesize=\"170483\" width=\"1824\" height=\"992\" previewable=\"true\"><figure>\n    <img srcset=\"https://3.basecampapi.com/195539477/blobs/65eb219272af7a61ba216a85ef1f7032cf7a25e1/previews/full/images-images-bcard-2.jpg?dppx=1 1x, https://3.basecampapi.com/195539477/blobs/65eb219272af7a61ba216a85ef1f7032cf7a25e1/previews/full/images-images-bcard-2.jpg?dppx=2 2x, https://3.basecampapi.com/195539477/blobs/65eb219272af7a61ba216a85ef1f7032cf7a25e1/previews/full/images-images-bcard-2.jpg?dppx=3 3x, https://3.basecampapi.com/195539477/blobs/65eb219272af7a61ba216a85ef1f7032cf7a25e1/previews/full/images-images-bcard-2.jpg?dppx=4 4x\" src=\"https://3.basecampapi.com/195539477/blobs/65eb219272af7a61ba216a85ef1f7032cf7a25e1/previews/full/images-images-bcard-2.jpg\" alt=\"Images images bcard 2\">\n  <figcaption>\n      images-images-bcard-2.jpg\n  </figcaption>\n</figure></bc-attachment>",
    "subject": "Business card",
`

**Comment by rosa** [comment]
> How should I approach this? I am not seeing approvals amongst the options in the recordings list which would allow querying multiple projects with one api call. Get client approvals requires specifying the basecamp id and would require an api call for each project.

That's correct, you need the `bucket_id` to query the approvals. What I suggest is to use [webhooks](https://github.com/basecamp/bc3-api/blob/master/sections/webhooks.md). We now support events for recordings of type `Client::Approval::Response`, so you could setup a webhook that sends you a request whenever a new client response is posted for an approval. When that happens you can trigger that email flow you mention.

> Also, would the files mentioned in the <bc-attachment> part of the client approval content be available for download?

We don't have documented API endpoints to download attachments yet, but you can use the URL included in `href` attribute of the `bc-attachment` element and replace the app's host with the API host. That is, 
```
https://3.basecampapi.com/195539477/blobs/65eb219272af7a61ba216a85ef1f7032cf7a25e1/download/images-images-bcard-2.jpg
``` 
from your example.
