### ISSUE TITLE
Feature Request: Add Chat to Latest Activity

### ISSUE THREAD

**Issue by toddgeist** [basecamp/bc3-api#95]
I love the Latest Activity feed. It would be really great to be able to add to that feed somehow so that we could post links to things that happen outside of Basecamp, like for example, when somebody closes a case in an external ticket system.

We can almost use the chatbot API, but the stuff we dump in there doesn't show up on the Lastest Activity unless somebody else happens to be chatting at the same time.  If there was a way to make a new Chat Line show on Latest History, that would do it.

What do you think?

Todd

**Comment by forrestolivo** [comment]
+1, I would definitely use this too.

**Comment by rosa** [comment]
@toddgeist thanks for the suggestion! Currently we don't have plans to add chat lines created by chatbots to our Activity feed (we exclude them on purpose, to avoid cluttering the feed with the bots' talk). Besides, we only post chat activity to the Activity feed every few hours, so even if we allowed chatbots, it probably wouldn't fit your purpose.

There is something else you could do. What about using any other element in Basecamp to track these kind of events (closing a case in a external ticket system), in a way they show up in the Activity feed? For example, if you map your cases in an external ticket system with todos in Basecamp, you could use the [Todos endpoints](https://github.com/basecamp/bc3-api/blob/master/sections/todos.md#to-dos) to:
- Create a todo when a new case is opened in your external ticket system. 
- Complete a todo when a case is closed there.

Both of these events would show up in the Activity feed, without being subject to holds for a few hours as chat lines are.
