### ISSUE TITLE
quick question: Does basecamp API OAuth2 support implicit grants? 

### ISSUE THREAD

**Issue by xinghengwang** [basecamp/bc3-api#96]
I am doing a single page app, but I don't see any mention of implicit grants in Basecamp's documentation.

**Comment by georgeclaghorn** [comment]
Hey @xinghengwang,

We support the [user-agent flow](https://tools.ietf.org/html/draft-ietf-oauth-v2-05#section-3.5) from an earlier draft of the OAuth 2.0 protocol. That’s what you’re looking for.

Hope that helps!
