### ISSUE TITLE
Basecamp Application issue

### ISSUE THREAD

**Issue by harisheidiko** [basecamp/bc3-api#97]
Hi Team,
              I am integrating Basecamp3 with my application.I am facing an issue with functionality of basecamp events.In todo I deleted a comment, after that moving that Todo from one project to another project.Now I am getting ToDo with deleted comment also.Due to this my integrations getting complaints from customers.Quick help is needed.Thanks in advance

**Comment by georgeclaghorn** [comment]
Please send an email to support@basecamp.com with more details and a specific example of the problem you’re seeing and we’ll be happy to help you.
