### ISSUE TITLE
getting authorization_expired when try to refresh access token

### ISSUE THREAD

**Issue by eslam-mahmoud** [basecamp/bc3-api#98]
Hello,

steps

1. From our web app user integrate normally with Basecamp
2. we can call api normally
3. user update his password
4. we get "401 Unauthorized" and message say access token is expired
5. we call https://launchpad.37signals.com/authorization/token tring to get new access token with parameters type, client_id, client_secret, redirect_uri, refresh_token 
6. we get error  400 authorization_expired

can we refresh the access token when user change his password on basecamp or we need to ask, users to reintegrate ?

**Comment by georgeclaghorn** [comment]
Hey @eslam-mahmoud, you’re correct: you need to request authorization anew. A password change expires all existing authorizations.

**Comment by eslam-mahmoud** [comment]
@georgeclaghorn ok so if access token expired should the end point i use to refresh be https://launchpad.37signals.com/authorization/token or https://launchpad.37signals.com/authorization/new ?

**Comment by chribsen** [comment]
According to my implementation, you should use `/authorization/token` to refresh expired tokens. 
Remember to set HTTP header `Content-Type` to `application/json`.

**Comment by eslam-mahmoud** [comment]
@chribsen in https://github.com/basecamp/bcx-api/issues/32 @jeremy said that the content-type should be "application/x-www-form-urlencoded"

**Comment by chribsen** [comment]
My mistake. `application/x-www-form-urlencoded` is correct.

**Comment by eslam-mahmoud** [comment]
Unfortunately i still have same problem 
My implementation in php to get new access token using refresh token is like that

        $vars = array(
            'type' => 'refresh',
            'client_id' => $clientID,
            'redirect_uri' => urlencode($redirectURL),
            'client_secret' => $clientSecret,
            'refresh_token' => urlencode($refreshToken)
        );

        $c = $this->curlHandle('https://launchpad.37signals.com/authorization/token');
        curl_setopt($c, CURLOPT_HTTPHEADER, array("Content-Type:application/x-www-form-urlencoded"));
        curl_setopt($c, CURLOPT_POST, true);
        curl_setopt($c, CURLOPT_POSTFIELDS, http_build_query($vars));
        curl_setopt($c, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($c, CURLOPT_TIMEOUT, 30);
        curl_setopt($c, CURLOPT_CONNECTTIMEOUT, 3);

        $response = curl_exec($c);
        $http_code = curl_getinfo($c, CURLINFO_HTTP_CODE);
        $curlError = curl_error($c);

and the result is 

        [response] => {"error":"authorization_expired"}
        [http_code] => 400
        [curlError] => 

Am I missing anything ? Note: i just integrated it should not be expired at all 

I reviewed the discussion in https://github.com/basecamp/bc3-api/issues/85 but could not find anything i missed

**Comment by eslam-mahmoud** [comment]
Sorry found the problem i should not use `urlencode` the `http_build_query` handle the encoding
