### ISSUE TITLE
Invoking APIs from Browser...

### ISSUE THREAD

**Issue by xinghengwang** [basecamp/bc3-api#99]
Hi, 

Since I have a single page app. I am calling the API from within browser. 
I got the user_agent flow for OAuth to work. 
(See previous question)
https://github.com/basecamp/bc3-api/issues/96

However, after obtaining the token. 
I run into two issues: 

1. I keeping getting CORS error: 

XMLHttpRequest cannot load. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
Do your API allow CORS calls? 

2. Another issue is that documentation for api calls seems to require 'User-Agent' to be set to my email and name. However, according to a lot of browsers (such as Chrome), for Ajax calls, we aren't allowed to set 'User-Agent' header.  Is there a work around?

**Comment by Bangerous10** [comment]
Hello!

I am having the same issue for 1 when trying to 'authenticate from scratch' through the browser. On step 4 of [the guide](https://github.com/basecamp/api/blob/master/sections/authentication.md#oauth-2-from-scratch), the app is making a backchannel request to trade the given verification code for an access token. However, this backchannel request is denied with the same error as above: 

> No 'Access-Control-Allow-Origin' header is present on the requested resource

Therefore, is it possible to authenticate from the client/browser if cross-domain requests are always blocked?

**Comment by rosa** [comment]
We haven't got plans to implement CORS in the near future, but that might certainly change! In the meantime I'm closing this in favour of #54.
